### DISCUSSION TITLE
tekton-triggers-example-sa cannot list resource "clusterinterceptors" in API group "triggers.tekton.dev at the cluster scope

### DISCUSSION THREAD

**Discussion by fabioluciano** [tektoncd/triggers#1595] [Q&A]
Im trying to install tekton trigger in my cluster, but after install all manifests and install RBAC, i still getting this error:

```
E0523 15:41:14.236893       1 reflector.go:140] k8s.io/client-go@v0.25.9/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ClusterInterceptor: failed to list *v1alpha1.ClusterInterceptor: clusterinterceptors
.triggers.tekton.dev is forbidden: User "system:serviceaccount:tekton-pipelines:tekton-triggers-example-sa" cannot list resource "clusterinterceptors" in API group "triggers.tekton.dev" at the cluster scope
```

My configuration:

**eventlistener**

```yaml
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-server-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: bitbucket-server-triggers
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            - name: secretRef
              value:
                secretName: event-listerner-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                - repo:refs_changed
      bindings:
        - ref: bitbucket-server-binding
      template:
        ref: bitbucket-server-template

```

**rbac**
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-example-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-example-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-example-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-example-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
```

![image](https://github.com/tektoncd/triggers/assets/499057/a5cf87e2-4b9c-4337-8ea7-34ec21f7704f)
![image](https://github.com/tektoncd/triggers/assets/499057/dd627aa0-0e63-4ac8-bdc2-8f9561566df8)
