### DISCUSSION TITLE
Trigger Binding type array

### DISCUSSION THREAD

**Discussion by sunyeongchoi** [tektoncd/triggers#1598] [Q&A]
Is there any way to bind parameters defined as array type to array?
I wonder why it was not possible to bind to an array type.
Am i missing something?

**Comment by palonza** [comment]
Hi @sunyeongchoi , 

do you have many ways, depend your needs:

1. array format: Ensure that the array is provided in the correct format when binding the parameter. Arrays can be specified using YAML or JSON syntax

```yaml
myArrayParam:
  - value1
  - value2
  - value3
```

2. binding method: When binding parameters to the array type, you have a couple of options. You can use the param field or the params field in the trigger event

```yaml
params:
  - name: myArrayParam
    value:
      - value1
      - value2
      - value3
```

3. using params:  If you're binding multiple parameters, you can use the params field in the trigger event. Here's an example

```yaml
params:
  - name: myArrayParam
    value:
      - value1
      - value2
      - value3
  - name: anotherArrayParam
    value:
      - value4
      - value5
```
