### DISCUSSION TITLE
CSRF header not found in request with bitbucket and tekton trigger with webhooks

### DISCUSSION THREAD

**Discussion by anandjaisy** [tektoncd/triggers#1649] [Q&A]
I have set up the Tekton Trigger to auto-run the pipeline when certain code is pushed to the bitbucket repository.

```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-listener
  namespace: fetebird-common
spec:
  serviceAccountName: git-service-account
  triggers:
    - name: bitbucket-triggers
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            - name: secretRef
              value:
                secretName: git-ssh-key-secret
                secretKey: ssh-privatekey
            - name: eventTypes
              value:
                - repo:refs_changed
      bindings:
        - ref: bitbucket-trigger-binding
      template:
        ref: bitbucket-trigger-template
```

Bitbucket webhook setup

![image](https://github.com/tektoncd/triggers/assets/84489031/d2ac3752-4130-4d68-a7ca-0d1005bc40f8)

The details of the webhook

![image](https://github.com/tektoncd/triggers/assets/84489031/b8ed646a-9c36-4a82-ab12-f8bd7ac2e54f)

Error Forbidden - CSRF header not found in request
