### DISCUSSION TITLE
how many interceptors can I have at same even listner? how many filters? It is very hard to understand

### DISCUSSION THREAD

**Discussion by alansenairj** [tektoncd/triggers#1766] [Q&A]
Hi. I am trying to create triggers to filter both push in master branch and approved merge in master branch too. But payload are not equal. I think I am getting some conflicts to apply filters. I don't know how to pass a condition to one pass and other not crashes. 

```
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener-payload-test
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline 
  triggers:
    # ====== Trigger for Push Events (portal-server) ======
    - name: "gitlab-push-portal-server"
      interceptors:
        - ref:
            name: gitlab  # GitLab interceptor reference
          params:
          - name: "secretRef"
            value:
              secretName: "gitlab-token-secret-el-use"
              secretKey: "secretToken"     # NEED THIS! CREATE A SECRET WITH THE TOKEN. USE IT IN CURL POST REQUEST. OTHERWISE WILL NOT WORK
          - name: "eventTypes"  # List of events to intercept in gitlab webhook
            value:
                - "Push Hook"
                - "Merge Request Hook"
        - ref:
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
            name: cel
          params:
            - name: "filter"
              value: "body.project.git_http_url == 'http://samegit/alanaguinaga/portal-server.git'"
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"   # Extract the branch name
                - key: commit_sha
                  expression: "body.checkout_sha.truncate(9)"  # Extract the commit id 8-chars

        - ref:
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
            name: cel
          params:
            - name: "filter"
              value: |-
                
                body.object_attributes.action == "approved" &&
                body.object_attributes.target_branch == "master" &&
                body.project.git_http_url == "http://samegit/alanaguinaga/portal-server.git"
                

            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.object_attributes.target_branch"   # Extract the branch name
                - key: commit_sha
                  expression: "body.object_attributes.merge_commit_sha.truncate(9)"  # Extract the commit id 8-chars

      bindings:
        - ref: gitlab-push-portal-server  # Reference the TriggerBinding
      template:
        ref: gitlab-trigger-template-portal-server  # Reference the TriggerTemplate`

```
        
```
        {"severity":"info","timestamp":"2024-09-26T05:36:27.474Z","logger":"eventlistener","caller":"sink/sink.go:420","message":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"\\nbody.object_attributes.action == \\\"approved\\\" &&\\nbody.object_attributes.target_branch == \\\"master\\\" &&\\nbody.project.git_http_url == \\\"http://gitlab-sema-system.apps.ocp.sema.mt.gov.br/alanaguinaga/portal-server.git\\\"\" failed to evaluate: no such key: object_attributes","commit":"f76be74","eventlistener":"gitlab-listener-payload-test","namespace":"cicd-tools","/triggers-eventid":"5125100d-7d13-414e-bf23-24d39678c12d","eventlistenerUID":"f22f2b89-bc99-4a0f-a986-924ae420c407","/triggers-eventid":"5125100d-7d13-414e-bf23-24d39678c12d","/trigger":"gitlab-push-portal-server"}
```
