### DISCUSSION TITLE
How to get latest sintax of cel and most new api features?

### DISCUSSION THREAD

**Discussion by alansenairj** [tektoncd/triggers#1768] [Q&A]
The tail of documentation is too long and very spread.  It is very hard to use just oficial documentation to get more reference to apply filters and overlays. 
If I start to using cel sintax from Google course it crashes too much. 
It is realy hard to create and manipulate and learn it. How can I use a better sintax?
I discovered extensions using by a blog. 
Other guy is declaring api inside cel kind field. Where he get it?
What is the most oficial source to keep me informed about updates and improvments?

**Comment by bigkevmcd** [comment]
@alansenairj What would you like to see added?

The Tekton docs link to the upstream documentation https://tekton.dev/docs/triggers/cel_expressions/#cel-go-extensions which includes the libraries?

The cel-eval tool can be a bit tricky, but it will make it easier to debug your expressions.

There are a lot of examples in the tests for the CEL interceptor https://github.com/tektoncd/triggers/blob/main/pkg/interceptors/cel/cel_test.go

And there are some examples in the repository https://github.com/tektoncd/triggers/blob/d308fd26c141f4cfab5903fa119f583a91402c5f/examples/v1beta1/trigger-ref/trigger.yaml#L12 

Which Google course are you following?

**Reply by alansenairj** [reply]
Hi, thanx for your reply.

this one info was crucial for me. I was wrong about documentation. It was there. Thank you. 

"Accessing data added by [Interceptors](https://tekton.dev/docs/triggers/interceptors/)
An interceptor can add additional useful data that can be used by a TriggerBinding. Data added by interceptors can be accessed under the top-level extensions field e.g. $(extensions.field-name). In the following example, the CEL interceptor adds a field that is then accessed by the trigger binding:"


About cel expressions, it is hard to work with. But I see advantage in its use so I was insisting to understand it and now I can put it to work. Their learning curve is hard. 

The way yaml encapsulates cel expression syntax was the problem for me when I am trying to learn it. 

And I think logs are very polluted and I did a ternary evaluation to test and print some output to get it more visible but that is not the way it works. I am not a programmer, I am learning but I will show to you a thing I tried to do: 

```
                - key: namespace
                  expression: |
                    body.ref == 'refs/heads/develop' ? 'portal-web-desenv' :
                    (body.ref == 'refs/heads/master' ? 'portal-web-prd' :
                    (body.ref == 'refs/heads/homolog' ? 'portal-web-hom' :
                    '---erro: branch não permitida-----'))
```
I am expecting some error in log to get it more visible. But it just filters and it not transforms values nesting those conditions there. But I think it could be easier to test if I could get some better message in log indicating my filter works. 

Google course is : https://codelabs.developers.google.com/codelabs/cel-go?hl=pt-br#0

**Reply by bigkevmcd** [reply]
That looks like an `overlay` expression, in which case, do you not see the overlay field `extensions.namespace` if it evaluates successfully.

I am looking at the possibility of using a CEL extension to let you "bind" variables before evaluating the expression.

This _might_ simplify this sort of long-expression that is hard to read and debug.

The basic idea is that you'd do something like:

```yaml
    interceptors:
    - name: "validate body and add field"
      ref:
        name: "cel"
      params:
      - name: "bindings"
        value:
          - name: isDevelop
            value: body.ref == 'refs/heads/develop'
          - name: isMaster
            value: body.ref == 'refs/heads/master'
      - name: "overlays"
        value:
        - key: namespace
          expression: isDevelop ? 'portal-web-desenv' : isMaster ? 'portal-web-prd'
```

This isn't implemented _yet_ but I have an experimental branch.

It's where I think things could go (and make use of a CEL extension for doing this) and it might help simplify long complex expressions.
