### ISSUE TITLE
Unable to run event-listener

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/triggers#1008]
# Expected Behavior

Unable to start event listener

```bash
✗  tkn version                                             
Client version: 0.16.0
Pipeline version: v0.20.1
Triggers version: v0.11.2
Dashboard version: v0.14.0

➜ k get eventlistener                                                   
NAME                            ADDRESS                                                             AVAILABLE   REASON
build-pipeline-event-listener   http://el-build-pipeline-event-listener.ci.svc.cluster.local:8080   False       MinimumReplicasUnavailable

➜ k get po                 
NAME                                                READY   STATUS             RESTARTS   AGE
el-build-pipeline-event-listener-7886bdcf54-75k7c   0/1     CrashLoopBackOff   6          5m7s

➜ klo el-build-pipeline-event-listener-7886bdcf54-75k7c --all-containers
{"level":"info","ts":"2021-03-19T02:56:29.922Z","caller":"logging/config.go:115","msg":"Successfully created the logger.","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/logging/config.go","line":"115","function":"knative.dev/pkg/logging.newLoggerFromConfig"}}
{"level":"info","ts":"2021-03-19T02:56:29.922Z","caller":"logging/config.go:116","msg":"Logging level set to: info","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/logging/config.go","line":"116","function":"knative.dev/pkg/logging.newLoggerFromConfig"}}
{"level":"info","ts":"2021-03-19T02:56:29.922Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/logging/config.go","line":"78","function":"knative.dev/pkg/logging.enrichLoggerWithCommitID"}}
{"level":"info","ts":"2021-03-19T02:56:29.922Z","logger":"eventlistener","caller":"logging/logging.go:47","msg":"Starting the Configuration eventlistener","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/logging/logging.go","line":"47","function":"github.com/tektoncd/triggers/pkg/logging.ConfigureLogging"}}
E0319 02:56:29.933248       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ci:project-crm-backend-trigger-sa" cannot list resource "configmaps" in API group "" in the namespace "ci"
E0319 02:56:31.219149       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ci:project-crm-backend-trigger-sa" cannot list resource "configmaps" in API group "" in the namespace "ci"
{"level":"fatal","ts":"2021-03-19T02:56:31.846Z","logger":"eventlistener","caller":"logging/logging.go:53","msg":"failed to start configuration manager: error waiting for ConfigMap informer to sync","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/logging/logging.go","line":"53","function":"github.com/tektoncd/triggers/pkg/logging.ConfigureLogging"},"stacktrace":"github.com/tektoncd/triggers/pkg/logging.ConfigureLogging\n\tgithub.com/tektoncd/triggers/pkg/logging/logging.go:53\nmain.main\n\tgithub.com/tektoncd/triggers/cmd/eventlistenersink/main.go:67\nruntime.main\n\truntime/proc.go:204"}

```

event listener:

```
# see more details about cel filtering
# https://bigkevmcd.github.io/kubernetes/tekton/pipeline/2020/02/05/cel-interception.html
# more on cel expressions is here: https://tekton.dev/docs/triggers/cel_expressions/
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-pipeline-event-listener
  namespace: ci
spec:
  serviceAccountName: project-crm-backend-trigger-sa
  triggers:
  - name: project-crm-backend-dev-trigger
    interceptors:
    - github:
        secretRef:
          secretName: project-crm-backend-webhook-secret
          secretKey: secret-token
        eventTypes:
        - push
    - cel:
        filter: "body.ref == 'refs/heads/develop'"
    bindings:
    - ref: project-crm-backend-dev-env
    - ref: github-trigger-binding
    template:
      name: build-pipeline-trigger-template
```

# Actual Behavior

event listener pod is in CrashLoopBackOff state. I am trying to run that listener in a different namespace (CI), while tekton's pipeline/trigger/dashboard runs in a different namespace:

```
✦ ➜ kgpo -n tekton-pipelines 
NAME                                                 READY   STATUS    RESTARTS   AGE
tekton-dashboard-75d6dc7949-sbs5t                    1/1     Running   0          10d
tekton-pipelines-controller-6c59f5f6fb-2dr5d         1/1     Running   0          10d
tekton-pipelines-webhook-6fdf785785-qgx4d            1/1     Running   0          10d
tekton-triggers-controller-84d74cc75c-pphpz          1/1     Running   0          10d
tekton-triggers-core-interceptors-6b4764b4f5-tmn25   1/1     Running   0          10d
tekton-triggers-webhook-9b855cd4d-ppnfx              1/1     Running   0          10d
```

# Additional Info

- Kubernetes version:
```
✦ ➜ kubectl version                                                                                             
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Tekton Pipeline version:

```
✗  tkn version                                             
Client version: 0.16.0
Pipeline version: v0.20.1
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
