### ISSUE TITLE
TriggerTemplate resource should not need metadata.namespace

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#101]
# Expected Behavior
When a templated resource in a TriggerTemplate is created without specifying a namespace, I expect the resource to be created in the same namespace as the EventListener which triggered this creation.

Currently, one needs to specify the namespace as a parameter in the TriggerTemplate for resources to be created properly.

# Actual Behavior
When a templated resource is created without specifying a namespace, the resource fails to be created with the following error:
```
PipelineResource.tekton.dev "git-resource-6chwh" is invalid: metadata.namespace: Required value
```

Example resource template:
```
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: git-resource-$(uid)
    labels:
      triggers: "true"
      triggersUid: "$(uid)"
  spec:
    type: git
    params:
    - name: url
      value: $(params.url)
    - name: revision
      value: $(params.revision)
```

# Steps to Reproduce the Problem

1. Create a TriggerTemplate containing a resource template like the example above without a `metadata.namespace` filed.
2. Create a TriggerBinding and EventListener to use the TriggerTemplate
3. Send an POST request to the EventListener sink pod
