### ISSUE TITLE
Replicas field is misleading while using customresource(knative)

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/triggers#1019]
# Expected Behavior
* When user provides replicas as 3 part of event listener, expected to create 3 pods of event listener.
# Actual Behavior
* But it just creates one pod when user chooses custom resource type as knative instead of native k8s resources.
Seems it's misleading to use replicas in this scenario.
(may be a webhook validation error/warning would help :thinking: )

# Steps to Reproduce the Problem
 ``` 
  cat << EOF| oc apply -f -
  ---
  apiVersion: triggers.tekton.dev/v1alpha1
  kind: EventListener
  metadata:
    name: github-knative-listener
  spec:
    triggers:
      - name: github-listener
        interceptors:
          - github:
              secretRef:
                secretName: github-secret
                secretKey: secretToken
              eventTypes:
                - pull_request
          - cel:
              filter: "body.action in ['opened', 'synchronize', 'reopened']"
        bindings:
          - ref: github-pr-binding
        template:
          ref: github-template
    replicas: 3      
    resources:
      customResource:
        apiVersion: serving.knative.dev/v1
        kind: Service
        spec:
          template:
            spec:
              serviceAccountName: pipeline
              containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
  ---
  apiVersion: triggers.tekton.dev/v1alpha1
  kind: TriggerBinding
  metadata:
    name: github-pr-binding
  spec:
    params:
      - name: gitrevision
        value: $(body.pull_request.head.sha)
      - name: gitrepositoryurl
        value: $(body.repository.clone_url)
  
  ---
  apiVersion: triggers.tekton.dev/v1alpha1
  kind: TriggerTemplate
  metadata:
    name: github-template
  spec:
    params:
      - name: gitrevision
      - name: gitrepositoryurl
    resourcetemplates:
      - apiVersion: tekton.dev/v1alpha1
        kind: TaskRun
        metadata:
          generateName: github-run-
        spec:
          taskSpec:
            inputs:
              resources:
                - name: source
                  type: git
            steps:
              - image: ubuntu
                script: |
                  #! /bin/bash
                  ls -al $(inputs.resources.source.path)
          inputs:
            resources:
              - name: source
                resourceSpec:
                  type: git
                  params:
                    - name: revision
                      value: $(tt.params.gitrevision)
                    - name: url
                      value: $(tt.params.gitrepositoryurl)
  EOF  
```                  
2. Verify number of pods (you will just see one pod)

# Additional Info

- Kubernetes version: v1.20.0+5fbfd19

  **Output of `oc version`:**

  ```
   oc version                                                                                                        
    Client Version: 4.7.0-202103010125.p0-c66c03f
    Server Version: 4.7.1
    Kubernetes Version: v1.20.0+5fbfd19
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
 tkn version
  Client version: 0.17.0
  Pipeline version: v0.22.0
  Triggers version: v0.12.1
```
