### ISSUE TITLE
Embedded ResourceTemplates aren't updated on EventListener Update

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#1026]
# Expected Behavior

When I update an embedded trigger in an EventListener, the update should be active for future trigger invocations.

# Actual Behavior

The EventListener/Trigger is successfully updated (kubectl get shows the right output), but when the trigger is invoked the old config is used.

# Steps to Reproduce the Problem

1. Create a trigger embedded in an EventListener. Example:
    ```
    apiVersion: triggers.tekton.dev/v1alpha1
    kind: EventListener
    metadata:
      name: trigger
    spec:
      triggers:
        - name: trigger
          template:
            spec:
              resourcetemplates:
                - apiVersion: tekton.dev/v1beta1 
                  kind: TaskRun
                  metadata:
                    generateName: echo-hello-world-run-
                  spec:
                    taskSpec:
                        steps:
                          - name: build-sources
                            image: ubuntu
                            command:
                              - /bin/bash
                            args: ['-c', 'echo hello!']
    ```
2. Modify the trigger (e.g. rename it)
3. Invoke the trigger - the change is not respected.

I suspect that we're caching the value of the EL/Trigger somewhere, and it isn't getting updated.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

   ```
  Client version: 0.15.0
  Pipeline version: v0.22.0
  Triggers version: devel (1965f62)
   ```

**Comment by jmcshane** [comment]
adding some thoughts after doing some basic diagnostics:

* It appears that the trigger lister doesn't have a watch on changes to triggers
* We may want to take a look at other CRD values as well, such as changing a pipelineSpec in a triggertemplate

**Comment by jmcshane** [comment]
https://github.com/tektoncd/triggers/blob/main/cmd/eventlistenersink/main.go#L94 <- timeout in the lister factory

there may be some issue with the way this is set up because I have seen it take more than 30 seconds to resolve the updates

**Comment by jmcshane** [comment]
a place to start could be to listen for the triggers on the configured target namespaces and force resync of the lister factory, like is done for the eventlistener here: https://github.com/tektoncd/triggers/blob/main/pkg/reconciler/v1alpha1/eventlistener/controller.go#L72

**Comment by jmcshane** [comment]
I just did an experiment with the following configs.

1. Deploy pipelines and triggers
2. Deploy this example: https://github.com/tektoncd/triggers/tree/main/examples/triggers
3. Update the following:

```yaml
#trigger.yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'pull_request')"
  template:
    ref: pipeline-template
```

```yaml
#triggertemplate.yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: message
    description: The message to print
    default: This is the default message
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run-
    spec:
      pipelineSpec:
        params:
        - name: message
          type: string
        tasks:
        - name: task1
          params:
          - name: message
            value: $(params.message) 
          taskSpec:
            params:
            - name: message
            steps:
            - image: busybox:latest
              name: print-message
              script: |
                echo "Hello $(params.message)"
      params:
      - name: message
        value: $(tt.params.message)
```

Then, ran:

```
$ k port-forward svc/el-listener-triggerref 8080 &                                                    
$ curl http://localhost:8080 --data '{}' -H "X-GitHub-Event: pull_request"
```

This created a pipelinerun with the script: `echo "Hello This is the default message"`

Now, I updated the TriggerTemplate with the following script:

```yaml
....
              script: |
                echo "Hi there $(params.message)"
```

I ran the aforementioned curl multiple times over 5 minutes, but it never updated the task. Then, I deleted the eventlistener pod and it resolved the new task and printed the new message.
