### ISSUE TITLE
Params inside template

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/triggers#1045]
# Expected Behavior

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: task-deploy
  namespace: platform-pipelines
spec:
  params:
  - name: name
  - name: branch
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      annotations:
        janitor/ttl: 1h
      generateName: "deploy-$(params.name)-"
    ....
```
should work fine and create task runs "deploy-xxx-<hash>". And it works for example in tekton triggers v0.3.1.

# Actual Behavior

In v0.12.1 it comes into
```
{"level":"error","ts":"2021-04-12T14:15:32.710Z","logger":"eventlistener","caller":"sink/sink.go:239","msg":"couldn't create resource with group version kind \"tekton.dev/v1beta1, Resource=taskruns\": TaskRun.tekton.dev \"deploy-$(params.name)-qtxrh\" is invalid: [metadata.generateName: Invalid value: \"deploy-$(params.name)-\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: \"deploy-$(params.name)-qtxrh\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]","knative.dev/controller":"eventlistener","/triggers-eventid":"c546dccd-3b4b-46e1-8d3b-65ab...
```
