### ISSUE TITLE
EventListener using Knative Services should use /live for readiness probe

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/triggers#1069]
# Expected Behavior
The event listener pod should only receive traffic when it signaled readiness when using Knative Services.

# Actual Behavior
The event listener pod might receive traffic earlier because knative only waits for the tcp socket to be available and not if the HTTP response is 200.

When using a Knative Service based EventListener definition (e.g. https://github.com/tektoncd/triggers/blob/main/docs/eventlisteners.md#specifying-a-customresource-object) the generated Knative Service contains the following readinessProbe definition.

```yaml
readinessProbe:
  successThreshold: 1
  tcpSocket:
    port: 0
```

I think that this should be changed to the following to make sure that knative only forwards requests once the event listener is ready.

```yaml
readinessProbe:
  successThreshold: 1
  httpGet:
    path: /live
    scheme: HTTP
```

Explicitly setting/overwriting the readinessProbe is denied by the admission webhook:
`admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: must not set the field(s): spec.resources.customResource.spec.template.spec.containers[0].readinessProbe`

# Additional Info
- Tekton Triggers version: `0.13.0`

**Comment by savitaashture** [comment]
Hey @Fabian-K 
Actually Knative doesn't support ReadinessProbe with port https://github.com/knative/serving/blob/main/pkg/apis/serving/fieldmask.go#L344-L347
That is the reason we are not allowing users to set probes in eventlistener yaml 
as it will fail again in Knative

**Comment by Fabian-K** [comment]
Thanks for looking into this! I think the port can´t be specified because it will use the same port on which it forwards incoming requests. This should not be an issue, right? But IMO the readinessProbe should be defined otherwise knative might forward incoming requests before the el container is able to handle them.

**Comment by savitaashture** [comment]
> Thanks for looking into this! I think the port can´t be specified because it will use the same port on which it forwards incoming requests. This should not be an issue, right? But IMO the readinessProbe should be defined otherwise knative might forward incoming requests before the el container is able to handle them.

Hey @Fabian-K I just re checked the code and i see even if we set the probes Knative will override those as part of [rewriteUserProbe](https://github.com/knative/serving/blob/main/pkg/reconciler/revision/resources/deploy.go#L72-L83) and which is called while creating [container](https://github.com/knative/serving/blob/main/pkg/reconciler/revision/resources/deploy.go#L156) 

I assume the request won't forward untill all containers in the Pod is up (Both queue-proxy and eventlistener container) so that should not be an issue 

could you tell me the scenario which you are trying to test may be i can try from my end also

**Comment by Fabian-K** [comment]
Knative rewriting the probe through the queue container makes sense to me. In the end, both the queue container and the eventlistener container needs to be ready in order to receive traffic. 

Based on the wording "we route them through the queue container" i assume if a readinessProbe is defined, the queue container will include it when deciding if it can receive traffic or not. Probably they pass the information as an argument or environment variable to the queue container. I´ll check this tomorrow and come back to it!

**Comment by Fabian-K** [comment]
Hi @savitaashture! May I kindly ask if you agree that this change makes sense and it´s just a time/effort issue?

**Comment by Fabian-K** [comment]
Friendly ping on this :)

**Comment by dibyom** [comment]
I'll add it to the agenda for this week's WG :)

**Comment by savitaashture** [comment]
@Fabian-K sorry for the delay in response

Yes queue proxy uses `SERVING_READINESS_PROBE` https://github.com/knative/serving/blob/main/pkg/reconciler/revision/resources/queue.go#L354 and the value for the env coming from https://github.com/knative/serving/blob/main/pkg/reconciler/revision/resources/queue.go#L243-L246 which will override probe info given by the user

**Comment by Fabian-K** [comment]
Hi, thanks for picking this up. As I´m not sure if you agree that this change should be implemented here an example:

Without using knative, the following pod is executed to handle incoming events. It contains a readinesProbe such that it
will only receive events once it is fully initialized. (I´ve reduced the yamls to the relevant parts only)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: el-site-6546885b58-8ccvx
spec:
  containers:
    - name: event-listener
      readinessProbe:
        httpGet:
          path: /live
          port: 8000
          scheme: HTTP
```

When using customResource and knative, the pod definition changes to the following. Note that it does not consider /live, causing the event-listener container to receive traffic before being ready/fully initialized.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: el-site-00001-deployment-6466fd88f-vsccc
spec:
  containers:
    - name: event-listener
    - name: queue-proxy
      env:
        - name: SERVING_READINESS_PROBE
          value: '{"tcpSocket":{"port":8000,"host":"127.0.0.1"},"successThreshold":1}'
      readinessProbe:
        httpGet:
          httpHeaders:
            - name: K-Network-Probe
              value: queue
          path: /
          port: 8012
          scheme: HTTP
```

When however including the readinessProbe in the created Knative Service as mentioned, the pod changes to the following, allowing the event-listener to fully initialize before receiving traffic.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: el-site-desired-00001-deployment-574fd8784c-q76jl
spec:
  containers:
    - name: event-listener
    - name: queue-proxy
      env:
        - name: SERVING_READINESS_PROBE
          value: '{"httpGet":{"path":"/live","port":8000,"host":"127.0.0.1","scheme":"HTTP","httpHeaders":[{"name":"K-Kubelet-Probe","value":"queue"}]},"successThreshold":1}'
      readinessProbe:
        httpGet:
          httpHeaders:
            - name: K-Network-Probe
              value: queue
          path: /
          port: 8012
          scheme: HTTP
```

What do you think about this? Do you agree that the Knative Service object which is created by tekton triggers should contain the following defintion:
```yaml
readinessProbe:
  successThreshold: 1
  httpGet:
    path: /live
    scheme: HTTP
```

Thanks, Fabian

**Comment by savitaashture** [comment]
@Fabian-K agree we can provide 
```
readinessProbe:
  successThreshold: 1
  httpGet:
    path: /live
    scheme: HTTP
```
then it will be added to `SERVING_READINESS_PROBE` env of `queue-proxy` container

But we cannot provide port because of validation from Knative side and because of that `SERVING_READINESS_PROBE` will have default value `8080`

```
    - name: SERVING_READINESS_PROBE
      value: '{"httpGet":{"path":"/live","port":8080,"host":"127.0.0.1","scheme":"HTTP","httpHeaders":[{"name":"K-Kubelet-Probe","value":"queue"}]},"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":1}'
```

@dibyom Considering the scenario can we move back eventlistener containerPort to `8080` instead of `8000` changes introduced in this [PR](https://github.com/tektoncd/triggers/pull/887/files#diff-8ada42d708113fb9c530f8abd77cc57f79e505776e654da3751092509ad8eb20R58)
