### ISSUE TITLE
How to create an PR EventListener based on github labels

### ISSUE THREAD

**Issue by jinzishuai** [tektoncd/triggers#1121]
I've got something kind of working but not completely.
With
```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-ci-listener
  namespace: tekton-ci
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: github-pr-open-listener
      bindings:
        - ref: tekton-ci-pipelinebinding
      template:
        ref: tekton-ci-triggertemplate
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secret
            eventTypes: ["pull_request"]
        - cel:
            filter: >-
              (body.action in ['opened', 'synchronize', 'reopened', 'labeled']) && 
              (body.pull_request.labels[0].name == 'CI/CD-PR')
```
I can trigger a pipeline based on the label. However, I am not quite sure what syntax are allowed to require one of many PR labels to match the specific `CI/CD-PR` value.

The above code only works if there is exactly one label. It fails if there is no label or multiple labels.  

May I have some suggestions?
Thanks a lot.
