### ISSUE TITLE
Event ID character length causing pipelineruns to fail

### ISSUE THREAD

**Issue by boarder981** [tektoncd/triggers#1124]
I'm running Tekton on a Kubernetes 1.20 cluster.  Until now, I've been using Triggers v0.11.2.  Within my TriggerTemplates, I had been giving PipelineRuns a human-readable name for easy identification in the dashboard.  The format is [environment]-[appName]-[eventid].  The eventid in this case is a random 5-character string.  TriggerTemplate looks something like this:

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: start
spec:
  params:
    - name: environment
    - name: appName
    ...
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(tt.params.environment)-$(tt.params.appName)-$(uid) # uid here is the tekton unique RUN id
      spec:
        serviceAccountName: tekton
      ...
      ...
      ...
```

The [v0.12 release notes](https://github.com/tektoncd/triggers/releases/tag/v0.12.0) state that event IDs have been switched from a 5-character string to a UUID (which is 36 characters).  My EventListener is configured to trigger on git code push.  I upgraded Triggers on my test cluster to v0.12 and now my pipelineRuns fail to create because the name exceeds the 63-character limit.  Example log from the EventListener pod:

```
{"level":"info","ts":"2021-05-27T20:53:48.663Z","logger":"eventlistener","caller":"resources/create.go:103","msg":"For event ID \"359c33b0-4caf-453e-8864-77783d955e54\" creating resource tekton.dev/v1beta1, Resource=pipelineruns","knative.dev/controller":"eventlistener"}
{"level":"error","ts":"2021-05-27T20:53:48.820Z","logger":"eventlistener","caller":"sink/sink.go:339","msg":"problem creating obj: &errors.errorString{s:\"couldn't create resource with group version kind \\\"tekton.dev/v1beta1, Resource=pipelineruns\\\": admission webhook \\\"validation.webhook.pipeline.tekton.dev\\\" denied the request: validation failed: Invalid resource name: length must be no more than 63 characters: metadata.name\"}","knative.dev/controller":"eventlistener","/triggers-eventid":"359c33b0-4caf-453e-8864-77783d955e54","/trigger":"my-build-interceptor","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.CreateResources\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:339\ngithub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:238\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:127"}
```

Does anyone know if there is an easy way to truncate the Event ID within the TriggerTemplate?  It would be great if you could utilize CEL, similar to how you can in the EventListener.  It looks like [there was a similar request](https://github.com/tektoncd/triggers/issues/367) for this in the past, but it didn't go far.

Any advice would be greatly appreciated.  Let me know if more information is required.  Thank you!

**Comment by dibyom** [comment]
Hmm, one workaround I can think of is to use generateName instead of using $(uid) to add in the chars for unique id.
```
metadata:
  generateName: $(tt.params.environment)-$(tt.params.appName)-
```

**Comment by boarder981** [comment]
> Hmm, one workaround I can think of is to use generateName instead of using $(uid) to add in the chars for unique id.
> 
> ```
> metadata:
>   generateName: $(tt.params.environment)-$(tt.params.appName)-
> ```

Wow, I didn't even know generateName existed.  Great idea!  The only problem is that I need to set a param `pipelineRunUid` with the same value as the pipelineRun name, like so:

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: start
spec:
  params:
    - name: environment
    - name: appName
    - name: pipelineRunUid
    ...
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(tt.params.environment)-$(tt.params.appName)-$(uid) # uid here is the tekton unique RUN id
      spec:
        serviceAccountName: tekton
        params:
          - name: pipelineRunUid
            value: $(tt.params.environment)-$(tt.params.appName)-$(uid) # uid here is the tekton unique RUN id
        ...
        ...
        ...
```

I don't think there would be a way for me to set the value of `pipelineRunUid` to the pipelineRun name it generates.
