### ISSUE TITLE
InvalidImageName    

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/triggers#1126]
# Expected Behavior

# Actual Behavior
gh-validate-78974bfb6-w65h6                             0/1     Pending           0          1s
gh-validate-78974bfb6-w65h6                             0/1     Pending           0          1s
gh-validate-78974bfb6-w65h6                             0/1     ContainerCreating   0          1s
gh-validate-78974bfb6-w65h6                             0/1     InvalidImageName    0          5s
# Steps to Reproduce the Problem

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-validate
  namespace: tekton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-validate
  template:
    metadata:
      labels:
        app: gh-validate
    spec:
      serviceAccountName: default
      containers:
        - name: validate
          image: "ko://github.com/tektoncd/triggers/examples/event-interceptors"
          env:
            - name: GITHUB_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: secret-token
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
