### ISSUE TITLE
for: "serviceaccount-listener.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "serviceAccount"

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/triggers#1127]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      serviceAccount:
        name: tekton-triggers-example-sa
        namespace: tekton
      interceptors:
      - github:
          eventTypes: ["pull_request"]
      bindings:
        - ref: pipeline-binding
        - ref: message-binding
      template:
        ref: pipeline-template
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
