### ISSUE TITLE
EventListener: failed to write back sink response: http: Handler timeout

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/triggers#1131]
# Expected Behavior

EventListnere respond to github webhook reequest

# Actual Behavior

Unable to register github webhook, getting the following inside the `EventListener` logs

```
{"level":"error","ts":"2021-06-16T01:37:44.018Z","logger":"eventlistener","caller":"sink/sink.go:206","msg":"failed to write back sink response: http: Handler timeout","knative.dev/controller":"eventlistener","eventlistener":"build-pipeline-event-listener","namespace":"ci","eventlistenerUID":"e723888b-25d8-419a-bab8-fe92b8158f25","/triggers-eventid":"3516d51b-4f6b-4b4f-ab92-9feb8115d7a6","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:206\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2069\ngithub.com/tektoncd/triggers/pkg/sink.Sink.IsValidPayload.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/validate_payload.go:52\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2069\ngithub.com/tektoncd/triggers/pkg/sink.(*Sink).NewMetricsRecorderInterceptor.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/metrics.go:81\ngithub.com/tektoncd/triggers/pkg/sink.(*MetricsHandler).Intercept.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/metrics.go:153\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2069\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2448\nnet/http.(*timeoutHandler).ServeHTTP.func1\n\tnet/http/server.go:3316"}
```

# Steps to Reproduce the Problem

```
➜ ls -1       
README.md
kustomization.yaml
tekton-dashboard-v0.17.0.yaml
tekton-pipelines-v0.24.2.yaml
tekton-triggers-interceptors-v0.14.2.yaml
tekton-triggers-v0.14.2.yaml

✗  kgpon tekton-pipelines                             
NAME                                                READY   STATUS    RESTARTS   AGE
tekton-dashboard-74fd76dcb8-jdf2r                   1/1     Running   0          24m
tekton-pipelines-controller-79bcb4584d-x2p7l        1/1     Running   0          57m
tekton-pipelines-webhook-7c77dbf6fc-fbwwp           1/1     Running   0          57m
tekton-triggers-controller-6b59bb674-xvh2d          1/1     Running   0          56m
tekton-triggers-core-interceptors-b7d6c4d55-q92h8   1/1     Running   0          55m
tekton-triggers-webhook-86cc4647f6-66fgh            1/1     Running   0          56m

➜ kgpon ci              
NAME                                                READY   STATUS    RESTARTS   AGE
el-build-pipeline-event-listener-54c9cc6f78-mprdh   1/1     Running   0          14m
```

# Additional Info

- Kubernetes version:

```
➜ kubectl version                               
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
➜ tkn version                                                                 
Client version: 0.19.0
Pipeline version: v0.24.2
Triggers version: v0.14.2
Dashboard version: v0.17.0
```

- EventListener Manifest

```
# see more details about cel filtering
# https://bigkevmcd.github.io/kubernetes/tekton/pipeline/2020/02/05/cel-interception.html
# more on cel expressions is here: https://tekton.dev/docs/triggers/cel_expressions/

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-pipeline-event-listener
  namespace: ci
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceAccountName: vh-backend-staging-trigger-sa
  triggers:
  - name: backend-listener
    serviceAccountName: vh-backend-staging-trigger-sa
    interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: vh-backend-staging-webhook-secret
            secretKey: secret-token
        - name: "eventTypes"
          value: ["push"]
    - ref:
        name: "cel"
      params: 
        - name: "filter"
          value: body.ref == 'refs/heads/staging' &&
                 body.head_commit.author.name != "tekton-kustomize" &&
                 body.repository.name == "vh-backend"
        - name: "overlays"
          value:
          - key: truncated_sha
            expression: "body.head_commit.id.truncate(7)"
          - key: branch_name
            expression: "body.ref.split('/')[2]"
    bindings:
    - name: sha
      value: $(extensions.truncated_sha)
    - ref: vh-backend-staging-env
    - ref: github-trigger-binding
    template:
      ref: buildpack-build-pipeline-trigger-template
```

## CURL

```sh
➜ curl -X POST https://webhook.staging.domain.com/backend --header "Content-Type: application/json" --data '{"message":"Hello World"}'   
EventListener Timeout!

➜ k port-forward -n ci svc/el-build-pipeline-event-listener 8080:8080
Forwarding from 127.0.0.1:8080 -> 8000
Forwarding from [::1]:8080 -> 8000
Handling connection for 8080

➜ curl -X POST http://localhost:8080 --header "Content-Type: application/json" --data '{"message":"Hello World"}'  
EventListener Timeout!
```
