### ISSUE TITLE
error getting secret: context deadline exceeded

### ISSUE THREAD

**Issue by dmitry-mightydevops** [tektoncd/triggers#1135]
# Expected Behavior

After editing any task with `kubectl  edit task taskname` event listener should not wait N seconds to accept the incoming webhook.

# Actual Behavior

```bash
kubectl edit task kustomize
(send update to github repo, causing webhook to be triggered)

kubectl logs -n ci $(kgpo -l eventlistener=build-pipeline-event-listener -o name)  | sed --unbuffered \
    -e 's/\(.*creating resource.*\)/\o033[32m\1\o033[39m/' \
    -e 's/\(.*error.*\)/\o033[31m\1\o033[39m/' -e '/milo/!d'

{"level":"info","ts":"2021-06-21T22:17:28.862Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = error getting secret: Get \"https://172.20.0.1:443/api/v1/namespaces/ci/secrets/miloct-backend-dev-webhook-secret\": context deadline exceeded","knative.dev/controller":"eventlistener","/triggers-eventid":"5rpns","/trigger":"miloct-backend-dev-trigger","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

However if I wait a couple minutes and do another push, it works as expected. Not sure if it is a bug or "expected" behavior, but this is kind of strange.

# Additional Info

This is a portion of my eventlistener declaration

```
  - name: miloct-backend-dev-trigger
    interceptors:
    - github:
        secretRef:
          secretName: miloct-backend-dev-webhook-secret
          secretKey: secret-token
        eventTypes:
        - push
    - cel:
        filter: body.ref == 'refs/heads/develop' &&
                body.head_commit.author.name != "tekton-kustomize" &&
                body.repository.name == "miloct-backend"
        overlays:
        - key: truncated_sha
          expression: "body.head_commit.id.truncate(7)"
```

- Kubernetes version:

```bash
✗  k version                 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:

```bash
➜ tkn version                                                                     
Client version: 0.18.0
Pipeline version: v0.20.1
Triggers version: v0.11.2
Dashboard version: v0.14.0
```
