### ISSUE TITLE
Exclude some labels by mask from deployment of EventListener

### ISSUE THREAD

**Issue by aivanov-citc** [tektoncd/triggers#1147]
Good day!
We use the "flux" gitops system for deployment in kubernetes. With this deployment, flux enriches all its monitored resources with kustomize.toolkit.fluxcd.io labels.
```yaml
kind: EventListener
apiVersion: triggers.tekton.dev/v1alpha1
metadata:
  name: kogito-wrap-event-listener
  labels:
    kustomize.toolkit.fluxcd.io/checksum: 44a073ce43daaea8f39d21f0c6410325c198c2b5
    kustomize.toolkit.fluxcd.io/name: workloads-sync
    kustomize.toolkit.fluxcd.io/namespace: flux-system

kind: Deployment
apiVersion: apps/v1
metadata:
  name: el-kogito-wrap-event-listener
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: kogito-wrap-event-listener
    kustomize.toolkit.fluxcd.io/checksum: 44a073ce43daaea8f39d21f0c6410325c198c2b5
    kustomize.toolkit.fluxcd.io/name: workloads-sync
    kustomize.toolkit.fluxcd.io/namespace: flux-system
```
If it is possible to exclude the inheritance of some labels from resources when processed by the controller? Remove by mask flux labels
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: el-kogito-wrap-event-listener
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: kogito-wrap-event-listener
    # Remove flux labels
    #kustomize.toolkit.fluxcd.io/checksum: 44a073ce43daaea8f39d21f0c6410325c198c2b5
    #kustomize.toolkit.fluxcd.io/name: workloads-sync
    #kustomize.toolkit.fluxcd.io/namespace: flux-system
```
for example, in strimzikafkaoperator this is implemented through an environment variable
```
- name: STRIMZI_LABELS_EXCLUSION_PATTERN
  value: "^kustomize.toolkit.fluxcd.*"
```
