### ISSUE TITLE
emptyDir workspace not properly set in pipeline run created from trigger template

### ISSUE THREAD

**Issue by hokadiri** [tektoncd/triggers#1174]
# Expected Behavior
Setting default `emptyDir: {}` as a workspace of a pipeline run in a trigger template should properly setup the emptyDir workspace.

https://tekton.dev/docs/pipelines/workspaces/#emptydir

# Actual Behavior
Trigger template fails to create the pipelinerun resource
 

# Steps to Reproduce the Problem
Setup a trigger template with an emptyDir workspace in a pipelinerun
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: some-trigger-template
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    spec:
      pipelineRef:
        name: some-pipeline
      workspaces:
        - name: ws
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        - name: secret-data
          secret:
            defaultMode: 420
            secretName: var-lib-tss
        - name: gradle-tmp
          emptyDir: {}
```

Trigger template fails to create pipelinerun with below error
```
{
  "level": "error",
  "ts": "2021-08-04T14:39:39.475Z",
  "logger": "eventlistener",
  "caller": "sink/sink.go:278",
  "msg": "couldn't create resource with group version kind \"tekton.dev/v1beta1, Resource=pipelineruns\": admission webhook \"validation.webhook.pipeline.tekton.dev\" denied the request: validation failed: expected exactly one, got neither: spec.workspaces[2].configmap, spec.workspaces[2].emptydir, spec.workspaces[2].persistentvolumeclaim, spec.workspaces[2].secret, spec.workspaces[2].volumeclaimtemplate",
  "knative.dev/controller": "eventlistener",
  "eventlistener": "commit-verify-listener",
  "namespace": "android",
  "eventlistenerUID": "df681322-0b4d-4e0f-8015-9e24bec443db",
  "/triggers-eventid": "1734f5e9-ce7e-4a98-b25f-1d629f4657b4",
  "/trigger": "commit-verify-trigger",
  "stacktrace": "github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:278\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func4\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:164"
}
```

Error seems to be because `emptyDir` missing from trigger-template pipelinerun config
```
$ kubectl get tt some-template -o yaml | tail
...
      workspaces:
      - name: ws
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      - name: secret-data
        secret:
          defaultMode: 420
          secretName: var-lib-tss
      - name: gradle-tmp
```

But when i update the `emptyDir` by explicitly setting the  **default** `medium: Memory`
```
        - name: gradle-tmp
          emptyDir:
            medium: Memory
```

It works
```
$ kubectl get tt some-trigger-template -o yaml | tail
            resources:
              requests:
                storage: 20Gi
      - name: secret-data
        secret:
          defaultMode: 420
          secretName: var-lib-tss
      - emptyDir:
          medium: Memory
        name: gradle-tmp
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.900", GitCommit:"28ab8501be88ea42e897ca8514d7cd0b436253d9", GitTreeState:"clean", BuildDate:"2021-06-30T09:23:36Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
$ tkn version
Client version: 0.17.1
Pipeline version: v0.24.1
Triggers version: v0.14.0
Dashboard version: v0.17.0
```
