### ISSUE TITLE
Too much memory used with large number of namespaces

### ISSUE THREAD

**Issue by guillaumerose** [tektoncd/triggers#1268]
# Expected Behavior

Same memory usage as the pipeline controller

# Actual Behavior

The memory taken by the interceptor and trigger controller is around 1GB.

This is not the case of the pipeline controller which stay around 50MB.

<img width="1468" alt="Screenshot 2021-11-24 at 15 30 56" src="https://user-images.githubusercontent.com/172624/143257378-c21e36ae-6f86-42a5-9e69-000f8c09c6b2.png">

(memory usage of pods in Tekton namespace during the load test - highest are tekton-triggers-controller and tekton-triggers-core-interceptors pods)

# Steps to Reproduce the Problem

1. Create 2000 namespaces. In the first 600, create a PipelineRun like this:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline1
spec:
  pipelineSpec:
    tasks:
      - name: step1
        taskSpec:
          steps:
          - name: step1
            image: busybox
            imagePullPolicy: IfNotPresent
            script: ls /
```
2. Observe the memory taken by the 2 controllers

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1+d8c4430", GitCommit:"2ade4d46986c94405aa0542f8d6ff7691bddb153", GitTreeState:"clean", BuildDate:"2021-11-02T02:02:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton Pipeline version:

pipeline: v0.28.2
triggers: v0.16.1 

- Other additional information 

It is stable: if I kill the pod, the controller is recreated and takes almost the same amount of memory.

The cluster has 681 deployments and 14180 configMaps.

I turned on profiling and saw there is something happening in the informers.

<img width="1390" alt="Screenshot 2021-11-24 at 15 31 32" src="https://user-images.githubusercontent.com/172624/143257354-5728f9db-3e1a-4106-adb0-b17b4f9d13c1.png">
