### ISSUE TITLE
v1alpha1 interceptor examples have v1beta1 definitions

### ISSUE THREAD

**Issue by protosam** [tektoncd/triggers#1324]
All of the `v1alpha1` examples with interceptor examples seem to be invalid. They all have `v1beta1` structures and will be rejected by the triggers webhook. 

The  triggers from the github example [here](https://github.com/tektoncd/triggers/blob/main/examples/v1alpha1/github/github-eventlistener-interceptor.yaml#L7-L28)  look like this.
```yaml
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-template
```

They should look like this.
```yaml
triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes: ["pull_request"]
        - cel:
            filter: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-template
```
