### ISSUE TITLE
I can't use CEL interceptor "cel not found"

### ISSUE THREAD

**Issue by rong280** [tektoncd/triggers#1338]
Info:
- Kubernetes version: v1.22
- kubelet version: v1.23
- Tekton Pipeline version: v0.34.1
- eventlistenersink:v0.19.1 (container image version)

configuration
```yaml
triggers:
    - name: cel-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
          - name: "filter"
            value: "header.match('X-Codeup-Event', 'Tag Push Hook')"
```

Eventlistener error log:
  ```
{"level":"error","ts":"2022-04-03T14:51:10.617Z","logger":"eventlistener","caller":"sink/sink.go:381","msg":"could not resolve interceptor URL: url resolution failed for interceptor cel with: clusterinterceptors.triggers.tekton.dev \"cel\" not found","eventlistener":"ptfss-codeup","namespace":"pipelines","/triggers-eventid":"a0c35be1-a905-47cd-a658-1f46e420e525","eventlistenerUID":"2dbbc6d0-c476-471a-bf61-7811a072685a","/triggers-eventid":"a0c35be1-a905-47cd-a658-1f46e420e525","/trigger":"cel-trigger","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:381\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:196"}
  ```

Everything works fine when I don't use the interceptor, please help

Thanks !
