### ISSUE TITLE
Wildcard match can't be used in EventListener's namespaceselector

### ISSUE THREAD

**Issue by gaodan-fang** [tektoncd/triggers#1341]
# Expected Behavior
EventListener should be applied successfully

# Actual Behavior
```
error: error parsing el.yaml: error converting YAML to JSON: yaml: line 8: did not find expected alphabetic or numeric character
```

# Steps to Reproduce the Problem
```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: mlmodel-eventlistener
spec:
  namespaceSelector:
    matchNames:
      - *
  serviceAccountName: pipeline
```
Trying to apply the above eventlistener to the cluster and got the yaml error

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v4.2.0-alpha.0-657-g51011e4
  Server Version: 4.8.31
  Kubernetes Version: v1.21.6+b82a451
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
  ```
  Client version: 0.15.0
  Pipeline version: v0.33.2
  Triggers version: v0.19.0
  ```

- Proposed fix, update the [documentation](https://github.com/tektoncd/triggers/blob/v0.19.0/docs/eventlisteners.md#constraining-eventlisteners-to-specific-namespaces) with 
  ```
  namespaceSelector:
    matchNames:
      - "*"
  ```
