### ISSUE TITLE
FR: Add common trigger bindings in TriggerGroups

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1388]
### Feature request

Currently, TriggerGroups allows users to group triggers that share a common set of interceptors. It may also be useful for some of these groups to share some common bindings across the triggers as well.

### Use case

1. Remove repetitive copying of the same bindings between triggers that are part of the same triggerGroup

Example of what this could look like:
```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener
spec:
  triggerGroups:
  - name: github-pr-group
    interceptors:
    - name: "validate GitHub payload and filter on eventType"
      ref:
        name: "github"
      params:
      - name: "secretRef"
        value:
          secretName: github-secret
          secretKey: secretToken
      - name: "eventTypes"
        value: ["pull_request"]
    bindings: # NEW FIELD
    - name: pr_nunber
      value: $(body.number)
    - name: pr_sha
      value: $(body.pull_request.head.sha)
    triggerSelector:
      labelSelector:
        matchLabels:
          type: github-pr
```
