### ISSUE TITLE
More than one EventListeners Instances Not Created on OKD

### ISSUE THREAD

**Issue by RAZA-ABBBASI** [tektoncd/triggers#1459]
I have 3 different services to be deployed on OKD 10 from three different repositories. I want to create separate event listener for each service. Eventlistener for the first service is successfully created; including the deployment, pod and service but not for the other two services, I am using same eventlistener yaml, the only difference is the name of the service and the triggerReference. 
The status for the first first service is Available: True, Ready: True 
The status for the rest of the service is Available: , Ready: 

EventListener version:  version: v0.16.1
Pipeline version: version: v0.28.3

```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: el-name
  namespace: my-namespace
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: triggername
```

Is there any restriction on number of EL Instance in a single namespace?
