### ISSUE TITLE
couldn't create resource with group version kind tekton.dev/v1beta1

### ISSUE THREAD

**Issue by gujiwork** [tektoncd/triggers#1464]
# Expected Behavior
  curl http://xxxx:8080 -d '{}'

# Actual Behavior

# Steps to Reproduce the Problem

1.
```
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-pipeline-template
spec:
  params:
  - name: revision
  - name: url

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: clone-read-run
      generateName: clone-read-run-
    spec:
      serviceAccountName: hello-gitlab-service-account
      pipelineRef:
        name: hello-flow
      status: PipelineRunPending
      podTemplate:
        securityContext:
          runAsUser: 0
          fsGroup: 65532

      workspaces:
      - name: shared-data
        persistentVolumeClaim:
          claimName: tekton-test

      - name: git-credentials
        secret:
          secretName: hello-gitlab
      params:
      - name: repo-url
        value: ${tt.params.url}
      - name: revision
        value: ${tt.params.revision}

      - name: testok
        value: "22"



---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: revision
      value: $(body.git.branch)
    - name: url
      value: $(body.git.url)


```
2.
```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: github-listener
      bindings:
        - ref: github-pr-binding
      template:
        ref: trigger-pipeline-template
```
3.
```
curl -H "Content-Type:application/json"  http://localhost:8090 -d '{"git": {"url": "https://github.com/xxxxxxx.git", "branch": "master"}}'
```
# Additional Info
```
{
	"severity": "error",
	"timestamp": "2022-10-14T07:43:22.313Z",
	"logger": "eventlistener",
	"caller": "sink/sink.go:524",
	"message": "problem creating obj: &errors.errorString{s:\"couldn't create resource with group version kind \\\"tekton.dev/v1beta1, Resource=pipelineruns\\\": The POST operation against PipelineRun.tekton.dev could not be completed at this time, please try again.\"}",
	"eventlistener": "github-listener",
	"namespace": "default",
	"/triggers-eventid": "a5dda8b7-ac33-41ea-9b2d-e99173417502",
	"eventlistenerUID": "7f57145b-005e-41f9-9d30-aca2de9652a9",
	"/triggers-eventid": "a5dda8b7-ac33-41ea-9b2d-e99173417502",
	"/trigger": "github-listener"
} {
	"severity": "error",
	"timestamp": "2022-10-14T07:43:22.313Z",
	"logger": "eventlistener",
	"caller": "sink/sink.go:413",
	"message": "couldn't create resource with group version kind \"tekton.dev/v1beta1, Resource=pipelineruns\": The POST operation against PipelineRun.tekton.dev could not be completed at this time, please try again.",
	"eventlistener": "github-listener",
	"namespace": "default",
	"/triggers-eventid": "a5dda8b7-ac33-41ea-9b2d-e99173417502",
	"eventlistenerUID": "7f57145b-005e-41f9-9d30-aca2de9652a9",
	"/triggers-eventid": "a5dda8b7-ac33-41ea-9b2d-e99173417502",
	"/trigger": "github-listener"
}
```
- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-aliyun.1", GitCommit:"937757761d3c1db7080f179102b437c26c521ecd", GitTreeState:"clean", BuildDate:"2022-05-26T12:38:52Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

Client version: 0.27.0
Pipeline version: v0.40.0
Triggers version: v0.21.0
Dashboard version: v0.29.2
