### ISSUE TITLE
Don't return HTTP 202 if a global interceptor fails

### ISSUE THREAD

**Issue by Brutus5000** [tektoncd/triggers#1465]
# Expected Behavior

If a global interceptor fails to process (e.g. `interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = event type  is not allowed`), the event listener http response should return status code 400 Bad Request. This indicates the user, that something was wrong with his payload and (even more important) that the pipeline did not run at all.

Also some artifact or at least log event with level warn/error should be created indicating that something happened

# Actual Behavior

* Event listener return status code 202 Accepted even if an interceptor fails.
* The listener pod just logs the error on info level.
* No pipeline run artifact or anything is created.

# Steps to Reproduce the Problem

1. Deploy & create an event listener with an interceptor similar to 
```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-gitlab-webhook
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: gitlab-push-events-trigger
      interceptors:
        - name: "verify-gitlab-payload"
          ref:
            name: "gitlab"
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: "gitlab-secret"
                secretKey: "secretToken"
            - name: eventTypes
              value:
                - "Push Hook"
```
2. Send an empty json object payload to the event listener, e.g. `curl -v -H 'content-Type: application/json' -d '{}' http://localhost:8080`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4+k3s1", GitCommit:"43b1cb48200d8f6af85c16ed944d68fcc96b6506", GitTreeState:"clean", BuildDate:"1970-01-01T01:01:01Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
Client version: 0.23.1
Pipeline version: v0.40.2
Triggers version: v0.21.0
Dashboard version: v0.29.2
```
