### ISSUE TITLE
Cannot create getting-started event listener pod

### ISSUE THREAD

**Issue by simonlaw0711** [tektoncd/triggers#1471]
# Expected Behavior
Could be able to run the event listner pod

# Actual Behavior
Ran into a error:
```
{"severity":"info","timestamp":"2022-10-27T10:36:53.888Z","caller":"logging/config.go:80","message":"Unable to read vcs.revision from binary"}
{"severity":"fatal","timestamp":"2022-10-27T10:36:53.897Z","logger":"eventlistener","caller":"v2/main.go:205","message":"Start returned an error","error":"Timed out waiting on CaBundle to available for clusterInterceptor: Timed out waiting on CaBundle to available for clusterInterceptor: empty caBundle in clusterInterceptor spec"}
```

# Steps to Reproduce the Problem

1. Follow the instruction on [here](https://github.com/tektoncd/triggers/tree/v0.8.1/docs/getting-started) to run `kubectl -n getting-started apply -f ./docs/getting-started/triggers.yaml`

My yaml file:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: getting-started-triggertemplate
  namespace: getting-started
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: getting-started-pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: getting-started-pipeline
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(tt.params.gitrevision)
              - name: url
                value: $(tt.params.gitrepositoryurl)
          - name: image-source
            resourceSpec:
              type: image
              params:
                - name: url
                  value: https://hub.docker.com/repository/docker/simon0711/my-app # docker-repo-location.com/repo:getting-started
          - name: event-to-sink
            resourceSpec:
              type: cloudEvent
              params:
                - name: targetURI
                  value: http://event-display.getting-started.svc.cluster.local
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: getting-started-pipelinebinding
  namespace: getting-started
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: getting-started
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: getting-started-listener
  namespace: getting-started
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - bindings:
      - ref: getting-started-pipelinebinding
      template:
        ref: getting-started-triggertemplate

```
# Additional Info

- Kubernetes version: 1.22.12-gke.2300	

  **Output of `kubectl version`:**
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12-gke.2300", GitCommit:"e55564cf3a1384026a54920174977659c8c56a50", GitTreeState:"clean", BuildDate:"2022-08-16T09:24:51Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version: v0.29.0
