### ISSUE TITLE
Dynamic triggering of triggerGroups

### ISSUE THREAD

**Issue by ronnberg** [tektoncd/triggers#1474]
### Feature request

I would like to have the possibility to use interceptor variabels when matching triggers with matchLabels. This would mean that you could define a single eventlistener for multiple repositories and activate specific triggers where labels match something in the payload. Since eventlistener has a long running pod it make sense to me to not have one eventlistener per repository. I know that it is possible to let the eventlistener trigger multipele triggers and let the triggers (via interceptor) filter out if they should continue or not.  With many repositories wired to one eventlistener this would create a spike for every event. Being able to use variables on matchLabels would save resources in the cluster by having fewer eventlisteners and only activate the triggers that should actually run.

### Use case
For our company this would be a great feature. We have a microservice architecture with many repositories. Every opening to the outside world comes with a lot of extra work (approval, firewalls etc.) so to have a singe eventlistener for multiple repositories is a must. 

Example:
```
spec:
  triggerGroups:
  - interceptors:
    - name: get-repository-name
      params:
      - name: overlays
        value:
        - expression: body.repository.name
          key: repo_name
      ref:
        kind: ClusterInterceptor
        name: cel
    triggerSelector:
      labelSelector:
        matchLabels:
          reponame: $(extensions.repo_name)

```
