### ISSUE TITLE
Unable to define Webhook interceptor according to the latest schema

### ISSUE THREAD

**Issue by ezh** [tektoncd/triggers#1485]
# Expected Behavior

Webhook is using `objectRef`

# Actual Behavior

`objectRef` is ignored

# Steps to Reproduce the Problem

There is a schema with interceptor definition https://github.com/tektoncd/triggers/blob/main/docs/interceptors.md#specifying-an-interceptor

```
    - ref:
        name: webhook
      params:
...
```

but the example in the document contains legacy behavior

```
    - webhook:
        objectRef:
          kind: Service
...
```

I tried multiple variants:

```
    - ref:
        name: webhook
...
```
without params. It works. There is no error but https://github.com/tektoncd/triggers/blob/main/pkg/apis/triggers/v1beta1/trigger_validation.go#L104

```
    - ref:
        name: webhook
      params:
        - name: "objectRef"
          value:
            - kind: Service
...
```

```
    - ref:
        name: webhook
      params:
        - name: "objectRef"
          value:
            kind: Service
...
```

There are no complaints from admission webhook "webhook.triggers.tekton.dev". All the above definitions are correct from the validator's POV.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}  ```
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
tkn version
Client version: 0.27.0
Pipeline version: v0.41.0
Triggers version: v0.21.0
Dashboard version: v0.30.0
```

I tried to search for more information across the code and read a bit of golang without luck.
