### ISSUE TITLE
Configurable label propagation for EventListener Pods

### ISSUE THREAD

**Issue by muxmuse** [tektoncd/triggers#1489]
### Feature request

EventListeners propagate their labels to Deployments and additionally to the (Pod) Template of the Deployment. This should be configurable, e.g. with the PodTemplate field of the EventListener. It should be possible to provide an empty value for a label such that a specific label is not propagated.

### Use case

Label based garbage collection in a git-ops setup.

**Comment by savitaashture** [comment]
Hi @muxmuse 

I have spent sometime to understand the feature request and based on my understanding tried below steps to see the current behavior 

**Steps:**

1. Below is the sample EL yaml by providing some labels at el metadata

```
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  labels:
    "hello": "hi"
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-example-sa
            ...
```
The created pod looks like below
```
kubectl get pod el-github-listener-74f457bcd-57kpb -o yaml
apiVersion: v1
kind: Pod
metadata:
   generateName: el-github-listener-74f457bcd-
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-listener
    hello: hi
    pod-template-hash: 74f457bcd
  name: el-github-listener-74f457bcd-57kpb
  namespace: default
```

2. Below is the sample yaml by providing empty values to  label using PodTemplate field of the EventListener

```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  labels:
    "hello": "hi"
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-template
  resources:
    kubernetesResource:
      spec:
        template:
          metadata:
            labels:
              "hello": ""
          spec:
              ....
```

The created pod looks like below
```
kubectl get pod el-github-listener-74f457bcd-57kpb -o yaml
apiVersion: v1
kind: Pod
metadata:
   generateName: el-github-listener-74f457bcd-
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-listener
    hello: ""
    pod-template-hash: 74f457bcd
  name: el-github-listener-74f457bcd-57kpb
  namespace: default
```

**Comment by savitaashture** [comment]
So basically what i want to say is that is that something you are looking

If not

Could you specify the UX of the expectation

**Comment by muxmuse** [comment]
Thank you very much for taking the time. The described approach changes the contents of the pod's label as I need it, but the deployment's label remains unchanged.

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: el-github-eventlistener
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-eventlistener
    hello: hi
```

Based on the current design of the resources field, the expected UX behavior would be that the deployment's labels are configurable, too. Based on the current design, I am not sure where I would expect it, as `kubernetesResource.spec` is reserved for the pod template.

``` yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-eventlistener
  labels:
    hello: hi
spec:
  ...
  resources:
    kubernetesResource:
      deploymentSpec: // ? doesn't seem right here
         metadata:
           labels: 
             hello: ""
```

Not taking the current design into account, I would expect that labels are only propagated if specified explicitly, i.e. without a resources field, there are no labels propagated at all.
