### ISSUE TITLE
event listener error unsupported protocol scheme

### ISSUE THREAD

**Issue by github4sanjay** [tektoncd/triggers#1492]
# Expected Behavior
Event listener should work with github webhook.
# Actual Behavior

```
{"severity":"error","timestamp":"2022-12-13T10:31:20.746Z","logger":"eventlistener","caller":"sink/sink.go:412","message":"Post \"\": unsupported protocol scheme \"\"","eventlistener":"github-token","namespace":"tekton-pipelines","/triggers-eventid":"b2b5820d-c466-42bb-83f2-69a3a1572f8a","eventlistenerUID":"7eef4c33-d2c9-4d2b-b528-826112b81596","/triggers-eventid":"b2b5820d-c466-42bb-83f2-69a3a1572f8a","/trigger":"springboot"}
```

# Steps to Reproduce the Problem

1. When github event is received by el it gives error unsupported protocol scheme

# Additional Info

- Kubernetes version: 1.24

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
Client version: 0.28.0
Pipeline version: v0.42.0
Triggers version: v0.22.0
Dashboard version: v0.30.0

**Comment by dibyom** [comment]
> unsupported protocol scheme

When you are configuring the eventlistener url your webhook in GitHub, please make sure you are including the protocol (https or http)

**Comment by savitaashture** [comment]
Could you also provide logs of Eventlistener pod and Interceptor pod

**Comment by github4sanjay** [comment]
Logs from event listener:

```
{"severity":"error","timestamp":"2022-12-13T10:31:20.746Z","logger":"eventlistener","caller":"sink/sink.go:412","message":"Post \"\": unsupported protocol scheme \"\"","eventlistener":"github-token","namespace":"tekton-pipelines","/triggers-eventid":"b2b5820d-c466-42bb-83f2-69a3a1572f8a","eventlistenerUID":"7eef4c33-d2c9-4d2b-b528-826112b81596","/triggers-eventid":"b2b5820d-c466-42bb-83f2-69a3a1572f8a","/trigger":"springboot"}

```
Logs from interceptor

```
{"level":"info","ts":1671064818.8078034,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
{"level":"info","ts":1671064818.9848797,"caller":"interceptors/main.go:178","msg":"Listen and serve on port 8443"}
```
`

Steps to reproduce:
1. Kubernetes version 1.24
2. kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.22.0/release.yaml
    kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.22.0/interceptors.yaml
3. Create an el

```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-token
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-ci-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: [ "push" ]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.repository.name in ['springboot-template'] && body.ref == 'refs/heads/master'"
      bindings:
        - ref: pipelinebinding
      template:
        ref: springboot-java17-triggertemplate

```

4. Instanciate webhook through github events

**Comment by abayer** [comment]
We're seeing this on plumbing too:
```
{"severity":"error","timestamp":"2022-12-20T12:50:32.302Z","logger":"eventlistener","caller":"sink/sink.go:320","message":"Post \"\": unsupported protocol scheme \"\"","eventlistener":"tekton-events","namespace":"default","/triggers-eventid":"7b12fc21-7d0b-4f86-ad11-f33a03b87231","eventlistenerUID":"b37832bb-3e30-4516-9b04-c41d626e9321","/triggers-eventid":"7b12fc21-7d0b-4f86-ad11-f33a03b87231","/triggergroup":"ci-job-triggers"}
```

**Comment by brunocascio** [comment]
I'm running tekton for a PoC using the operator, and after cleanup and re-install everything it started failing using with this issue.

```yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  targetNamespace: tekton-pipelines
  dashboard:
    readonly: false
  pipeline:
    # alpha is required for use new features like:
    #   - https://tekton.dev/docs/pipelines/pipelineruns/#propagated-workspaces
    enable-api-fields: alpha 
  pruner:
    resources:
    - pipelinerun
    - taskrun
    keep: 3
    schedule: "* * * * *"
```

**Comment by brovoca** [comment]
I seem to have encountered a similar issue when I switched to triggerGroups. I see the following in the EL log:

>`{"severity":"error","timestamp":"2023-02-10T12:13:24.702Z","logger":"eventlistener","caller":"sink/sink.go:320","message":"Post \"\": unsupported protocol scheme \"\"","eventlistener":"gerrit-ref-updated","namespace":"tekton-neo","/triggers-eventid":"34678b4a-3454-49d9-80fa-5373231b8d6e","eventlistenerUID":"5bfd7114-1c77-4265-b055-887158692ee4","/triggers-eventid":"34678b4a-3454-49d9-80fa-5373231b8d6e","/triggergroup":"tekton-filter-group"}`

This is what I had which worked:
```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gerrit-ref-updated
spec:
  serviceAccountName: tekton-triggers-gerrit-sa
  triggers:
    - name: gerrit-push-events-trigger
      interceptors:
        - name: "Only process refs/heads/*"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.refUpdate.refName.startsWith('refs/heads/')"
      bindings:
        - ref: gerrit-ref-updated
      template:
        spec:
          params:
            - name: project
            - name: ref_name
            - name: old_rev
            - name: new_rev
            - name: origin_url
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: TaskRun
              metadata:
                generateName: gerrit-ref-updated-
              spec:
                taskSpec:
                  steps:
                    - image: ubuntu
                      script: |
                        #! /bin/bash
                        cat << EOF
                        project: $(tt.params.project)
                        ref_name: $(tt.params.ref_name)
                        old_rev: $(tt.params.old_rev)
                        new_rev: $(tt.params.new_rev)
                        origin_url: $(tt.params.origin_url)
                        EOF
```

I then switched to this which broke:

```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gerrit-ref-updated
spec:
  serviceAccountName: tekton-triggers-gerrit-sa
  triggerGroups:
  - name: tekton-filter-group
    interceptors:
  - name: "Only process refs/heads/*"
    ref:
      name: "cel"
    params:
    - name: "filter"
      value: "body.refUpdate.refName.startsWith('refs/heads/')"
    triggerSelector:
      labelSelector:
        matchLabels:
          projectType: bogus
```

I'm on Kubernetes 1.26.4 and [Tekton operator v0.64.0](https://github.com/tektoncd/operator/releases/tag/v0.64.0)

**Comment by khrm** [comment]
Is this happening with the latest triggers version? @brovoca 

This pr should have resolved this issue: https://github.com/tektoncd/triggers/issues/1499

**Comment by brovoca** [comment]
@khrm I am unable to check as I'm relying on the version published by the operator, which uses triggers v0.22.0.

**Comment by khrm** [comment]
/assign khrm
I will look into the operator.

**Comment by pbaity** [comment]
I'm seeing the same error when using `triggerGroups` on OpenShift 4.11 (Kubernetes 1.24.6), using Tekton via the Red Hat OpenShift Pipelines operator (which provides Triggers v0.22.0).

If anyone else is hitting this issue, a workaround that fixed it for me was simply to provide the `kind` in the interceptors. So instead of this:

```yaml
  triggerGroups:
    - name: app-engine-triggers
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
```

Include `kind: ClusterInterceptor` in the `ref`:

```yaml
...
  triggerGroups:
    - name: app-engine-triggers
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor    # <--- add this
          params:
            - name: "secretRef"
```

It may already be fixed in the most recent version of Triggers, or will be shortly, but this workaround shouldn't later cause problems if you apply it. :crossed_fingers:
