### ISSUE TITLE
Remote resolution for Triggers

### ISSUE THREAD

**Issue by pbaity** [tektoncd/triggers#1539]
### Feature request

> Remote Resolution is a Tekton [Pipelines] feature that allows users to fetch tasks and pipelines from remote sources outside the cluster.<sup>[[1]](https://tekton.dev/docs/pipelines/resolution/)</sup>

It would be great if we could use resolvers in event listeners and triggers too, so that we could fetch triggers, trigger bindings, and trigger templates from remote sources outside the cluster.

Event listeners that use `triggerGroups` can already select triggers in other namespaces with `triggerSelector`, in much the same way pipeline and task runs can use pipeline and task definitions in another namespace with the [cluster resolver](https://tekton.dev/docs/pipelines/cluster-resolver/). It would be great if this was more flexible so you could remotely resolve trigger definitions from other sources too. Maybe something like this:

```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sample-el
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: trigger/simple/0.1/simple.yaml
```

Similarly, triggers could reference trigger bindings and templates from remote sources, which - to my knowledge - they can't do even across namespaces in the cluster at this time.

```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: sample-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref:
        resolver: cluster
        params:
          - name: kind
            value: triggerbinding
          - name: name
            value: sample-triggerbinding
          - name: namespace
            value: triggers-library-ns
  template:
    ref:
      resolver: bundles
      params:
        - name: bundle
          value: docker.io/myrepo/example@sha256:053a6c...
        - name: name
          value: sample-triggertemplate
        - name: kind
          value: triggertemplate
```

### Use case

Overall, I think this feature would be a natural next step for resolvers. They were made for exactly this purpose.

But for specific use cases, allow me to riff on [TEP-0060's use cases](https://github.com/tektoncd/community/blob/main/teps/0060-remote-resource-resolution.md#use-cases-optional):

**Sharing a git repo of triggers:** An organization decides to manage their internal triggers, trigger templates, and trigger bindings in a shared git repository. The CI/CD cluster is set up to allow these resources to be referenced directly by EventListeners and Triggers in the cluster.

**Using non-git VCS for pipelines-as-code:** A game dev keeps all of their Triggers, TriggerTemplates, and TriggerBindings, config-as-code style, in a Perforce repo alongside the assets and source that make up their product. Triggers does not provide support for resolving Tekton resources from Perforce repositories out-of-the-box. The dev creates a new Resolver by following a template and docs published as part of the Tekton Pipelines project. The dev's Resolver is able to fetch Tekton resources from their Perforce repo and return them to the Triggers reconciler.

**Platform interoperability:** A platform builder accepts workflows imported from other Tekton-compliant platforms. When a Trigger is imported that includes a reference to a TriggerTemplate or TriggerBinding in a Remote that the platform doesn't already have it goes out and fetches that TriggerTemplate or TriggerBinding, importing it alongside the pipeline without the user having to explicitly provide it.

**Providing an audited catalog of tasks and pipelines:** A company requires their CI/CD Triggers, TriggerBindings, and TriggerTemplates to be audited to check that they adhere to specific compliance rules before they can be used in their app teams' Pipelines. The company hosts a private internal catalog and requires all the app teams to build their EventListeners and Triggers using only that catalog. To make this easier all of the CI/CD clusters in the company are configured with a single remote resource resolver - a CatalogRef resolver - that points to the internal catalog.
