### ISSUE TITLE
Allow GitHub interceptor to reference secrets in other namespaces

### ISSUE THREAD

**Issue by pbaity** [tektoncd/triggers#1555]
### Feature request

I found a couple of issues that seemed tangential to this, but not that stated it explicitly - apologies if I've missed one.

The GitHub interceptor (and other interceptors that use the secret getter) only retrieve secrets from the same namespace as the trigger (I think I'm reading that Go right). But the getter already has a parameter for the namespace - can we expose that parameter to the interceptor, so you could have a single EventListener that's able to get secrets from other namespaces in its GitHub interceptor (and other interceptors, I suppose)? 

Like so:

```yaml
 triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "secretRef"
            value:
              secretName: github-secret
              secretKey: secretToken
              secretNamespace: my-namespace        # this is the only new line
```

### Use case

I've seen a few other issues mention the desire to have a single running EventListener that "serves" multiple namespaces. Even if you can achieve that now, my understanding is that you can only really have a single Secret referenced by the GitHub interceptor on that EventListener (or Trigger). This means that all your repositories need to use the same secret in their webhook configuration, which can be undesirable. It'd be more secure if your EventListener or Trigger could reference a secret in another namespace so that each repository could have its own unique secret, stored in a Kubernetes secret in its own namespace.
