### ISSUE TITLE
TriggerTemplate unable to use JSON array as parameter

### ISSUE THREAD

**Issue by jangel97** [tektoncd/triggers#1562]
Hi,

I am trying to trigger the creation of VMs using a tekton pipeline. The idea is that there is an eventlistener which receives a HTTP POST request with the data required for the provisioning.

This is an example of the JSON payload that I need to pass to the pipelinerun:
```
{
  "systems": [
    {
      "name": "vm1webserver",
      "os": "RHEL9",
      "vm size": "small",
      "network": "default",
      "namespace": "vm-webservers"
    },
    {
      "name": "vm2webserver",
      "os": "RHEL9",
      "vm size": "small",
      "network": "default",
      "namespace": "vm-webservers"
    },
  ]
}
```
I am unable to achieve to read an object parameter using TriggerTemplate

My tekton triggers look like this:
```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: provisioning-pipelinebinding
  namespace: tekton-vm-provisioning-pipeline
spec:
  params:
    - name: systems
      value: $(body.systems)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: provisioning-automation-tt
  namespace: tekton-vm-provisioning-pipeline
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: systems
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-vm-provisioning-pipeline-
        labels:
          tekton.dev/pipeline: tekton-vm-provisioning-pipeline
        namespace: tekton-vm-provisioning-pipeline
      spec:
        params:
          - name: systems
            value: $(tt.params.systems)
        pipelineRef:
          name: vm-provisioning
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                annotations:
                  kubernetes.io/reclaimPolicy: Delete
                labels: {}
                name: ws-pvc
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 500Mi
                storageClassName: managed-nfs-storage
```
My tekton pipeline:
```
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vm-provisioning
spec:
  params:
    - name: systems
      type: array
  workspaces:
    - name: shared-workspace
  tasks:
    - name: get-cluster-info
      taskRef:
        name: get-cluster-info
      params:
        - name: names
          value: '$(params.systems[*])'
      workspaces:
        - name: source
          workspace: shared-workspace
```

When spawning pipeline I see following error:
```
PipelineRun tekton-vm-provisioning-pipeline/tekton-vm-provisioning-pipeline-jkv5k parameters have mismatching types with Pipeline tekton-vm-provisioning-pipeline/vm-provisioning's parameters: parameters have inconsistent types : [systems]
```

Is this supported in tekton?

Thanks,
