### ISSUE TITLE
Provide a mechanism to more easily access the "event" in pipelines

### ISSUE THREAD

**Issue by skaegi** [tektoncd/triggers#1574]
We run a slightly forked implementation of triggers that allows creation of the standard tekton resources as well as "configmaps". The "main" reason we need configmaps is because teams invariably want to package up the event (head and body). Typically done like so...
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - bindings:
        - name: header
          value: $(header)
        - name: body
          value: $(body)
      template:
        ref: trigger-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: header
    - name: body
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: event-$(uid)
      data:
        header: $(tt.params.header)
        body: $(tt.params.body)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: event
            configmap:
              name: event-$(uid)
```

This pattern is incredibly common -- near 100% of our pipelines use some variant of populating a workspace with the "event". Is there something we could do to make this somehow much easier and let us stop using a triggers "fork".
