### ISSUE TITLE
Interceptors Need Trigger Information

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#158]
# Problem 
The current `gh-validate` binary that is used as an EventInterceptor is very basic. For each request that comes in, it validates the [webhook payload](https://developer.github.com/webhooks/securing/#validating-payloads-from-github). To do this, it uses a single static webhook that is passed as an [enviornment variable](https://github.com/tektoncd/triggers/blob/master/examples/event-interceptors/github-validate.yaml#L35). 

This means that users using this binary have to create a new deployment per webhook secret or use the same webhook secret across multiple webhooks. Both of these are less than ideal.

# Ideas

Currently, the event listener sink forwards incoming requests as is to the interceptor. The interceptor needs a way to identify the incoming payload and associate it with an `secretRef.key` to use to fetch the right secret. A few ideas:

**Option 1**: Use a well-known field in the event payload e.g. `repository.full_name` for Github webhook events.

**Option 2**: Pass an identifier from the event listener e.g. the `trigger.name` field as a well defined header that the interceptor can use.

**Option 3**:  Add an additional field to `EventInterceptor` that allows users to pass in key value pairs:
```
  triggers:
    - name: foo-trig
      interceptor:
       params:
         - name: "secretKeyRef"
           value: "secretKeyRefValue"
        objectRef:
          kind: Service
          name: gh-validate
          apiVersion: v1
          namespace: default
```  

Options 1 and 2 do not require changing the API but it means that the interceptor needs a way to resolve the identifier to the `secretRef.key` -- either following some kind of naming convention or by using something like a `ConfigMap` that resolves the identifier to the secretRef

Option 3 is the simplest way forward for the interceptor but it does involve adding additional fields to the API.
