### ISSUE TITLE
EventListener - unable to define NodePort (Question)

### ISSUE THREAD

**Issue by hcguersoy** [tektoncd/triggers#1586]
# Expected Behavior

I expect that I'm able to configure the `NodePort` of an `EventListener`.
So my main question is: how can I tell the `EventListener` to be exposed using `NodePort` on a specific port?

# Actual Behavior

I was not able to configure the `NodePort`. Maybe this is a bug or simply missing clarification in the documentation if this feature is not available.
I assume that I missed something. 

# Steps to Reproduce the Problem

I deploy a very simple `EventListener`:

```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: simple-eventlistener
spec:
  serviceAccountName:  simple-tekton-robot
  triggers:
    - name: simple-trigger
      interceptors:
        - name: "verify-gitlab-payload"
          ref:
            name: "gitlab"
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: "gitlab-secret"
                secretKey: "verySecretToken"
            - name: eventTypes
              value:
                - "Push Hook"
      bindings:
      - ref: simple-binding
      template:
        ref: simple-template
  resources:
    kubernetesResource:
      serviceType: NodePort
      servicePort: 38080
``` 

This results in this `Service`:

```text
❯ kubectl describe service -n simple el-simple-eventlistener
Name:                     el-simple-eventlistener
Namespace:                simple
Labels:                   app.kubernetes.io/managed-by=EventListener
                          app.kubernetes.io/part-of=Triggers
                          eventlistener=simple-eventlistener
Annotations:              <none>
Selector:                 app.kubernetes.io/managed-by=EventListener,app.kubernetes.io/part-of=Triggers,eventlistener=simple-eventlistener
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.38.175
IPs:                      10.43.38.175
Port:                     http-listener  38080/TCP
TargetPort:               8080/TCP
NodePort:                 http-listener  32462/TCP
Endpoints:                10.42.0.50:8080
Port:                     http-metrics  9000/TCP
TargetPort:               9000/TCP
NodePort:                 http-metrics  30353/TCP
Endpoints:                10.42.0.50:9000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

# Additional Info

- Kubernetes version:

  ```text
  ❯ kubectl version --short 
  Client Version: v1.26.3
  Kustomize Version: v4.5.7
  Server Version: v1.25.6+k3s1
  ```

I'm running/testing currently on a local Rancher Desktop (v1.8.1)

- Tekton Pipeline version:

```text
 ❯ tkn version 
Client version: 0.30.1
Pipeline version: v0.46.0
Triggers version: v0.23.1
Dashboard version: v0.33.0
```
