### ISSUE TITLE
Event listener no able to detect the changes from the bitbucket server

### ISSUE THREAD

**Issue by tppalani** [tektoncd/triggers#1597]
# Expected Behavior

1. RBAC configured
2.  Trigger Template configured
3.  Event listener configured
4. Trigger binding configured
5. Ingress configured
6. Webhook added inside the bitbucket repository status is (successful calls 2/2 (100%))

# Actual Behavior

I have applied all the required files and i followed this page as sample https://github.com/dlorenc/triggers/tree/master/examples/bitbucket.  but when I'm checking logs from event listener i can see following error.

```
{"severity":"info","timestamp":"2023-05-27T12:40:50.103Z","logger":"eventlistener","caller":"sink/sink.go:418","message":"
interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = no X-Hub-Signature header set","
eventlistener":"bitbucket-event-listener","namespace":"devops-cost-triggers","/triggers-eventid":"4262499e-5389-49f9-8593-4258aee73629",
"eventlistenerUID":"e36d7ea0-1e4d-4759-b4c7-49a1feb85cea","/triggers-eventid":"4262499e-5389-49f9-8593-4258aee73629","
/trigger":"bitbucket-trigger-binding"}
``` 

# Steps to Reproduce the Problem

```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bitbucket-event-listener
  namespace: devops-cost-triggers
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: bitbucket-trigger-binding
      interceptors:
        - ref:
            name: bitbucket
          params:
            - name: secretRef
              value: 
                secretName: tekton-triggers-example-sa
                secretKey: secretToken
            - name: eventTypes
              value:
                - repo:refs_changed
      bindings:
       - ref: bitbucket-trigger-binding-abb
      template:
        ref: bitbucket-trigger-template-abb
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bitbucket-trigger-binding-abb
  namespace: devops-cosr-triggers
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
---
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
 Client Version: v1.26.2-eks-a59e1f0
Kustomize Version: v4.5.7
Server Version: v1.23.17-eks-0a21954
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
v0.42.0
```
