### ISSUE TITLE
Tekton Bitbucket Event listener only run when the master branch is changed 

### ISSUE THREAD

**Issue by tppalani** [tektoncd/triggers#1607]
Hi Team,

1) I have successfully configured Event listener with bitbucket server. 
2) But the problem is when new changes has been detected inside my repository pipeline getting triggered,  Instead i want trigger the pipeline when the changes has merged or committed in only master branch.

Here the code.

Trigger-binding.yaml
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bitbucket-trigger-binding
  namespace: devops
spec:
  params:
  - name: gitrevision
    value: $(body.changes[0].ref.displayId)
  - name: gitrepositoryurl
    value: $(body.repository.links.clone[1].href)
```

Eventlistener.yaml

```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-event-listener
  namespace: devops
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: bitbucket-trigger-binding
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            - name: secretRef
              value: null
            - name: eventTypes
              value:
                - repo:refs_changed
      bindings:
        - ref: bitbucket-trigger-binding
      template:
        ref: bitbucket-trigger-template
```
Trigger template

```
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: bitbucket-trigger-template
  namespace: devops
spec:
  params:
  - name: revision
  - name: url
    default: "https://bitbucket.tekton-poc.git"
  - name: flags
    default: --insecure
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: trigger-eventlistener-
    spec:
      pipelineRef:
        name: test-pipeline-triggers
      podTemplate:
        securityContext:
          runAsUser: 0
          fsGroup: 1001
      params:
        - name: repo_full_name
          value: "tekton-poc"
        - name: revision
          value: "eventlistener-trigger"
        - name: subdirectory
          value: "source"
        - name: url
          value: "https://bitbucket.tekton-poc.git"
```

**Comment by vinamra28** [comment]
hi @tppalani, probably one interceptor won't work alone, you'll have to use CEL expressions as well in order to filter the request based on custom requirements such as
```yaml
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: body.ref == 'refs/heads/main'
```
so your resultant EventListener would turn up as
```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-event-listener
  namespace: devops
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: bitbucket-trigger-binding
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            - name: secretRef
              value: null
            - name: eventTypes
              value:
                - repo:refs_changed
        - ref:
              name: "cel"
           params:
            - name: "filter"
              value: body.ref == 'refs/heads/main'
      bindings:
        - ref: bitbucket-trigger-binding
      template:
        ref: bitbucket-trigger-template
```

@dibyom @savitaashture @khrm please correct me if I missed something here
