### ISSUE TITLE
Triggers called multiple times by EventListener or never called at all

### ISSUE THREAD

**Issue by Gio-R** [tektoncd/triggers#1617]
# Expected Behavior
With the following EventListener I expect the selected Triggers to be called:
```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: push-listener
  namespace: default
spec:
  serviceAccountName: tekton-robot
  triggerGroups:
  - name: gitlab
    interceptors:
    - name: gitlab
      ref:
        name: "gitlab"
      params:
      - name: secretRef
        value:
          secretName: gitlabSecret
          secretKey: secretToken
      - name: eventTypes
        value: ["Push Hook"]
    triggerSelector:
      labelSelector:
        matchLabels:
          idp/trigger-type: component-ci
      namespaceSelector:
        matchNames:
        - '*'
```

# Actual Behavior
The selected Triggers are not called and adding the following `spec.namespaceSelector` section to the above EventListener causes the Trigger to be called two times instead of the expected one:
```
  namespaceSelector:
    matchNames: 
    - '*'
```

# Steps to Reproduce the Problem

1. Install the Tekton Operator version 0.67
2. Create the above EventListener and a Trigger that satisfies the triggerSelector
3. Send a Gitlab webhook push payload to the EventListener Service

# Additional Info

- Kubernetes version:
  ```
  Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
  Kustomize Version: v5.0.1
  Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/arm64"}
  ```

- Tekton Pipeline version: v0.47.0
- Tekton Triggers version: v0.24.0
