### ISSUE TITLE
Cant't creating EventListener

### ISSUE THREAD

**Issue by Yeroha** [tektoncd/triggers#1634]
tkn version
```
Client version: 0.28.0
Pipeline version: v0.50.0
Triggers version: v0.24.1
Dashboard version: v0.38.0
```

k8s version: 
`v1.25.4+rke2r1`

I have manifets:
```
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-interceptor
  namespace: tkn-cicd
spec:
  serviceAccountName: tkn-git-ssh
  triggers:
    - name: gitlab-listener-trigger
      interceptors:
        - name: "gitlab-interceptor-payload"
          ref:
            name: "gitlab"
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: "gitlab-interceptor-secret"
                secretKey:  "secretToken"
            - name: eventTypes
              value:
                - "Push Hook"
                - "Tag Push Hook"
        - name: "CEL filter: only master branch"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref in ['refs/heads/master']"
            - name: "overlays"
              value:
              - key: branch_name
                expression: "body.ref.split('/')[2]"
      bindings:
        - ref: tkn-trigger-binding
      template:
        ref: tkn-trigger-template
```
This manifest return error and EvenListener failed:
```
{"severity":"info","timestamp":"2023-08-28T09:47:49.353Z","caller":"logging/config.go:80","message":"Unable to read vcs.revision from binary"}
{"severity":"fatal","timestamp":"2023-08-28T09:47:49.386Z","logger":"eventlistener","caller":"v2/main.go:205","message":"Start returned an error","error":"Timed out waiting on CaBundle to available for clusterInterceptor: Timed out waiting on CaBundle to available for Interceptor: empty caBundle in clusterInterceptor spec"}
```

Please help us
