### ISSUE TITLE
Make TriggerBindings optional for EventListeners

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#165]
# Expected Behavior

Don't require a TriggerBinding for EventListeners. If it is not defined, assume there are no bindings.

# Actual Behavior

EventListener fails (not during creation, during runtime) with the error:

```
2019/10/10 19:31:03 Error getting TriggerBinding : resource name may not be empty
```

This error is visible in the event listener pod logs.

# Steps to Reproduce the Problem

Sample event listener (adapted from https://github.com/tektoncd/triggers/pull/162/commits/d9baa3bccbf3ab22b8c9849a5a0e2df8a8171514):

```
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cron-trig
      template:
        name: pipeline-template
      params:
      - name: message
        value: Hello from the Triggers EventListener!
      - name: gitrevision
        value: master
      - name: gitrepositoryurl
        value: https://github.com/tektoncd/triggers
```
