### ISSUE TITLE
Starting the multiple triggers with Github interceptor is limited by the client rate limiter 

### ISSUE THREAD

**Issue by Aqaliarept** [tektoncd/triggers#1684]
I'm trying to build a developer's cluster with ephemeral environments for feature branches. 
Each environment is located in a dedicated namespace (name same as the git branch name) and contains a set of triggers for building services in the repository.

Each trigger filters git pushes by the branch name and service folder inside the git repository.  The basic idea is to start the pipeline only push was made for a proper branch and contains changes for the specific service.
```
spec:
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-interceptor-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
        - name: "addChangedFiles"
          value:
            enabled: true
    - ref:
        name: cel
      params:
      - name: filter
        value: |
          body.ref.split('/')[2].matches('{{ $env.branchName }}') && (
            extensions.changed_files.matches('{{ $image.build.sourceDir }}/')
          )  
```
There is a single ```EventListener```, that spawns all those triggers in all namespaces:
```
spec:
  namespaceSelector:
    matchNames:
    - "*"  
  labelSelector:
    matchLabels:
      build: backend
```  

**The problem** : when the trigger number grows over 25, the rest of the triggers start to fail with the error:  
```
"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = error getting secret: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"
```

It looks like the triggers are limited by the cooperative access to the secret, specified in ```secretRef``` configuration.

**Comment by timur-nugaev** [comment]
I found the workaround with the usage of TriggerGroups and the single github Interceptor.

**Comment by savitaashture** [comment]
WG discussion:

Based on the issue description even we thought that TriggerGroups and the single github Interceptor is a way to go as here you are using same interceptor

**Comment by dmitry-mightydevops** [comment]
alt option would be to increase qps for the interceptor deployment

```
➜ k ice command -l app.kubernetes.io/component=interceptors
PODNAME                                             CONTAINER                          COMMAND  ARGUMENTS
tekton-triggers-core-interceptors-59c7dbb867-l5q6l  tekton-triggers-core-interceptors  -        -logtostderr -stderrthreshold INFO -kube-api-qps 50 -kube-api-burst 50

```

```yaml
serviceAccountName: tekton-triggers-core-interceptors
      containers:
        - name: tekton-triggers-core-interceptors
          image: "ghcr.io/tektoncd/triggers/interceptors-3176d6a3f314c3655b30bfd36e421dd5:v0.31.0@sha256:7662d66b3b471fce5d7510592c744d87701a3c5c424d50b22c4f45146e0aa10d"
          ports:
            - containerPort: 8443
          args: [
            "-logtostderr", "-stderrthreshold", "INFO",
            "-kube-api-qps", "50",
            "-kube-api-burst", "50"
          ]
```
