### ISSUE TITLE
Proposal to add arbitrary labels for generated resources

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/triggers#169]
# Expected Behavior
@dibbles and I have been pondering how to see what PipelineRuns/Pipelineresources were created by certain triggers (for our use case, so we can monitor them and report on GitHub if the Tasks all passed)

Example labels would be, for example, the Git repository URL, branch, the trigger name, any other params etc

# Actual Behavior
This isn't here atm

**Comment by wlynch** [comment]
I think you should be able to do this today with `TriggerTemplate`. e.g.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: triggerName
    description: Name of the trigger
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      labels:
        my-label: $(params.triggerName)  # This can be replaced with any param
any binding.
```

For reusability, you could set this in the EventListener on a per Trigger basis:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: el
spec:
  triggers:
    - name: foo
      template:
        name: pipeline-template
      params:
      - name: triggerName
        value: "my-trigger"
```

Now, it's an open question whether this should happen **automatically** for all resources created. My gut instinct is to add `trigger.name` similar to [event listener name and event id](https://github.com/tektoncd/triggers/blob/22060fd548fafe51fb701c2b2200303fa853d8ca/pkg/sink/sink.go#L184-L191) to allow tracing of created resources, and leave all other labels to be defined by the user via parameters.

Let me know if this sounds reasonable! I'm happy to pick up this work.
