### ISSUE TITLE
How to give affinity and toleration to Tekton Eventlistner 

### ISSUE THREAD

**Issue by ritesh-makerble** [tektoncd/triggers#1703]

**Comment by khrm** [comment]
@ritesh-makerble What about this example: https://github.com/tektoncd/triggers/blob/main/examples/v1beta1/eventlisteners/eventlistener-tolerations.yaml

**Comment by khrm** [comment]
So try this:
```
spec:
  serviceAccountName: github-trigger
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            tolerations:
                - key: "kubernetes.azure.com/scalesetpriority"
                  operator: "Equal"
                  value: "spot"
                  effect: "NoSchedule"
                - key: "type"
                  operator: "Equal"
                  value: "spot-1"
                  effect: "NoSchedule""
```
