### ISSUE TITLE
Proposal: Allow multiple TriggerBindings in Triggers

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#176]
# Expected Behavior

Allow triggers to be composed from multiple trigger bindings.

Motivating example: Have one trigger binding that extracts relevant parameters from the incoming event and provide a second binding that provides environment specific parameters (e.g. where to run/deploy).

Example:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: event-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: prod-env
spec:
  params:
  - name: environment
    value: prod
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - name: prod-trigger
      binding:
        - name: event-binding
        - name: prod-env
      template:
        name: pipeline-template
    - name: staging-trigger
      binding:
        - name: event-binding
        - name: staging-env
      template:
        name: pipeline-template
```

# Actual Behavior

Triggers only allow specifying one TriggerBinding.

# Additional Info

This is similar to #87, but focuses on just allowing multiple bindings without introducing a new ParamBinding type.

Things to think about:
* What happens if multiple trigger bindings specify the same param?
