### ISSUE TITLE
I can't understand why gitlab interceptor is complaining about invalid token

### ISSUE THREAD

**Issue by alansenairj** [tektoncd/triggers#1764]
I am creating this to try to understand how it works. 

```
---
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener-payload-test
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: gitlab-trigger
      interceptors:
        - name: verify-gitlab-payload
          ref:
            name: gitlab  # GitLab interceptor reference
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: git-credentials
                secretKey: id_rsa
            - name: eventTypes
              value:
                - "Push Hook"
                #- "Merge Request Hook"
                #- "Pipeline Hook"
                #- "Tag Push Hook"
                #- "Issue Hook"
                #- "Job Hook"
      bindings:
        - ref: gitlab-push-binding  # Reference the TriggerBinding
      template:
        ref: gitlab-trigger-template  # Reference the TriggerTemplate

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-push-binding
spec:
  params:
    - name: payload
      value: "$(body)"  # Extract the entire body
   # - name: gitrevision
   #   value: "$(body.checkout_sha)"  # Extract the git SHA
   # - name: gitrepositoryurl
   #   value: "$(body.project.git_http_url)"  # Extract the repository URL


---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gitlab-trigger-template
spec:
  params:
    - name: payload
      description: The full body of the webhook event  
    #- name: gitrevision
    #  description: The Git SHA from the webhook
    #- name: gitrepositoryurl
    #  description: The Git repository URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: log-payload-test-taskrun-
      spec:
        taskRef:
          name: log-payload-test  # Reference the Task
        params:
          - name: payload
            value: "$(params.payload)"  # Pass the payload from the event
          #- name: gitrevision
          #  value: "$(params.gitrevision)"  # Pass the gitrevision param
          #- name: gitrepositoryurl
          #  value: "$(params.gitrepositoryurl)"  # Pass the repository URL

```
Refs to this task:
```
# Add a simple echo TaskRun to your EventListener to log the incoming payload
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: log-payload-test
spec:
  params:
    - name: payload  # Declare the payload parameter
      description: The webhook payload
      type: string
  
  steps:
  - name: echo
    image: alpine
    script: |
      env
      echo "Payload: $(params.payload)"  # Reference the parameter correctly

```

I got this: 
```
1 - disabling  token header: 
[gitlab-listener-payload-test-el-gitlab-listener-payload-test-766b668c4-c5f7w]: {"level":"debug","ts":"2024-09-06T15:00:25.646Z","logger":"eventlistener","caller":"sink/metrics.go:115","msg":"event listener request","commit":"b133ef7-dirty","status":"succeeded"}
[gitlab-listener-payload-test-el-gitlab-listener-payload-test-766b668c4-c5f7w]: {"level":"debug","ts":"2024-09-06T15:00:25.646Z","logger":"eventlistener","caller":"sink/metrics.go:100","msg":"event listener request completed","commit":"b133ef7-dirty","status":202,"duration":0.00020838}
[gitlab-listener-payload-test-el-gitlab-listener-payload-test-766b668c4-c5f7w]: {"level":"debug","ts":"2024-09-06T15:00:25.648Z","logger":"eventlistener","caller":"sink/sink.go:420","msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = no X-GitLab-Token header set","commit":"b133ef7-dirty","eventlistener":
"gitlab-listener-payload-test","namespace":"cicd-tools","/triggers-eventid":"f0e11a3b-3f8d-49b9-b32c-33bd843ef2a1","eventlistenerUID":"fe4a3800-3e99-4785-b6f0-4363c8f41338","/triggers-eventid":"f0e11a3b-3f8d-49b9-b32c-33bd843ef2a1","/trigger":"gitlab-trigger"}


2- enabling token header: 

[gitlab-listener-payload-test-el-gitlab-listener-payload-test-766b668c4-c5f7w]: {"level":"debug","ts":"2024-09-06T15:02:08.465Z","logger":"eventlistener","caller":"sink/metrics.go:115","msg":"event listener request","commit":"b133ef7-dirty","status":"succeeded"}
[gitlab-listener-payload-test-el-gitlab-listener-payload-test-766b668c4-c5f7w]: {"level":"debug","ts":"2024-09-06T15:02:08.465Z","logger":"eventlistener","caller":"sink/metrics.go:100","msg":"event listener request completed","commit":"b133ef7-dirty","status":202,"duration":0.000198948}
[gitlab-listener-payload-test-el-gitlab-listener-payload-test-766b668c4-c5f7w]: {"level":"debug","ts":"2024-09-06T15:02:08.466Z","logger":"eventlistener","caller":"sink/sink.go:420","msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = Invalid X-GitLab-Token","commit":"b133ef7-dirty","eventlistener":"gitla
b-listener-payload-test","namespace":"cicd-tools","/triggers-eventid":"2cd5d4c2-248e-48c3-a5f0-30d94c9bbee0","eventlistenerUID":"fe4a3800-3e99-4785-b6f0-4363c8f41338","/triggers-eventid":"2cd5d4c2-248e-48c3-a5f0-30d94c9bbee0","/trigger":"gitlab-trigger"}


```

I am testing like this:

```
curl -v \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: GitLab/17.4.0-pre' \
  -H 'Idempotency-Key: bdce583c-6ac3-403a-8337-0048e1907be7' \
  -H 'X-Gitlab-Event: Push Hook' \
  -H 'X-Gitlab-Webhook-UUID: 0f92c29c-f489-4063-a9d5-8a73af9a34cd' \
  -H 'X-Gitlab-Instance: https://gitlab.com' \
  -H 'X-Gitlab-Event-UUID: 61e396dc-510c-4e1d-a6ce-8eec0a1939e1' \
  -H 'X-Gitlab-Token: <NEW TOKEN CREATED AND 1234567 AND ANOTHER VALID TOKEN TOO>' \
  -d "@payload-gitlab-push.json" \  ====PAYLOAD SENT BY WEBHOOK TEST
  http://localhost:8080`

```

I can't understand why interceptor is complaining about it because I am passing token in header. 

I am testing this EL with port forward. rbac applied works with other task and it triggered taht task.
