### ISSUE TITLE
EventListener Unsupported Protocol Scheme Error

### ISSUE THREAD

**Issue by sidharthsudheer20** [tektoncd/triggers#1772]
# EventListener Unsupported Protocol Scheme Error

### **Expected Behavior**
The Tekton EventListener should correctly process incoming GitHub webhook events without errors, properly identifying and handling the protocol.

### **Actual Behavior**
The Tekton EventListener fails to process GitHub webhook events and logs the error:
```
{"level":"error","ts":"2024-10-09T09:27:42.006Z","logger":"eventlistener","caller":"sink/sink.go:414","msg":"Post \"\": unsupported protocol scheme \"\"","commit":"b133ef7-dirty","eventlistener":"default-listener","namespace":"default","/triggers-eventid":"709d9f0f-bb8f-4743-899d-250a81c75e6e","eventlistenerUID":"9d5e8cd6-9b3b-4445-b648-fe59ecf975f3","/triggers-eventid":"709d9f0f-bb8f-4743-899d-250a81c75e6e"
```

### **Steps to Reproduce the Issue**
1. Configure a Tekton EventListener with a GitHub interceptor.
2. Set up a GitHub webhook to trigger the EventListener.
3. Trigger a GitHub event (e.g., push or pull request) to invoke the EventListener.

### **Additional Information**
- **Kubernetes Version:**

  ```
  Client Version: v1.29.7
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.29.7+6abe8a1
  ```

- **Tekton Pipeline Version:**

  ```
  v0.62.0
  ```

- **EventListener Configuration:**

  ```yaml
   apiVersion: triggers.tekton.dev/v1alpha1
   kind: EventListener
   metadata:
     name: default-listener
     namespace: default
   spec:
     serviceAccountName: build-scc
     triggers:
       - name: zookeeper-build-trigger
         interceptors:
           - ref:
               name: "github"
               kind: ClusterInterceptor
               apiVersion: triggers.tekton.dev
             params:
             - name: "secretRef"
               value:
                 secretName: github-secret
                 secretKey: secretToken
             - name: "eventTypes"
               value: ["pull_request", "push"]
             - name: "addChangedFiles"
               value:
                 enabled: true
           - ref:
               name: cel
             params:
             - name: filter
               value: extensions.changed_files.matches('/operator/zookeeper/')
         bindings:
         - ref: default-pipelinebinding
         template:
           ref: default-triggertemplate


  ```

- **Logs:**
  ```
   {"level":"debug","ts":"2024-10-09T09:41:13.819Z","logger":"eventlistener","caller":"sink/metrics.go:115","msg":"event listener request","commit":"b133ef7-dirty","status":"succeeded"}
   {"level":"debug","ts":"2024-10-09T09:41:13.819Z","logger":"eventlistener","caller":"sink/metrics.go:100","msg":"event listener request completed","commit":"b133ef7-dirty","status":202,"duration":0.001259106}
   {"level":"error","ts":"2024-10-09T09:41:13.837Z","logger":"eventlistener","caller":"sink/sink.go:414","msg":"Post \"\": unsupported protocol scheme \"\"","commit":"b133ef7-dirty","eventlistener":"default-listener","namespace":"default","/triggers-eventid":"7a9923a1-af8b-4baf-93c2-219e2a1cf66a","eventlistenerUID":"9d5e8cd6-9b3b-4445-b648-fe59ecf975f3","/triggers-eventid":"7a9923a1-af8b-4baf-93c2-219e2a1cf66a","/trigger":"zookeeper-build-trigger","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:414\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:202"}
  ```

**Comment by khrm** [comment]
Did you choose non Json Webhook?

**Comment by sidharthsudheer20** [comment]
No...its JSON 
`application/json`

**Comment by khrm** [comment]
I tried recreating this using the following example: https://github.com/tektoncd/triggers/tree/main/examples/v1beta1/github-add-changed-files-push-cel

Above error isn't happening. I configured with a repo.

**Comment by khrm** [comment]
Can you please provide some more concrete example where we can recreate this?

**Comment by sidharthsudheer20** [comment]
I’ve set it up on OpenShift, and here is the configuration I used for the triggers.

**Comment by khrm** [comment]
@savitaashture Can you look into this?

**Comment by savitaashture** [comment]
Hi @sidharthsudheer20 i tried your example and i don't see any such errors
I got success response in el pod as well as interceptor pod

Interceptor pod log:
```
{"level":"info","ts":1730807196.560467,"caller":"server/server.go:153","msg":"Interceptor response is: &{Extensions:map[changed_files:README.md] Continue:true Status:{Code:OK Message:}}"}
{"level":"info","ts":1730807196.5625138,"caller":"server/server.go:153","msg":"Interceptor response is: &{Extensions:map[] Continue:false Status:{Code:FailedPrecondition Message:expression extensions.changed_files.matches('operator/zookeeper/') did not return true}}"}
```

EL pod log
```
{"severity":"info","timestamp":"2024-11-05T11:46:36.534Z","logger":"eventlistener.event-broadcaster","caller":"record/event.go:364","message":"Event(v1.ObjectReference{Kind:\"EventListener\", Namespace:\"test-1\", Name:\"default-listener\", UID:\"\", APIVersion:\"v1beta1\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Normal' reason: 'dev.tekton.event.triggers.started.v1' ","commit":"616cae1"}
{"severity":"info","timestamp":"2024-11-05T11:46:36.534Z","logger":"eventlistener.event-broadcaster","caller":"record/event.go:364","message":"Event(v1.ObjectReference{Kind:\"EventListener\", Namespace:\"test-1\", Name:\"default-listener\", UID:\"07964c2a-f4d4-41a1-bb66-2494a11f06fa\", APIVersion:\"triggers.tekton.dev/v1beta1\", ResourceVersion:\"68393\", FieldPath:\"\"}): type: 'Normal' reason: 'dev.tekton.event.triggers.done.v1' ","commit":"616cae1"}
```

**Comment by sidharthsudheer20** [comment]
Can you provide me the core interceptor configuration ?

**Comment by W1zzardTPU** [comment]
I just had the same error on a fresh cluster, with a "known good" configuration. 

For debugging, I messed around in the Trigger yaml, added/removed sections, disabled "enabled: true" and enabled it again, and it magically worked after that.

```
  interceptors:
    - name: "Add list of changed files"
      ref:
        name: "github"
        kind: ClusterInterceptor
        apiVersion: triggers.tekton.dev
      params:
      - name: "eventTypes"
        value: ["push"]
      - name: "addChangedFiles"
        value:
          enabled: true <--- I set this to 'false', sent the webhook, got an error message, set it to true, sent it again and it worked
```

Tekton deployed using ArgoCD. Random guess: maybe there is some timing issue that causes addChangedFiles to break when not all of Tekton is running?
