### ISSUE TITLE
TriggerBinding interpolation does not support OwnerReferences

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#184]
# Expected Behavior
Resources are created in order so we should be able to specify `OwnerReferences` on resource templates within the `TriggerBinding`.

# Actual Behavior
There is no interpolation variable to provide access to the necessary variables to do this.

# Additional Info
This is mostly a continuation of https://github.com/tektoncd/triggers/issues/50. In order to achieve this we would store the metadata of resources created in the `TriggerBinding` for interpolation within later resource templates. The following example adds a monitor task to the current `TriggerBinding` documentation example:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run
    spec:
      pipelineRef:
        name: simple-pipeline
      params:
      - name: message
        value: $(params.message)
      - name: contenttype
        value: $(params.contenttype)
      resources:
      - name: git-source
        resourceRef:
          name: git-source-$(uid)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run-monitor
      ownerReferences:
      - name: $(meta[1].name)
        apiVersion: tekton.dev/v1alpha1
        kind: PipelineRun
        uid: $(meta[1].uid)
    spec:
      pipelineRef:
        name: pipeline-monitor
      params:
      - name: pipeline
        value: $(meta[1].name)
```

The interpolation syntax could use indexes as above or we could add a name field for each resource template and refer to them in this way. If we expand Triggers outside of Tekton resources, this can prove more valuable. It is hard to determine whether this sort of behavior should happen within a `Task` or a `TriggerBinding` so maybe it's not as important?
