### ISSUE TITLE
Question: duplicate triggers after merging in eventlisteners is expected behavior?

### ISSUE THREAD

**Issue by l-qing** [tektoncd/triggers#1841]
# Expected Behavior

The same event in an EventListener should only trigger once for a specific trigger, rather than multiple times.

# Actual Behavior

Triggered multiple times.

# Steps to Reproduce the Problem

1. create `EventListener`
```yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-ref-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - triggerRef: trigger-x
  namespaceSelector:
    matchNames:
    - "*"
```

2. After receiving the event, the `trigger-x` will be triggered multiple times.

3. This is because a trigger was found based on the namespaceSelector. Then, triggers were found again, and there was no de-duplication in the code merge.

https://github.com/tektoncd/triggers/blob/b27feb038baf26befc114c25576243baaea0939d/pkg/sink/sink.go#L286-L296

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.31.6
WARNING: version difference between client (1.33) and server (1.31) exceeds the supported minor version skew of +/-1

Triggers version: v0.30.1
```
