### ISSUE TITLE
event-listener container fails with: empty caBundle in clusterInterceptor spec

### ISSUE THREAD

**Issue by T0MASD** [tektoncd/triggers#1846]
# Expected Behavior

el-tls-listener-interceptor works

# Actual Behavior

```
{"severity":"fatal","timestamp":"2025-05-21T19:02:47.879Z","logger":"eventlistener","caller":"v2/main.go:205","message":"Start returned an error","commit":"4db
b0a6","error":"Timed out waiting on CaBundle to available for clusterInterceptor: Timed out waiting on CaBundle to available for Interceptor: empty caBundle in clusterInterceptor spec"}                                                                                                                                     
stream closed EOF for docs-cicd/el-tls-listener-interceptor-bffc54d95-k5zf7 (event-listener)         
```

# Steps to Reproduce the Problem

Apply yaml to create el-tls-listener-interceptor

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: docs-cicd
---
# Role with full permissions within the docs-cicd namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-full-access
  namespace: docs-cicd
rules:
  # All Tekton core resources
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources", "conditions", "runs"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  
  # All Tekton Triggers resources
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["triggers", "triggerbindings", "triggertemplates", "eventlisteners", "interceptors"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  
  # Special finalizer permissions needed by EventListeners
  - apiGroups: ["tekton.dev", "triggers.tekton.dev"]
    resources: ["eventlisteners/finalizers"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  
  # Kubernetes core resources needed by Tekton
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  
  # Additional networking resources for EventListeners
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
# RoleBinding to grant the tekton-triggers-sa service account all permissions in the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-full-access-binding
  namespace: docs-cicd
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: docs-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-full-access
---
# The only ClusterRole needed - for accessing ClusterInterceptors
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-clusterinterceptors-role
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors"]
    verbs: ["get", "list", "watch"]
---
# Binding to the minimal ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-clusterinterceptors-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: docs-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-clusterinterceptors-role
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
---
apiVersion: v1
data:
  tls.crt: ...
  tls.key: ...
kind: Secret
metadata:
  name: tls-secret-key
type: generic

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tls-listener-interceptor
spec:
  triggers:
    - name: tls-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: tls-pr-binding
      template:
        ref: tls-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa
            containers:
            - env:
              - name: TLS_CERT
                valueFrom:
                  secretKeyRef:
                    name: tls-secret-key
                    key: tls.crt
              - name: TLS_KEY
                valueFrom:
                  secretKeyRef:
                    name: tls-secret-key
                    key: tls.key
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tls-pr-binding
spec:
  params:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tls-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        generateName: tls-run-
      spec:
        taskSpec:
          inputs:
            resources:
              - name: source
                type: git
          steps:
            - image: ubuntu
              script: |
                #! /bin/bash
                ls -al $(inputs.resources.source.path)
        inputs:
          resources:
            - name: source
              resourceSpec:
                type: git
                params:
                  - name: revision
                    value: $(tt.params.gitrevision)
                  - name: url
                    value: $(tt.params.gitrepositoryurl)

```

# Additional Info

pod describe .spec
```yaml
spec:
  containers:
  - args:
    - --el-name=tls-listener-interceptor
    - --el-namespace=docs-cicd
    - --port=8080
    - --readtimeout=5
    - --writetimeout=40
    - --idletimeout=120
    - --timeouthandler=30
    - --httpclient-readtimeout=30
    - --httpclient-keep-alive=30
    - --httpclient-tlshandshaketimeout=10
    - --httpclient-responseheadertimeout=10
    - --httpclient-expectcontinuetimeout=1
    - --is-multi-ns=false
    - --payload-validation=true
    - --cloudevent-uri=
    - --tls-cert=/etc/triggers/tls/tls.crt
    - --tls-key=/etc/triggers/tls/tls.key
    env:
    - name: K_LOGGING_CONFIG
      value: '{"zap-logger-config":"{\n  \"level\": \"info\",\n  \"development\":
        false,\n  \"disableStacktrace\": true,\n  \"sampling\": {\n    \"initial\":
        100,\n    \"thereafter\": 100\n  },\n  \"outputPaths\": [\"stdout\"],\n  \"errorOutputPaths\":
        [\"stderr\"],\n  \"encoding\": \"json\",\n  \"encoderConfig\": {\n    \"timeKey\":
        \"timestamp\",\n    \"levelKey\": \"severity\",\n    \"nameKey\": \"logger\",\n    \"callerKey\":
        \"caller\",\n    \"messageKey\": \"message\",\n    \"stacktraceKey\": \"stacktrace\",\n    \"lineEnding\":
        \"\",\n    \"levelEncoder\": \"\",\n    \"timeEncoder\": \"iso8601\",\n    \"durationEncoder\":
        \"\",\n    \"callerEncoder\": \"\"\n  }\n}\n"}'
    - name: K_METRICS_CONFIG
      value: '{"Domain":"tekton.dev/triggers","Component":"eventlistener","PrometheusPort":0,"PrometheusHost":"","ConfigMap":{}}'
    - name: K_TRACING_CONFIG
      value: '{"backend":"none","debug":"false","sample-rate":"0.1"}'
...
```

- Kubernetes version:

  ```
 kubectl version
Client Version: v1.29.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.12
  ```

- Tekton Pipeline version:

  **v20250521-32872165de`**
