### ISSUE TITLE
FR: Dynamic TriggerTemplate Resources

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#189]
## Motivating Use Case

Be able to run/test Tekton Trigger configurations ephemerally without needing to apply it permanently to the cluster. e.g. how do I test a change to a Template/Pipeline config?

## Proposed Solution

Add a new type that can be included in TriggerTemplates that will read configuration dynamically from a file.

This type should take a volume generating resource (such as [GitResource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#git-resource) or [StorageResource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#storage-resource)) as an input.

### Example
```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-repo
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: DynamicResource
    metadata:
      name: dynamic-resource
    spec:
      path: '/path/to/my/config.yaml'
      inputs:
        resourceRef:
          name: git-repo
```

Where `/path/to/my/config.yaml` references a file containing other TriggerTemplate resources ([example](https://github.com/tektoncd/triggers/blob/master/tekton/resources.yaml))

## Open Questions

1. Will there be any issues in order when referencing a Resource from another Resource?
2. Name? DynamicResource? FileResource?

## TODO
- [ ] Write full design
- [ ] Implement
