### ISSUE TITLE
TriggerTemplateRun !?

### ISSUE THREAD

**Issue by skaegi** [tektoncd/triggers#200]
TriggerTemplates are really important to us as we use them to lay down non Tekton resources like ConfigMaps and Secrets however we have been forced to write our own implementation because our eventing is totally different. In addition to event based triggering we support API based triggering and what I observed is that the payload looks remarkably like what I imagine a TriggerTemplateRun object would be if it existed. Maybe something like...
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplateRun
metadata:
  name: mytemplaterun
spec:
  templateRef:
    name: mytemplate
  params:
  - name: revision
     value: v0.32.0
  - name: url
     value: https://github.com/GoogleContainerTools/skaffold
```
What I'm wondering is if Triggers could directly expose the TriggerTemplateRun instead of hiding it inside. This would let us adopt the Triggers controller at least for the Templating piece.
