### ISSUE TITLE
FR: Suport core/built-in event interceptors

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#207]
We should add a set of "core" built-in interceptors e.g. for for validating Github/Gitlab payloads. This will simplify things for the user as they do not have to deploy their own services to use them. 

Previously mentioned in the [interceptors design doc](https://docs.google.com/document/d/1sw6R-DHmGzfHpD6itMr1AgmNdsjkFdMIUZhv-L6OQLw/edit#heading=h.z3hraejv7bmg) 

In terms of syntax, we could either allow a `type` and set of key value pairs:
```
type EventInterceptor struct {
	Header []pipelinev1.Param json:"header,omitempty"
	ObjectRef *corev1.ObjectReference json:"objectRef,omitempty"
	InterceptorType string
	InterceptorParams map[string]string
}
```

Or we could have a more "typed" approach:

```
interceptor:
  githubValidation:
    repoName: "foo/bar"
    secretToken: ""  
  ```

cc @dlorenc

**Comment by dlorenc** [comment]
Nice!

**Comment by dlorenc** [comment]
The proposed schema is:

```yaml
interceptor:
  webhook:
    ...       
  github:
    secretRef:
      secretName: foo
      secretKey: bar
  gitlab:
    ...
```

The existing `objectRef` and `header` fields will move under `webhook`, and then other core interceptors will appear at the top level next to `webhook`.
