### ISSUE TITLE
Matching on GitHub events

### ISSUE THREAD

**Issue by bigkevmcd** [tektoncd/triggers#243]
# Proposal

Now that we have GitHub/GitLab interception, it'd be nice if we could match only on specific branch/repo combinations for things.

e.g. if you want to only execute triggers on a push to "master" for a repo, or maybe a build when a pull request is opened in a repo.

Perhaps something like...

```yaml
  triggers:
    - name: foo-trig
      interceptor:
        github:
          secretRef:
            secretName: foo
            secretKey: bar
            namespace: baz
          eventTypes:
          - pull_request:
              repo: tektoncd/triggers
              action: opened
      bindings:
      - name: pipeline-binding
      template:
        name: pipeline-template
```

or for merges:

```yaml
          eventTypes:
          - push:
              repo: tektoncd/triggers
              branch: master
```

For GitLab support, I'm not sure if this would use `merge_request` (GitLab terminology) or `pull_request`, that's a fairly trivial change tho'.

If configured to match only on `pull_request` events, it would return an error if it didn't match the repo/action combination, for unknown events/unconfigured events, it would just return the body unchanged.
