### ISSUE TITLE
Proposal: Typed Values for TriggerBindings

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#253]
# Current Behavior

Currently, TriggerBindings are a lot like `Params` in pipelines i.e. they have a `name` and a `value` field. The value field can either contain an expression - GJson/JSONPath which are wrapped in `$()` or it can be static string i.e. not wrapped in `$()`.
```
spec:
  params:
  - name: gitrevision
    value: "$(body.head_commit.id)"
  - name: docker-registry
    value: "gcr.io/my-docker"
```
# Proposal

Instead of reusing the same `value` filed and using `$()` to differentiate between expressions and strings we could use separate fields instead. This will allow us to get rid of the enclosing `$()` in front of the expressions
e.g. 
```
spec:
  params:

  - name: gitrevision
    jsonPath: body.head_commit.id

  - name: docker-registry
    string: "gcr.io/my-docker"
```

Another alternative would be to get rid of the top level `params` as well:

```
spec:
  jsonPath:
  - name: gitrevision
    value: body.head_commit.id
  string:
  - name: docker-registry
    value: "gcr.io/my-docker"
```

cc @wlynch
