### ISSUE TITLE
Add health check URL for eventlistener

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/triggers#276]
# Expected Behavior

Health check requests should be processed separately from events

# Actual Behavior

Health check requests should be processed separately from events but the separate URL doesn't exist for the health check now so they are sent to the same URL as events.  It causes extra usage of the resources and filling the event listener log with the entries like below. 
```
2019/12/12 20:25:09 EventListener: tekton-webhooks-eventlistener in Namespace: tekton-pipelines handling event (EventID: bbfbh) with payload:  and header: map[Accept-Encoding:[gzip, compressed] Connection:[close] User-Agent:[ELB-HealthChecker/2.0]]
2019/12/12 20:25:09 Error Intercepting Event (EventID: rqd2n): "Not OK response from Event Processor: Request rejected; status: 417 Expectation Failed; message: Webhook request has unsupported Content-Type \"\"\n"
```

# Steps to Reproduce the Problem

1. Install pipeline and trigger in EKS
2. Create an ALB (ingress) like below
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      kubernetes.io/ingress.class: alb
eventlistener
  spec:
    rules:
    - host: 3ba9f977-tektonpipelines-e-828b-301609709.us-east-2.elb.amazonaws.com
      http:
        paths:
        - backend:
            serviceName: el-tekton-webhooks-eventlistener
            servicePort: 8080
```

# Additional Info

ALB supports annotations to specify the health check URL separately.
