### ISSUE TITLE
Does GitLab Interceptor need to trim secretData?

### ISSUE THREAD

**Issue by liuchintao** [tektoncd/triggers#311]
This is my gitlab secret token config and curl command.

gitlab-webhook-token.yaml

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: webhook-demo-token
  namespace: deploy-ci
type: Opaque
data:
  demotoken: "aGVsbG8K" # echo hello | base64
```

```shell
curl -XPOST -H "X-GitLab-Token:hello" <hook url> -d '...'
```

I think the `task` pod should create after I request, however `el-xxx` pod's log says that:

```log
# These lines are my debug-prints
Header Secret: [104 101 108 108 111]
Stored Secret: [104 101 108 108 111 10]
Header Secret: hello
Stored Secret: hello

{"level":"error","logger":"eventlistener","caller":"sink/sink.go:107","msg":"Invalid X-GitLab-Token","knative.dev/controller":"eventlistener","/triggers-eventid":"d8c6v","/trigger":"demo-push-only-trig","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:107"}
```

I found that `secretData` got from k8s client would add a line break?

How can I use Tekton-Trigger with gitlab?
