### ISSUE TITLE
Feature Request: Clusterwide TriggerBinding

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/triggers#322]
In tektoncd/triggers, Trigger Binding is the concept that is used to extract details from the events and stored as parameters to use further.

TriggerBindings are designed with the consideration of reusability. A user can associate a TriggerBinding with multiple EventListeners.

Currently, TriggerBinding is a namespaced resource and it is reusable only within a namespace. If a user wants to use the same TriggerBinding in different namespaces, they would have to duplicate it in those namespaces as well.

Analogous to the concept of Tasks and ClusterTasks in tektoncd/pipeline, tektoncd/triggers should also have the concept of TriggerBindings and ClusterTriggerBindings. This will resolve the above-mentioned problem of using the same TriggerBinding in multiple namespaces.

The CRD will look like:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustertriggerbindings.tekton.dev
spec:
  group: tekton.dev
  scope: Cluster
  names:
    kind: TriggerBinding
    plural: clustertriggerbindings
    singular: clustertriggerbinding
    shortNames:
      - ctb
    categories:
      - all
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
```

An example on how to create a new ClusterTriggerBinding is similar to TriggerBinding, only the kind will change.
```
apiVersion: tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)
```
Example on how to use it with TriggerTemplate in EventListener spec:
```
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      bindings:
        - name: pipeline-binding
          kind: ClusterTriggerBinding
      template:
        name: pipeline-template
```

If the user does not define `kind` field, it will by default assume TriggerBinding.

# Expected Behavior

`TriggerBinding should be reusable within cluster`

# Actual Behavior

`TriggerBinding is reusable within namespace`

/kind feature
/assign
