### ISSUE TITLE
Unable to use nested values in arrays in TriggerBinding

### ISSUE THREAD

**Issue by CSTDev** [tektoncd/triggers#347]
# Expected Behavior
Be able to access values of objects within arrays. I'm trying to get the branch name out of a Bitbucket webhook body. I'm able to get the value of $(body.push.changes) which is an array, but not any object within it. [see here for bitbucket spec](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push)

# Actual Behavior
Requested path is passed to the TriggerTemplate as a string, i.e. git tries to checkout a branch called "$(body.push.changes[0].new.name)"

# Steps to Reproduce the Problem

1. Create a TriggerBinding that is looking for a value within an object within an array:
```
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name:  bitbucket-binding
spec:
  params:
    - name: branch
      value: $(body.push.changes[0].new.name)
```
2. Use the *branch* parameter in a PipelineRun within a TriggerTemplate, as the Revision for the git resource
3. Invoke the trigger with a push to bitbucket (or resend a webhook)
