### ISSUE TITLE
CEL expressions in TriggerBindings

### ISSUE THREAD

**Issue by bigkevmcd** [tektoncd/triggers#367]
Being able apply functions to the hook bodies in the trigger bindings might be useful.

Perhaps prefixing the expressions?

I think this can probably mostly be done with the CEL interceptor (with the the overlays functionality) so this might be an easy way around this.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: my-trigger-binding
spec:
  params:
  - name: shortsha
    value: cel:(truncate(body.pull_request.head.ref, 8))
```
