### ISSUE TITLE
Embed TriggerBinding in EventListener triggers

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#371]
# Expected Behavior
I expect to be able to send static parameters to my TriggerTemplate without creating an extra TriggerBinding resource to define these parameters in.

# Actual Behavior
In v0.1.0, we had a `params` field in the EventListener:
```YAML
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
      - name: message
        value: Hello from the Triggers EventListener!
```
This field made it very easy for me to send static parameters to my TriggerTemplate. However, we removed it with the v0.2.0 release, because parameters were replaced with multiple TriggerBindings. So, now I must create a separate TriggerBinding resource with static parameters to use in my EventListener.
I expect to be able to define my static parameters in the EventListener. Having to create a separate TriggerBinding resource with my parameters is annoying.

I think that a nice solution to this problem is to implement the option to embed TriggerBindings in the EventListener. The implementation could be similar to how Tekton Pipelines handles embedding PipelineResources. They have a `resourceRef` or `resourceSpec` for each PipelineResource used in a TaskRun or PipelineRun ([more info here](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#providing-resources)). Similarly, we could have a `bindingRef` or `bindingSpec` for each TriggerBinding used in an EventListener.
