### ISSUE TITLE
Webhook interceptor fails to make a request to the service

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#373]
# Expected Behavior
The webhook interceptor should make a request to the configured service.

# Actual Behavior
I get the following error in the event listener pod:
```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:181","msg":"Post http://mario.mario.svc/: http: Request.RequestURI can't be set in client requests.","knative.dev/controller":"eventlistener","/triggers-eventid":"hgmvj","/trigger":"trigger","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.executeInterceptors\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:181\ngithub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:129\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:93"}
W0122 18:28:38.001660       1 reflector.go:256] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 39735951 (39737609)
```

# Steps to Reproduce the Problem

1. The event listener is connected to tektoncd/plumbing, it receives events on comments
2. Leave a comment to a PR (e.g. https://github.com/tektoncd/plumbing/pull/98)
3. The event listener tries to invoke the configured webhook interceptor, but nothing is written in the interceptor logs, and the error mentioned in this bug shows up in the event listener logs

# Additional Info

The event listener:
```
apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: EventListener
  metadata:
    name: mario-image-builder
    namespace: mario
  spec:
    serviceAccountName: mario-listener
    serviceType: LoadBalancer
    triggers:
    - bindings:
      - name: trigger-to-build-and-push-image
      interceptors:
      - webhook:
          objectRef:
            apiVersion: v1
            kind: Service
            name: mario
            namespace: mario
      name: trigger
      template:
        name: build-and-push-image
```
