### ISSUE TITLE
Interceptors receiving incorrect headers 

### ISSUE THREAD

**Issue by dibbles** [tektoncd/triggers#391]
# Expected Behavior

Having multiple triggers, each with one interceptor, which has a number of headers (note type is webhook).  I expect each trigger to be fired once with the correct set of headers on the request to the interceptor.

e.g this set of headers on each trigger but with different header values name1, name2, name3 etc..

```
      interceptors:
      - webhook:
          header:
          - name: Wext-Trigger-Name
            value: name1
          - name: Wext-Repository-Url
            value: foo
          - name: Wext-Incoming-Event
            value: pull_request, Merge Request Hook
          - name: Wext-Secret-Name
            value: bar
          - name: Wext-Incoming-Actions
            value: opened,reopened,synchronize
          objectRef:
            apiVersion: v1
            kind: Service
            name: tekton-webhooks-extension-validator
            namespace: tekton-pipelines
```

# Actual Behavior

What I see varies, but is usually a single request sent to the interceptor 3 times.  When I dump the incoming request as the first action in my HandleFunc the headers are the same on the 3 requests - thus my interceptor does not function as expected.

# Steps to Reproduce the Problem

1.  1 event listener, 3 triggers, 1 interceptor on each (same interceptor service)
2.  interceptor of type webhook with headers (same key different values)
3.  trigger webhook and dump your headers in the interceptor and note they are the same.

# Additional Info

I have added debug into ExecuteTrigger() in pkg.interceptor.webhook.go and sometimes I see headers post addInterceptorHeaders are incorrect ..... however even when they are correct I still seem to be able to receive 1 set of headers on 3 requests.
