### ISSUE TITLE
Combine GitLab and GitHub interceptors

### ISSUE THREAD

**Issue by bigkevmcd** [tektoncd/triggers#441]
# Expected Behavior

Instead of `GitHub` and `GitLab` interceptors being separate

```yaml
      interceptors:
        - github:
            secretRef:
              secretName: foo
              secretKey: bar
            eventTypes:
              - pull_request
```

Perhaps these could be simplified to a `GitWebhook` with type `github` or `gitlab`

This would make extending somewhat simpler:

And tidy this long validation line up:

https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_validation.go#L83

And make it easier to extend with Bitbucket, and other possible interceptors, while keeping the benefits of the strongly typed values, as opposed to...

```yaml
      interceptors:
        - type: github
          params:
             name: secretName
             value: foo
             name: secretKey
             value: bar
             name: eventTypes
             value:
               - pull_request
```
