### ISSUE TITLE
Labels on event listener break service selector

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#463]
# Expected Behavior
It should be possible to add custom labels on an event listener

# Actual Behavior
Label is set to the event listener:
```
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  annotations:
  labels:
    app: tekton.plumbing
(...)
```

Label is propagated to the service, and it's added to the service selector:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-28T12:19:38Z"
  labels:
    app: tekton.plumbing
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: label-sync-deployer
  name: el-label-sync-deployer
  namespace: default
spec:
  clusterIP: 10.121.2.219
  ports:
  - name: http-listener
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tekton.plumbing
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: label-sync-deployer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

However the label is not propagated to the pod:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
        event-listener'
    creationTimestamp: "2020-02-28T12:15:45Z"
    generateName: el-label-sync-deployer-8588df855-
    labels:
      app.kubernetes.io/managed-by: EventListener
      app.kubernetes.io/part-of: Triggers
      eventlistener: label-sync-deployer
      pod-template-hash: 8588df855
    name: el-label-sync-deployer-8588df855-p4wwp
```

Which causes the service selector to catch nothing.
I'm having this issue on triggers v0.2.1 - not sure if the issue has been fixed since.
