### ISSUE TITLE
How to set front-end port on EL Service

### ISSUE THREAD

**Issue by rlangfordBV** [tektoncd/triggers#473]
How do you actually set the front-end port for the service an EL creates?  I want to wire it up to an existing ingress controller.

I have this `EventListener`:
```
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
  namespace: mynamespace
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - name: foo-trig
      interceptors:
        - github:
            eventTypes:
              - pull_request
      bindings:
        - name: github-webhook-binding
      template:
        name: build-container-template
```

and the service config looks like:
```
spec:
  clusterIP: 100.64.195.249
  ports:
  - name: http-listener
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-listener-interceptor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

I'd like set `port` to something else.
