### ISSUE TITLE
Relax TriggerTemplate limitation of only creating Tekton resources

### ISSUE THREAD

**Issue by disposab1e** [tektoncd/triggers#482]
# Expected Behavior
It should be possible to create a PersistentVolumeClaim resource in TriggerTemplate `spec.resourcetemplates:`.
 
# Actual Behavior
Only Tekton resources are allowed.

# Steps to Reproduce the Problem

We would like to have a possibilty to dynamically create a PVC within TriggerTemplate.

 ``` yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-tt
  namespace: awesome-pipelines
spec:
  params:
  - name: pipelineName
    description: Pipeline Name (build, deploy, verify)    
 resourcetemplates:
 - apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: $(uid)
   spec:
     resources:
       requests:
         storage: 0.2Gi
     accessModes:
       - ReadWriteMany
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-
    spec:
      serviceAccountName: pipeline-sa
      pipelineRef:
        name: pipeline-$(params.pipelineName)
      workspaces:
      - name: pipeline-workspace
        persistentVolumeClaim:
          claimName: `$(uid)`
```

We don't think this will break any design decisions but can be very helpful in some dynamic scenarios. 

In this context we really miss "support" for workspace lifecycle management. For example cleaning up a workspace (and optional PVC) after:
- Success
- Error (support from [Error Handling](https://github.com/tektoncd/pipeline/issues/1684) and [Allowing for actions to be taken in failure scenarios](https://github.com/tektoncd/pipeline/issues/1376))
- Hooks (support from [Lifecycle Management](https://github.com/tektoncd/pipeline/issues/1460))
- House keeping #64 

We also follow the [Auto Workspaces](https://github.com/tektoncd/pipeline/issues/1986) discussion.

# Additional Info
This issue has its roots [here](https://github.com/tektoncd/triggers/issues/476).
