### ISSUE TITLE
Add Rego interceptor

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#484]
# Expected Behavior

In addition to supporting CEL for filtering and mutation of payloads, we can support other options out of the box, such as Rego.

# Actual Behavior

We only support CEL, tho folks can bring their own interceptors of course!

# Additional Info

To actually make this happen we should propose a design since there are a few ways we could express filtering + overlays with Rego.

[This is a POC of a Rego interceptor](https://github.com/tektoncd/triggers/compare/master...bobcatfish:rego_interceptor). It uses a `filter` query and an `overlay` query which provides the same functionality as [this example CEL interceptor](https://github.com/tektoncd/triggers/blob/0ea7560954be72b176b4ce199083404da4b9a0bb/examples/eventlisteners/cel-eventlistener-interceptor.yaml#L9-L14).

Preview of the rego syntax:

```yaml
  triggers:
    - name: rego-trig-with-matches
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: secret
        - rego:
            source: |
              package main
              default filter = false
              filter {
                input.header[k][i] == "pull_request"
                lower(k) == "x-github-event"
              }
              
              default overlay = {}
              overlay = {
                "extensions": {
                   "truncated_sha": substring(input.body.pull_request.head.sha, 0, 7),
                }
              }
      bindings:
      - name: rego-binding
      template:
        name: rego-trigger-template
```

[This yaml](https://github.com/bobcatfish/triggers/blob/8c74714382dc2f3610f60ea3e96a507882104a18/examples/eventlisteners/rego-eventlistener-interceptor.yaml) is an example that uses [the pullrequest task](https://github.com/tektoncd/catalog/tree/v1beta1-wip/pullrequest) to comment on a PR when it is opened.
