### ISSUE TITLE
Dynamic params sent from EventListener to PipelineRun

### ISSUE THREAD

**Issue by dalefwillis** [tektoncd/triggers#485]
# Expected Behavior

I'm sorry to spam issues with this but I'm not seeing any docs on this topic. First off - I love the idea of Tekton and the triggers project is a great addition. I was able to follow through the getting started guide and so I know I have the event listeners setup properly to do basic things.

What I'm attempting to do is to take the entire payload body from a github hookshot (caught by the EventListener) and pass this eventually into a Task - I have seen the examples of taking params and using those to setup the `gitrepositoryurl` which is later used as an input (`source-repo`) - however if I just want to take the body of a push request (to say get the list of commits and changed files) I don't see any docs on how to get that json content into the task.

I'm attempting this on the triggers release v0.3.1

I understand that the variable substitution would only take place in certain areas and that the variables would need to be available to the proper tekton components to make this work, so I apologize if I'm completely blowing up the intentions of how the EventListener to Pipeline to Task interaction was supposed to work ;).

- I looked at trying to leverage resources to feed this as an input but I'm using AWS so the only type that seemed appropriate was storage which I don't have access to (still GCP only correct?)
- I looked at some CEL interceptor examples that showed the use of `extensions.truncated_sha` but I couldn't find any examples or docs on what the end result of that was (how is this fed into the Pipeline) - also it failed for me in general when I tested it out.

# Actual Behavior

Unable to see dynamic param getting passed from TriggerTemplate to a PipelineRun without being first pulled into a resource.

# Steps to Reproduce the Problem

1. Follow getting started guide
2. Setup github hooks, then push update to repo

# Additional Info

My starting point with this was the getting started tutorial, here are the snippets simplified a bit to just show what I think is relevant (specifically targeting the `gitpayload` key below):

```
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cicd-pipelinebinding
  namespace: cicd
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: cicd
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: gitpayload
      value: "$(body)"
---

apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cicd-listener
  namespace: cicd
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - name: cicd-pipelinebinding
      template:
        name: cicd-triggertemplate
---

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cicd-triggertemplate
  namespace: cicd
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
    - name: gitpayload
      description: The git payload
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: cicd-pipeline-run-$(uid)
        namespace: $(params.namespace)
      spec:
        serviceAccountName: tekton-triggers-admin
        pipelineRef:
          name: cicd-pipeline
        params:
          - name: gitpayload
            value: "$(gitpayload)"
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(params.gitrevision)
              - name: url
                value: $(params.gitrepositoryurl)
```

Then for the pipeline:

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cicd-pipeline
  namespace: cicd
spec:
  params:
    - name: gitpayload
      description:
        The payload
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToContext
          value: /workspace/source-repo
        - name: gitpayload
          value: "$(params.gitpayload)"
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image
  namespace: cicd
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
    params:
      - name: pathToContext
        description:
          The build directory used by img
        default: /workspace/source-repo
      - name: gitpayload
        description:
          The git payload
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: debug-1
      image: ubuntu
      command:
        - /bin/bash
      args:
        - -c
        - |
          set -ex
          echo "${inputs.params.gitpayload}"

```

**Comment by ncskier** [comment]
Hello @dalefwillis, I'm a little unclear whether you're requesting a feature or having trouble getting the `$(body)` parameter to be sent to your Pipeline.

If it's the former, does this feature sound similar to what you're looking for? https://github.com/tektoncd/triggers/issues/87

If it's the latter, then this should illustrate how to send the `$(body)` of your event to a Task/Pipeline: 
```YAML
###
# Save this YAML as test.yaml
# Create the resources in this file:
# kubectl apply -f test.yaml
#
# Port-forward the EventListener pod:
# kubectl port-forward $(kubectl get pod -o=name -l eventlistener=test) 8080
#
# Send a request to the EventListener pod:
# curl -X POST http://localhost:8080 \
#   -d '{
# 	"hello":
# 	{
# 		"this": "is"
# 	},
# 	"a":
# 	{
# 		"test": "!"
# 	}
# }'
#
# View the triggered TaskRun (this command only works if you have the Tekton CLI installed):
# tkn tr logs test
###
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test
spec:
  params:
  - name: body
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      name: test
    spec:
      taskSpec:
        inputs:
          params:
          - name: body
        steps:
          - image: ubuntu
            script: |
              #! /bin/bash
              echo $(inputs.params.body)
      inputs:
        params:
        - name: body
          value: $(params.body)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: test
spec:
  params:
  - name: body
    value: $(body)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test
spec:
  triggers:
    - name: test
      bindings:
        - name: test
      template:
        name: test
```
(sorry for the long YAML snippet, I don't think GitHub allows attaching YAML files)

**Comment by dalefwillis** [comment]
Thanks for the response @ncskier - last question related to these kinds of dynamic params:

I can tell from the output the params are variable replaced using Go and when that happens if the variable being replaced is a json object Go just prints it out without regard for it being json - so for instance it would print `{test:object}` instead of `{"test": "object"}` which would cause something like this to break in a really funny way if you aren't paying attention to what is going on:

```
script: |
  #! /bin/bash
  apt-get update && apt-get install -y -q --no-install-recommends jq
  echo $(inputs.params.body) | jq
```

Others may not directly see that if `body` is a json object itself and they attempt to pass it outside of what the pipeline sets up they might run into trouble - if I find the time I would like to help contribute to documentation for some of these things (I know its an odd place that spans between the triggers and pipeline repos).

Also for anyone else looking at how you would do this for a PipelineRun instead of a TaskRun, here is an example (and pay attention to the fact that Triggers as of v0.3.1 doesn't support v1beta1 apiVersions for PipelineRuns just yet so as you translate the Pipeline spec you need to make sure you are using v1alpha1).

```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cicd-triggertemplate
  namespace: cicd
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
    - name: gitpayload
      description: The git payload
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: cicd-pipeline-run-$(uid)
        namespace: $(params.namespace)
      spec:
        serviceAccountName: tekton-triggers-admin
        pipelineSpec:
          params:
            - name: gitpayload
          tasks:
            - name: test
              taskSpec:
                inputs:
                  params:
                  - name: gitpayload
                steps:
                  - image: ubuntu
                    script: |
                      #! /bin/bash
                      echo $(inputs.params.gitpayload)
              params: 
              - name: gitpayload
                value: $(params.gitpayload)
        params: 
        - name: gitpayload
          value: $(params.gitpayload)
```

**Comment by ncskier** [comment]
> I can tell from the output the params are variable replaced using Go and when that happens if the variable being replaced is a json object Go just prints it out without regard for it being json - so for instance it would print {test:object} instead of {"test": "object"} which would cause something like this to break in a really funny way if you aren't paying attention to what is going on:

I think that's because my `echo` command in the Task didn't have single quotes. Using `echo '$(inputs.params.body)'` should return this:
```
{"a":{"test":"."},"hello":{"this":"is"}}
```

If you check the TaskRun resource with `kubectl get taskrun test -oyaml`, the parameter is being passed to the Task like this:
```YAML
params:
- name: body
  value: '{"a":{"test":"."},"hello":{"this":"is"}}'
```
However, one thing to note is that I think we're escaping the double quotes, so when you check the resource JSON, the parameter looks like this:
```JSON
"params": [
    {
        "name": "body",
        "value": "{\"a\":{\"test\":\".\"},\"hello\":{\"this\":\"is\"}}"
    }
],
```

Please let me know if this clears up the issue you're seeing with parameter substitution, or if there's something else that I'm missing 😄 

> if I find the time I would like to help contribute to documentation for some of these things

Thanks! It would be very helpful if you had the time to contribute some documentation. The Triggers & Tekton documentation definitely has room for improvement, so contributions would be quite valuable. As a reference, here's our documentation about contributing to the Triggers repo 👍  https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md.
