### ISSUE TITLE
Add Support For Naming Modifiers

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#50]
# Expected Behavior
Resources that are created by `TriggerTemplates` will clash if the names defined in the resources are static. Add some postfix/modifier (uuid/timestamp) to resources to prevent naming collisions.

Pipelines uses uuid's so it's probably best to follow that convention.

# Actual Behavior
Currently, nothing does this.

# Additional Info
If all resources get an automatic and unknown name modifier (like a postfix), it will be impossible to refer to them from within the `TriggerTemplate`. For this reason, it is important that the same mechanism that uniquely names resources also allows this (sort of uuid) to be exposed for usage throughout the `TriggerTemplate`.

This can be accomplished by exposing another interpolation variable within the `TriggerTemplate` or also extending the `TriggerTemplate` struct.

For example, a variable such as `${id}` (or any such name like `${unique}`) could be utilized throughout a `TriggerTemplate` as follows:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
  namespace: default
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source${id.one}
        namespace: ${params.namespace}
        labels:
            triggertemplated: true
      spec:
        type: git
        params:
        - name: revision
          value: ${params.gitrevision}
        - name: url
          value: ${params.gitrepositoryurl}
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: simple-pipeline-run${id.two}
        namespace: default
        labels:
            triggertemplated: true
      spec:
        pipelineRef:
            name: simple-pipeline
        trigger:
          type: event
        resources:
        - name: git-source
          resourceRef:
            name: git-source${id.one}
```
In this way, some interpolation base (like `${id}`) would have fields that could be implicitly referenced throughout the template (maybe as valid [here](https://github.com/tektoncd/triggers/blob/master/pkg/parse/validate.go#L17)). In any case, this is similar to how `${params}` is functioning.

To be more explicit, we could add another `TriggerTemplateSpec` field like Params where users would specify exactly what unique field names they want to expose. For example:
```
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  id:
    - idOne
    - idTwo
```
These are not functionally surfaced to the `TriggerBinding` however, so maybe creating explicit fields is annoying and verbosity isn't good/as valuable?

This could also be done in a similar way, but instead of providing access to some randomly generated variable that is used for naming, resources names could be automatically modified and resources themselves (which still functionally evaluates to their name) could have some identifier to be used within the template. Regarding the prior example, it could look something like this:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
  namespace: default
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source
        namespace: ${params.namespace}
        labels:
            triggertemplated: true
      spec:
        type: git
        params:
        - name: revision
          value: ${params.gitrevision}
        - name: url
          value: ${params.gitrepositoryurl}
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: simple-pipeline-run
        namespace: default
        labels:
            triggertemplated: true
      spec:
        pipelineRef:
            name: simple-pipeline
        trigger:
          type: event
        resources:
        - name: git-source
          resourceRef:
            name: ${1}
```

Documentation should DEFINITELY be included for this one. Discussion is good 😄

**Comment by vtereso** [comment]
Many ways to tackle this one 🤔, but discussion definitely necessary immediately after we have resource creation.

**Comment by ncskier** [comment]
I like your first approach 👍 
However, I don't really like that `${1}` in the second example, but something like this could be an alternative:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
  namespace: default
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
  - uniqueName: true
    template:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source
        namespace: ${params.namespace}
        labels:
            triggertemplated: true
      spec:
        type: git
        params:
        - name: revision
          value: ${params.gitrevision}
        - name: url
          value: ${params.gitrepositoryurl}
  - uniqueName: true
    template:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: simple-pipeline-run
        namespace: default
        labels:
            triggertemplated: true
      spec:
        pipelineRef:
            name: simple-pipeline
        trigger:
          type: event
        resources:
        - name: git-source
          resourceRef:
            name: ${name.git-source}
```
Or, to match your "verbose" example:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
  namespace: default
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
  - name:
    - unique: true
    - id: gitpr
    template:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source
        namespace: ${params.namespace}
        labels:
            triggertemplated: true
      spec:
        type: git
        params:
        - name: revision
          value: ${params.gitrevision}
        - name: url
          value: ${params.gitrepositoryurl}
  - uniqueName: true
    template:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: simple-pipeline-run
        namespace: default
        labels:
            triggertemplated: true
      spec:
        pipelineRef:
            name: simple-pipeline
        trigger:
          type: event
        resources:
        - name: git-source
          resourceRef:
            name: ${name.gitpr}
```
Here, `uniqueName: true` or `unique: true` would signal that we should append a `uuid` to the resource name.

**Comment by EliZucker** [comment]
Still trying to understand the full extent of this issue. Would this still be a problem if we removed any guarantees of resource creation order and forced people to use in-line resource definitions?

So you would have to do something like this example I took from a pipelines yaml:
```
    resources:
    - name: workspace
      resourceSpec:
        type: git
        params:
          - name: revision
            value: v0.32.0
          - name: url
            value: https://github.com/GoogleContainerTools/skaffold
```

**Comment by vtereso** [comment]
> Still trying to understand the full extent of this issue. Would this still be a problem if we removed any guarantees of resource creation order and forced people to use in-line resource definitions?

Right, I didn't really specify :sweat_smile:. If you want to create a `PipelineResource` and refer to it within a `PipelineRun`, it will need to know the identifier and since many events can come in, there has to be a system to uniquely name each.

**Comment by vtereso** [comment]
Also, I don't see why someone would create more than a few resources within these templates where it shouldn't be very costly to create resources in order. If some `TriggerTemplate` had two resources and one relies on the other, this was my understanding for why we would want to support this.

**Comment by vtereso** [comment]
@ncskier Made a good point that having an explicit field within the `TriggerBinding` to specify ordering on/off might be the best way to tackle this, but as a first pass, forced ordering is probably easiest.

**Comment by chhsia0** [comment]
For the first approach, there's probably no need to specify a unique name for each generated resource since within a `TriggerTemplate` there should already be no name conflict, so the resource names can be e.g., `$(uniqueNamePrefix)-git-source`, `$(uniqueNamePrefix)-simple-pipeline-run`, where `uniqueNamePrefix` can be made required to be assigned from a `TriggerBinding`. Some mechanism to make the resulting names follow the k8s requirements needs to be designed.

@ncskier's variant of the second approach looks nice. I'd like to suggest a small modification:
```
spec:
  params:
    ...
  outputs:
  - name: git-source
    resourceTemplate:
      apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        namespace: $(params.namespace)
        labels:
          triggertemplated: true
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
  - name: simple-pipeline-run
    resourceTemplate:
      metadata:
        name: simple-pipeline-run
        namespace: default
        labels:
          triggertemplated: true
      spec:
        pipelineRef:
          name: simple-pipeline
        trigger:
          type: event
        resources:
        - name: git-source
          resourceRef:
            name: ${outputs.git-source.name}
```
If there is no `name` field specified in `resourceTemplate.metadata`, then some unique naming generation kicks in; otherwise, the user clearly states that this template should use a static name. In either case, `$(outputs.git-source.name)` would be resolved to the resulting name.

**Comment by vtereso** [comment]
Interesting... IIUC, your suggestion is to allow for resource templates to be able to reference one another? Kubernetes already supports generated names if the name field is left empty where an interpolation variable allows you to reference the "unknown" generated name. This seemingly stipulates that the resources MUST be created in order since the the name couldn't be extracted otherwise. I am shying away from this because it makes it would appear like all fields could be interpolated where are seemingly we only care about naming.

**Comment by chhsia0** [comment]
Hmm good point on the field interpolation. Maybe simply `$(output.git-source)`?

If it's not preferred to enforce the resource generation order, then it looks a bit better if the naming contract is explicit in the resource template, like the first approach.

**Comment by chhsia0** [comment]
Another idea that is more close to the first approach and avoids ordering and resolving after resource generation:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
  namespace: default
spec:
  params:
  - name: gitrevision
  - name: gitrepositoryurl
  resources:
  - name: git-source
    apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - name: simple-pipeline-run
    apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    spec:
      pipelineRef:
        name: simple-pipeline
      trigger:
        type: event
      resources:
      - name: git-source
        resourceRef:
          name: $(outputs.git-source.name)
          namespace: $(output.git-source.namespace)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-pipeline-binding
  namespace: default
spec:
  templatebindings:
  - templateref:
      name: simple-pipeline-template
    params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
    resources:
    - name: git-source
      metadata:
        name: git-source-<uuid>
        namespace: default
    - name: simple-pipeline-run
      metadata:
        name: simple-pipeline-run-<uuid>
        namespace: default
```
The spirit is that, the "contents" of the generated resources are defined in the `TriggerTemplate`, but the "names" that are used to refer to the generated resources are specified when the `TriggerTemplate` is instantiated.

**Comment by akihikokuroda** [comment]
Can we introduce a predefined variable like $(pipelinerun) and replace the variables in the definitions with the uuid of the pipelinerun when the bindings and templates are used?

**Comment by chhsia0** [comment]
It seems that the conclusion of today's meeting is that we'll moving towards a solution that's similar to @vtereso's first proposal. For this direction, here's another potential proposal:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-pipeline-template
  namespace: default
spec:
  params:
  - name: gitrevision
  - name: gitrepositoryurl
  resources:
  - name: git-source
    template:
      apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        labels:
          triggertemplated: true
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
  - name: simple-pipeline-run
    template:
      apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        labels:
          triggertemplated: true
      spec:
        pipelineRef:
          name: simple-pipeline
        trigger:
          type: event
        resources:
        - name: git-source
          resourceRef:
            name: $(resources.git-source)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-pipeline-binding
  namespace: default
spec:
  templatebindings:
  - templateref:
      name: simple-pipeline-template
    params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
    resources:
    - name: git-source
      value: my-git-resource-bv1k5
    - name: simple-pipeline-run
      value: my-simple-pipeline-run-av3ck
```
Pros:
* The interpolation syntax is consistent with `params`.
* No need for user to put `metadata: name: git-source-$(id)` in the template.
* No implicit $(uuid)
Cons:
* The uniqueness must be handled by the user.
