### ISSUE TITLE
Confusing params syntax in trigger templates

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#508]
# Expected Behavior
`TriggerTemplates` allow defining a set of (Tekton) resources that should be provisioned.
`TriggerTemplates` expose parameters that can be injected into the resources using the `$(params.<param-name>)` syntax. The problem is that some of the resources that can be provisioned in `TriggerTemplates`  have their own parameters, and they can refer to them using the exact same syntax `$(params.<paramName>)`.

Resources that suffer from this issue are `TaskRuns` with a `taskSpec` embedded as `PipelineRuns` with a `pipelineSpec` embedded.

# Actual Behavior
It would be nice to have a way to distinguish parameters that come from the `TriggerTemplate`.
One way could be to prepend `tt` to params, e.g. `$(tt.params.<paramName>`.

# Steps to Reproduce the Problem

Example:
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: deploy-tekton-release
spec:
  params:
  - name: clusterResource
    description: Name of the cluster resource that points to the target cluster
  - name: targetCluster
    description: Name of the target cluster, used for the overlay
  - name: releaseBucket
    description: Base URL of the bucket where the release file is stored
    default: gs://tekton-releases
  - name: releaseFile
    description: Name of the release file
    default: release.yaml
  - name: releaseExtraPath
    description: Any extra path after bucket/project, starting with a "/"
    default: ""
  - name: tektonProject
    description: Name of the project to deploy (pipeline, triggers, dashboard)
  - name: tektonVersion
    description: Version of the project to deploy
  - name: namespace
    description: Target namespace. Not enforeced, for verification.
  - name: plumbingRepository
    description: URL of the repository that holds plumbing scripts
  - name: plumbingRevision
    description: Git revision of the repository that holds plumbing scripts
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: deploy-$(params.tektonProject)-release-$(params.targetCluster)-$(uid)
    spec:
      taskRef:
        name: install-tekton-release
      params:
      - name: projectName
        value: $(params.tektonProject)
      - name: namespace
        value: $(params.namespace)
      - name: version
        value: $(params.tektonVersion)
      - name: environment
        value: $(params.targetCluster)
      - name: release-file
        value: $(params.releaseFile)
      resources:
        inputs:
          - name: release-bucket
            resourceSpec:
              type: storage
              params:
              - name: type
                value: gcs
              - name: location
                value: $(params.releaseBucket)/$(params.tektonProject)$(params.releaseExtraPath)
              - name: dir
                value: "y"
          - name: k8s-cluster
            resourceRef:
              name: $(params.clusterResource)
          - name: plumbing-library
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(params.plumbingRevision)
              - name: url
                value: https://$(params.plumbingRepository)
```

# Additional Info
