### ISSUE TITLE
Can't use Pipeline level params with TriggerTemplate params

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#525]
# Expected Behavior

I should be able to use params from the TriggerTemplate inside of a resource template that contains a Pipeline spec which also has it's own params.

# Actual Behavior

Both TriggerTemplate params + Pipeline params are specified with `$(params.my-param)` and TriggerTemplates can't distinguish between them, meaning that when you try to use a pipeline level param, TriggerTemplates will complain that it does not recognize the param.

# Steps to Reproduce the Problem

For example if I try to make a TriggerTemplate similar to this, where the Pipeline has a param `$(params.bucket-name)` with a default value:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gcs-triggertemplate
spec:
  resourceTemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: gcs-pr-$(uid)
      spec:
        pipelineSpec:
          params: bucket-name
          default: tekton-test-bucket-$(uid)
          tasks:
          - name: some-task
            taskRef:
              name: some-task
            params:
            - name: location
              value: $(params.gcs-bucket)
```

Because there is no TriggerTemplate param `bucket-name` I'll get an error like this:
```
Error from server (BadRequest): error when creating "./gcs/samples/gcs-sample.yaml": admission webhook "validation.webhook.triggers.tekton.dev" denied the request
: validation failed: invalid value: undeclared param '$(params.bucket-name)': spec.resourcetemplates[0]
'$(params.bucket-name)' must be declared in spec.params
```

# Additional Info

Ideas for possible fixes:
* Don't try to catch unknown params (kind of sad for a user who mistypes a TriggerTemplate param but maybe worth it for the flexibility?)
* Change the syntax to be more explicit, either in TriggerTemplates, Pipelines or both (e.g. `triggertemplate.params.foo` and `pipeline.params.foo`)
* Add some kind of escaping syntax??

(discovered this with @sbwsg )

**Comment by dibyom** [comment]
Another possible solution might be the one suggested in #508 i.e. TriggerTemplate params use $(tt.params) vs $(params)

**Comment by bobcatfish** [comment]
Looks like I duplicated #508? feel free to close this! (I like the tt.params syntax btw)

**Comment by dibyom** [comment]
I think the solution is similar but this is technically a "different" bug 
/kind bug

**Comment by skaegi** [comment]
I have a similar problem where I am trying to add jsonpath support in the pipeline. My plan there is to follow what Kubernetes does and escape $ as $$. e.g. see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core

One really really important difference that I think we want to have is that Kubernetes container args use the rule "If a variable cannot be resolved, the reference in the input string will be unchanged. " A rule like this can "only" be used at the bottom-most layer of a templating system or chaos will reign and the darklord will destroy our world.

What this means is that @bobcatfish's trigger template should be written as...
```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gcs-triggertemplate
spec:
  resourceTemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: gcs-pr-$(uid)
      spec:
        pipelineSpec:
          params: bucket-name
          default: tekton-test-bucket-$(uid)
          tasks:
          - name: some-task
            taskRef:
              name: some-task
            params:
            - name: location
              value: $$(params.gcs-bucket)
``` 

@dibyom it also means that you might want to look at this regular expression and its use... https://github.com/tektoncd/pipeline/blob/master/pkg/jsonpath/expand.go#L32
