### ISSUE TITLE
Incorrect capitalization in fields treated differently b/w first creation + updates

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#526]
# Expected Behavior

When I make a change to a TriggerTemplate it should change!

# Actual Behavior

When I apply a TriggerTemplate and subsequently try to make changes to it, the changes are never reflected in the state of the TriggerTemplate! I have to delete the TriggerTemplate and re-apply it to see the change.

# Steps to Reproduce the Problem

1. Apply a Trigger template such as:

```yaml
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: unused-triggertemplate
spec:
  resourceTemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: sad-pr-$(uid)
    spec:
      pipelineSpec:
        tasks:
        - name: be-sad
          taskSpec:
            steps:
            - name: sad
              image: ubuntu
              script: |
                #/bin/bash
                set -ex
                echo "happy"
```

2. Make a change to the template and apply, e.g.:

```yaml
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: unused-triggertemplate
spec:
  resourceTemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: sad-pr-$(uid)
    spec:
      pipelineSpec:
        tasks:
        - name: be-sad
          taskSpec:
            steps:
            - name: sad
              image: ubuntu
              script: |
                #/bin/bash
                set -ex
                echo "preplexed or is it perplex"
```

3. Retrieve the TriggerTemplate with kubectl - and note that it still uses the first value (i.e. "happy" in the case above) but bizarrely the `last-applied-configuration` does reflect the values we tried to change (i.e. "perplexed" above), e.g:

```bash
k get triggertemplates -o yaml unused-triggertemplate
```

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"triggers.tekton.dev/v1alpha1","kind":"TriggerTemplate","metadata":{"annotations":{},"name":"unused-triggertemplate","namespace":"default"},"spec":{"resourceTemplates":[{"apiVersion":"tekton.dev/v1beta1","kind":"PipelineRun","metadata":{"name":"sad-pr-$(uid)"},"spec":{"pipelineSpec":{"tasks":[{"name":"be-sad","taskSpec":{"steps":[{"image":"ubuntu","name":"sad","script":"#/bin/bash\nset -ex\necho \"preplexed or is it perplex\"\n"}]}}]}}}]}}
  creationTimestamp: "2020-04-07T16:25:09Z"
  generation: 1
  name: unused-triggertemplate
  namespace: default
  resourceVersion: "20694699"
  selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/default/triggertemplates/unused-triggertemplate
  uid: 808ade7d-acc1-41f9-9f36-599e88b444f2
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: sad-pr-$(uid)
    spec:
      pipelineSpec:
        tasks:
        - name: be-sad
          taskSpec:
            steps:
            - image: ubuntu
              name: sad
              script: |
                #/bin/bash
                set -ex
                echo "happy"
```

Note that I am not even using an eventlistener or referring to `unused-triggertemplate` anywhere! At first I thought the event listener might be doing this but it's not involved at all afaik!

(I am using the latest triggers from HEAD https://github.com/tektoncd/triggers/commit/b44648c9bed0f8c55c1bef2217782f201b309974)

# Additional Info

My only guess for what could be causing this is a webhook? I'm kinda stumped tho!

Also this might be something I'm not understanding that I need to do differently and not a bug at all? However I haven't seen this behavior with any other CRDs so not sure!

**Comment by bobcatfish** [comment]
p.s. I thought this was just me until I paired with @sbwsg and he ran into it as well

**Comment by sbwsg** [comment]
Ah, interesting!  So... If I add a new _param_ to the trigger template then I see this update straight away after applying it.

However, if I rename a workspace (for example) in the resourceTemplate and apply it then that change ends up in the `kubectl.kubernetes.io/last-applied-configuration` JSON but does not appear in the `resourceTemplate` itself.

**Comment by bobcatfish** [comment]
This is wild! If I change a param and a resource template field at the same time, the param change takes and the resource template field only changes in the last-updated-configuration :O

@dibyom sounds like this makes sense to you somehow??

**Comment by dibyom** [comment]
My hunch is that it has something to do with just the resourceTemplates since they get stored as  "rawMessage"/"unstructured" unlike the regular fields

**Comment by dibyom** [comment]
probably related: https://github.com/kubernetes/kubernetes/issues/64612

**Comment by bobcatfish** [comment]
In the repro case we were using `resourceTemplates` instead of `resourcetemplates` 😅  Looks like if you create a CRD with a field having the wrong case, it gets automatically corrected, but apply afterward doesnt do that b/c it just generates a patch containing the field with the wrong capitalization which is then IGNORED X'D

It's possible that open API validation will help here, some related issues from pipeline:
* Request to add validation: https://github.com/tektoncd/pipeline/issues/1461
* PR to add the validation, https://github.com/tektoncd/pipeline/pull/1179 which made us concerned we'd have a mismatch between our validation + the schema
* WIP to generate this automatically https://github.com/tektoncd/pipeline/pull/1776

**Comment by bobcatfish** [comment]
@dibyom tried adding openapi validation, but it seemed to be ignored unless we disabled the webhook 😨

**Comment by sbwsg** [comment]
Wow, great sleuthing!

**Comment by dibyom** [comment]
Expanding on @bobcatfish 's comment above, here is what I tried:
*. Add openAPI schema validation to `config/300-triggertemplates.yaml`:
```
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - resourcetemplates
```
*. Applied the CRD and then tried to create a `TriggerTemplate` with a `resourceTemplates` field. This should have failed due to the above validation but did not i.e. the template got created. Interestingly, the if you get the tempalte, the field is now all lower-case `resourcetemplate`. 

* I removed our webooks by running ` k delete -f config/500-webhooks.yaml`. Now the apiSchema validation seemed to work and we cannot create the trigger template anymore: `spec.resourcetemplates in body is required`

I don't know enough about the webhooks workflow, but it seems like the knative webhook field name checks should be case sensitive?
 
(Also, @bobcatfish could repro this on Pipelines as well!)
