### ISSUE TITLE
Parsing JSON strings in CEL interceptors

### ISSUE THREAD

**Issue by jace-ys** [tektoncd/triggers#538]
# Expected Behavior

It will be really useful if we could parse JSON strings in CEL interceptors, when we get a payload containing a JSON string field.

# Actual Behavior

When my EventListener receives `deployment` webhooks from GitHub, that JSON object contains a payload field that's a JSON string (not sure why GitHub does this 😓). Example:

```yaml
{
  "action": "created",
  "deployment": {
    "url": "https://api.github.com/repos/Codertocat/Hello-World/deployments/145988746",
    "id": 145988746,
    "node_id": "MDEwOkRlcGxveW1lbnQxNDU5ODg3NDY=",
    "sha": "f95f852bd8fca8fcc58a9a2d6c842781e32a215e",
    "ref": "master",
    "task": "deploy",
    "payload": "{\"hello\": \"world\"}", # this JSON string
    "original_environment": "production",
    "environment": "production",
    ...
  }
}
```

I would ideally like to do something like this in my interceptor `body.deployment.payload.hello == 'world'` , but since payload isn't treated as an object, I have to do `body.deployment.payload == '{"hello": "world"}'` which isn't great once i have a larger payload field.

# Steps to Reproduce the Problem

1. Send the above webhook payload to an EventListener containing a field with a JSON string
2. Parse the `body.deployment.payload.hello == 'world'`
3. EventListener doesn't evaluate the above statement to true

# Additional Info
