### ISSUE TITLE
Define EventListener Status

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#54]
# Expected Behavior
When an EventListener resource is created, we expect its status section to have information about the resulting deployment and the endpoint this deployment can be reached at.

# Actual Behavior
The [event_listener_types.go](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go) file defines the EventListener resource to have an empty status section.

# Additional Info
@bobcatfish mentioned [here](https://github.com/tektoncd/triggers/pull/53#discussion_r309023062) that we can use the status section in our tests.

Please use this issue to discuss what information should go in the EventListener's status. We haven't discussed this yet, but I think that some relevant information we should consider includes the:
- EventListener's deployment
- Address for sending an http request to the EventListener's deployment
- [`duckv1beta1.Status`](https://godoc.org/github.com/knative/pkg/apis/duck/v1beta1#Status)

**Comment by vincent-pli** [comment]
I think the `status` should be like this:
```
  status:
    conditions:
    - lastTransitionTime: "2019-08-01T00:56:33Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2019-08-01T00:56:33Z"
      status: "True"
      type: ListenerReady
    - lastTransitionTime: "2019-08-01T00:56:33Z"
      status: "True"
      type: TriggerBindingProvided
    address:
      hostname: sample-eventListener.default.svc.cluster.local
      url: http://sample-eventListener.default.svc.cluster.local
```
Include:
- conditions (`duckv1beta1.Status`), include several `type`s
  + `TriggerBindingProvided`: means `TriggerBinding` is get and validated.
  + `ListenerReady`: `deployment` and `service` is created, i don't want to tell `deployment`, hide the implement details.
  + `Ready`: everything is ok
- `address`, this part is follow the `Addressable` definition (https://github.com/knative/eventing/blob/master/docs/spec/interfaces.md)
