### ISSUE TITLE
TriggerTemplate should have default values for the param type when it is empty

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#549]
# Expected Behavior
TriigerTemplate have [params](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_template_types.go#L48) in the spec and while creating if we doesn't specify [Type](https://github.com/tektoncd/triggers/blob/master/vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/param_types.go#L38) then Triggers Webhook should assign a default value which is **string**

# Actual Behavior
When provided params of `triggertemplate` doesn't have `Type` then Triggers are not assigning any default value

# Steps to Reproduce the Problem

1. Create a TriggerTemplate with yaml like below
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
```
2. Get the output of created `triggertemplate`
```
  resourceVersion: "127645"
  selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/default/triggertemplates/pipeline-template
  uid: 399b7696-0a90-4aaa-8efb-b53c47e3c584
spec:
  params:
  - default: master
    description: The git revision
    name: gitrevision
  - description: The git repository url
    name: gitrepositoryurl
```
No default values for the Type

# Additional Info
1. If we have a default value for the **Type** it will be useful for the `tkn tt desc` so that we can remove this [condition](https://github.com/tektoncd/cli/pull/928/files#diff-1accda1e24c18eb696c75b318cfb1cd6R49) 
2. It will be in consistence with the other pipeline resources like `Task` `ClusterTask` etc... for these resources if we don't give `Type` Value it will take default as `string`
