### ISSUE TITLE
TriggerTemplate default value is not applied if the param is missing from Binding

### ISSUE THREAD

**Issue by lqy1992** [tektoncd/triggers#568]
### [Summary](https://github.com/tektoncd/triggers/issues/568#issuecomment-648838427):

> I've been hitting this issue as well - it seems that if an omitted field in the JSON payload is used in a TriggerBinding, we error out before even reaching the code that merges in default values from our TriggerTemplate. It works fine as long as the field is present, even if it's a zero value like an empty string.
> 
> The relevant bit of code I could find: https://github.com/tektoncd/triggers/blob/master/pkg/template/event.go#L36-L41
> Here we exit with a JSONPath error, thus never reaching MergeInDefaultParams.
> 
> One way to solve this, would be to attempt to merge in our default params even when encountering a JSONPath error (field is missing) and finally return the error if no default is provided and the binding value can't be resolved.

triggers-binding.yaml
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggers-nodejs-app-binding
spec:
  params:
  **- name: replicaset
    value: $(header.replicaset)**
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: dockerTag
    value: $(body.dockertag.version)
  - name: imageurl
    value: $(body.dockerhub.url)
```
triggertemplate.yaml
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template-nodejs-app
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: dockerTag
    default: latest
  **- name: replicaset
    default: "2"**
  - name: imageurl
    description: url of docker hub
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: nodejs-app-elrun
    spec:
      pipelineRef:
        name: nodejs-app-pipeline
      serviceAccountName: tekton-pipelines-controller
      params:
      - name: dockerTag
        value: $(params.dockerTag)
      - name: replicaset
        value: $(params.replicaset)
      resources:
      - name: mygit
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.gitrevision)
          - name: url
            value: $(params.gitrepositoryurl)
      - name: myimage
        resourceSpec:
          type: image
          params:
          - name: url
            value: $(params.imageurl)
```
when i dont set replaceset
curl -X POST \
  http://192.168.5.73:30318/ \
  -d '{
	"head_commit":
	{
		"id": "master"
	},
	"repository":
	{
		"url": "https://github.com/tekton-nodejs-demo.git"
	},
	"dockertag":
	{
       	"version": "latest"
	},
	"dockerhub":
	{
	    "url": "xxxx/nodejs-demo"
	}
}'

error:
failed to ApplyEventValuesToParams: failed to replace JSONPath value for param replicaset: {string $(header.replicaset) []}: Replicaset is not found","knative.dev/controller":"eventlistener","/

# Expected Behavior
Why do I need to define a replicaset?I think, When I do n’t pass a parameter to replicaset, get it from the default value "2"
# Actual Behavior
Error can't run

**Comment by dibyom** [comment]
from looking at the example, this should work
/kind bug

**Comment by lqy1992** [comment]
You can easily pass this example test
https://github.com/tektoncd/triggers/tree/master/examples

kubectl apply -f role-resources/secret.yaml
kubectl apply -f role-resources/serviceaccount.yaml
kubectl apply -f role-resources/triggerbinding-roles
kubectl apply -f triggertemplates/triggertemplate.yaml
kubectl apply -f triggerbindings/triggerbinding.yaml
kubectl apply -f triggerbindings/triggerbinding-message.yaml
kubectl apply -f eventlisteners/eventlistener.yaml


if we don't pass head_commit,id can't work

curl -X POST \
  http://localhost:8080 \
  -H 'Content-Type: application/json' \
  -H 'X-Hub-Signature: sha1=2da37dcb9404ff17b714ee7a505c384758ddeb7b' \
  -d '{
	**"head_commit":
	{
		"id": "master"
	},**
	"repository":
	{
		"url": "https://github.com/tektoncd/triggers.git"
	}
}'


but i see  git gitrevision has default value master,i think it should be work

**Comment by savitaashture** [comment]
@dibyom 
The issue which i mentioned during  WG  discussion is not exactly same the one mentioned here

**Issue:**
Use of same `TriggerBinding` to the `EventListener` gives below error
```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:164","msg":"failed to ApplyEventValuesToParams: failed to replace JSONPath value for param branch: {string $(body.extensions.branch_name) []}: branch_name is not found","knative.dev/controller":"eventlistener","/triggers-eventid":"wssnr","/trigger":"cel-trig-with-matches","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:164\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:97"}
```

**TriggerBinding yaml**
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)
    - name: branch
      value: $(body.extensions.branch_name)
    - name: sha
      value: $(body.extensions.truncated_sha)
```

**EventListener Yaml**
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cel-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  serviceType: NodePort
  #serviceAccountName: pipeline
  triggers:
    - name: cel-trig-with-matches
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event', 'pull_request')"
            overlays:
              - key: extensions.truncated_sha
                expression: "body.pull_request.head.sha"
      bindings:
        - name: pipeline-binding
      template:
        name: pipeline-template
    - name: cel-trig-with-canonical
      interceptors:
        - cel:
            filter: "header.canonical('X-GitHub-Event') == 'push'"
            overlays:
              - key: extensions.branch_name
                expression: "split(body.ref, '/')[2]"
      bindings:
        - name: pipeline-binding
      template:
        name: pipeline-template
```

As mentioned above used same **TriggerBinding** for multiple Triggers in the **EventListener**
In the first trigger of `EventListener` there is no info of branch and it directly failes with the below error
```
failed to replace JSONPath value for param branch: {string $(body.extensions.branch_name)
```

So this way we will not be able to make use of same **TriggerBinding**  at multiple place
