### ISSUE TITLE
Triggers with interceptors no longer work after a certain number is reached

### ISSUE THREAD

**Issue by ghfalcon7** [tektoncd/triggers#570]
When adding multiple triggers **with interceptors** to the same event listener, I noticed that all triggers work fine until I add a ninth trigger with interceptors, all the old triggers still work but the ninth doesn't get triggered although it's configured in the same way as the others. Here is definition of the event listener I used:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: team-operation
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: app-wsk-generator
      interceptors:
        - github:
            secretRef:
              secretName: wsk
              secretKey: wsk      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"
      bindings:
        - name: pipeline-binding
      template:
        name: wsk-generator-triggertemplate
    - name: app-distancecalculator
      interceptors:
        - github:
            secretRef:
              secretName: github
              secretKey: foo      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"      
      bindings:
        - name: pipeline-binding
      template:
        name: app-distancecalculator-triggertemplate
    - name: app-install-fe
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: appinstallfe      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"      
      bindings:
        - name: pipeline-binding
      template:
        name: app-install-fe-triggertemplate
    - name: app-planif-fe
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: appplaniffe      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"      
      bindings:
        - name: pipeline-binding
      template:
        name: app-planif-fe-triggertemplate
    - name: app-install-be
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: appinstallbe      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"      
      bindings:
        - name: pipeline-binding
      template:
        name: app-install-be-triggertemplate
    - name: app-planif-be
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: appplanifbe      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"
      bindings:
        - name: pipeline-binding
      template:
        name: app-planif-be-triggertemplate
    - name: ptl-admin
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: ptladmin      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"      
      bindings:
        - name: pipeline-binding
      template:
        name: ptl-admin-triggertemplate
    - name: gatewayapi
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: apigw      
        - cel:
            overlays:
            - key: extensions.branch_name
              expression: "split(body.ref, '/')[2]"      
      bindings:
        - name: pipeline-binding
      template:
        name: gatewayapi-triggertemplate
```
