### ISSUE TITLE
Cannot use same TriggerBinding with the multiple Triggers for CEL interceptors

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#573]
**Issue:**
As discussed in WG call issue is
Can not use same **TriggerBinding** to the multiple **Triggers** if `TriggerBinding` containes params for those interceptors

**TriggerBinding yaml**
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)
    - name: branch
      value: $(body.extensions.branch_name)
    - name: sha
      value: $(body.extensions.truncated_sha)
```
**EventListener Yaml**

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cel-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  serviceType: NodePort
  #serviceAccountName: pipeline
  triggers:
    - name: cel-trig-with-matches
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event', 'pull_request')"
            overlays:
              - key: extensions.truncated_sha
                expression: "body.pull_request.head.sha"
      bindings:
        - name: pipeline-binding
      template:
        name: pipeline-template
    - name: cel-trig-with-canonical
      interceptors:
        - cel:
            filter: "header.canonical('X-GitHub-Event') == 'push'"
            overlays:
              - key: extensions.branch_name
                expression: "split(body.ref, '/')[2]"
      bindings:
        - name: pipeline-binding
      template:
        name: pipeline-template
```

Same `TriggerBinding` **pipeline-binding** used in a multiple Triggers of the EventListener

In the first trigger of EventListener there is no info of **branch** and it directly fails with the below error
```
failed to replace JSONPath value for param branch: {string $(body.extensions.branch_name) []}: branch_name is not found
```

So this way we will not be able to make use of same **TriggerBinding** for multiple Interceptors
