### ISSUE TITLE
One more breaking change for 0.5.0 release notes

### ISSUE THREAD

**Issue by estei** [tektoncd/triggers#577]
# Expected Behavior

Straightforward update for EventListeners
This worked in 0.4.0
```
      bindings:
        - name: event-binding
        - name: other-binding
```

# Actual Behavior

We are now required to have either an inline `spec` or a `ref:`
https://github.com/tektoncd/triggers/blob/454c8e0151f188288ae98c44688bbd0c8a182e25/pkg/apis/triggers/v1alpha1/event_listener_validation.go#L49-L52

Above need to be changed to:

```
      bindings:
        - name: event-binding
          ref:  event-binding
        - name: other-binding
          ref:  other-binding
```

The need for `ref` in bindings is not mentioned in the [prerelease for 0.5.0](https://github.com/tektoncd/triggers/releases/tag/v0.5.0) 

It is a small thing, but I think it would make the update experience a bit better for people if it was mentioned in the Breaking changes.
The rest of the documentation seems to have been updated.
