### ISSUE TITLE
Unable to create EventListener with Github Interceptor

### ISSUE THREAD

**Issue by davissp14** [tektoncd/triggers#581]
# Expected Behavior
Create an EventListener with a Github interceptor.  

# Actual Behavior
Fails to create EventListener with the following error:
```
Error from server (BadRequest): error when creating "triggers/event_listener.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "eventTypes"
```

# Steps to Reproduce the Problem
Create an 0.4.0 EventListener while specifying a github interceptor and specific eventTypes.
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-listener
  namespace: pipeline
spec:
  triggers:
    - name: push-build-and-deploy
      interceptors:
        - github:
          secretRef:
            secretName: webhook-secret
            secretKey: secretKey
          eventTypes: ["push"]
      bindings:
        - name: pipeline-triggerbinding
      template:
        name: pipeline-triggertemplate
  serviceAccountName: pipeline
```
 

# Additional Info
* IBM Cloud - IKS
* Kubernetes 1.15.11
