### ISSUE TITLE
Upgrading to Triggers 0.5 from 0.4 errors if you used type: in a TT's params

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/triggers#583]
# Expected Behavior
I expected the upgrade from Triggers 0.4 to Triggers 0.5 to not require this, or to mention this in the release notes

# Actual Behavior
As part of https://github.com/tektoncd/experimental/issues/547 I noticed the problem and the solution is to delete all references to type: for all parameters in my TriggerTemplate, and to delete any existing TriggerTemplates

**My guess is, you can have one small TriggerTemplate using type: on Triggers 0.4, then try to apply the same one on Triggers 0.5, and you'd see the error.**

# Steps to Reproduce the Problem

1. An easy way to get existing Trigger Templates against Triggers 0.4 is to install the Webhooks Extension, or to simply have a template with plenty of type: values specified for params, e.g.:

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: monitor-task-template
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
spec:
  params:
  - name: pullrequesturl
    description: The pull request url
    type: string <-- like this
```
2. Then install Triggers 0.5
3. git clone https://github.com/tektoncd/experimental.git 
4. cd webhooks-extension
5. kubectl apply -f 400-monitor-triggertemplate.yaml 
6. observe error
7. now remove type: for all of the params (keeping only type: pullRequest later)
8. now delete the existing TriggerTemplates
9. apply 400-monitor-triggertemplate.yaml  again and observe the error
 
# Additional Info
There's probably a much easier reproduce than this but it's the use case I'm particularly interested in, I'll handle things on the extension side but wondering if we want a 0.5.1 release or to call this out in the release notes?
