### ISSUE TITLE
Support OpenID Connect authentication and authorization with OpenPolicyAgent

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/triggers#610]
# Expected Behavior

That I can use OpenID Connect authenticated request sent to the Trigger. And that I can check authorization using the OpenPolicyAgent.

# Actual Behavior

Only SSH-keypair or a predefined password/credential/Secret can be used as authentication and authorization.

# Additional Info

**Authentication**

Common types of authentication:
* SSH key pair (typically generated on developers computer and then **distributed to both** GitRepoProvider and TektonTrigger)
* Preconfigured password/credential/secret (typical generated on GitRepoProvider and then **distributed** to TektonTrigger) e.g. Personal Token?
* OpenID Connect / JWT-token (no key distribution needed, but only configure authorization). This is the typical web-app authentication, and also newer Kubernetes ServiceAccount format.

Examples of OpenID Connect authentication is [Azure Active Directory](https://azure.microsoft.com/sv-se/services/active-directory/), [Sign in with Google / Google Accounts](https://developers.google.com/identity/protocols/oauth2/openid-connect), [Sign in with Apple](https://developer.apple.com/sign-in-with-apple/), [Keycloak](https://www.keycloak.org/), [RedHat Single Sign-on](https://access.redhat.com/products/red-hat-single-sign-on). E.g. typically requests from web-apps, e.g. a dashboard.

Also Kubernetes [Bounded Service Account - newer, rotated tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) is on OpenID Connect format with [discovery endpoint coming in 1.18](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery).

E.g. an upcoming, not yet existing GitRepoProvider would probably support modern OIDC serviceAccounts. E.g. It can be a provider that runs on Kubernetes (e.g. GitLab) and use the **new** Kubernetes ServiceAccounts for this.

**Use cases**

* the "potentially upcoming GitRepoProvider" above is a use case
* Having a Build-Pipeline in Cluster X, that trigger a Deploy-Pipeline in Cluster Y (e.g. deploying same image to clusters in multiple regions). This can be done with a curl-Task, or CloudEvent-Task, using Kubernetes ServiceAccount.
* Requests from an web-app, e.g. a dashboard

**Authorization**

[OpenPolicyAgent](https://github.com/open-policy-agent/opa) is an increasingly popular tool to "externalize authorization" - e.g. for [everything](https://www.openpolicyagent.org/docs/latest/ecosystem/) within an organization, e.g. [Http API authZ](https://www.openpolicyagent.org/docs/latest/http-api-authorization/), Kafka and other systems with a single authorization language.

This can be used for [validating JWT tokens (e.g. OpenID Connect)](https://www.openpolicyagent.org/docs/latest/http-api-authorization/#8-optional-use-json-web-tokens-to-communicate-policy-data) and also do [authorization](https://www.openpolicyagent.org/docs/latest/http-api-authorization/#2-load-a-policy-into-opa) e.g. if this "API-key" or JWT-token has access to this pipeline.

**Final note**

On a final note, I _think_ the above can be solved by using Istio, that "inject" an [opa istio sidecar](https://github.com/open-policy-agent/opa-istio-plugin). But I would like to be able to use this also without Istio, e.g. for triggering things with CloudEvents that is authenticated with a Kubernetes ServiceAccount.

**Example Curl Task**

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: curl
spec:
  params:
  - name: url
    type: string
  steps:
  - name: curl
    image: curlimages/curl
    script: "cat /var/run/secrets/tokens/token | xargs -I {} curl -X POST -H \"Authorization: Bearer {}\" $(params.url)"
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: token-volume

```

and TaskRun

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: curl-request-
spec:
  taskRef:
    name: curl
  params:
  - name: url
    value: http://tekton-trigger.my-namespace
  podTemplate:
    securityContext:
      supplementalGroups: [ 65534 ]
      fsGroup: 65534
    volumes:
    - name: token-volume
      projected:
        sources:
        - serviceAccountToken:
            path: token
            expirationSeconds: 7200
            audience: tekton-trigger
```

**Example Deployment OPA sidecar**

OPA can be used as a proxy in-front of a service, e.g. using Istio. Or as a sidecar that the **Trigger** asks (http-request) if the "event" is authorized. In a `Deployment`

```
    spec:
      containers:
      - name: tekton-trigger
        image: tekton-trigger-image
        env:
          - name: OPA_ADDR
            value: http://localhost:8181
          - name: POLICY_PATH
            value: /v1/data/httpapi/authz
      - name: opa
        image: openpolicyagent/opa
        args:
          - run
          - --server
          - --ignore=.*
          - --log-format=json-pretty
          - --set=decision_logs.console=true
          - "/policies"
        volumeMounts:
        - name: policy-volume
          mountPath: /policies
          readOnly: true
      volumes:
      - name: policy-volume
        configMap:
          name: example-policy
```

Also a possible solution for e.g. https://github.com/tektoncd/triggers/issues/572

/kind feature
