### ISSUE TITLE
More concise embedded TriggerBindings

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#617]
# Expected Behavior
A trigger binding consists of name and value pairs. So, when we embed it we should be able to use something like:

```
 bindings:
    - ref: my-cool-binding # this one is a ref to an existing binding

    - name: commit_id # embedded binding
      value: "$(body.head_commit_id)

    - name: message # embedded binding with static values
      value: "Hello from an embedded binding"
```

# Actual Behavior
Today, the above example looks like:
```
 bindings:
        - ref: my-cool-binding # this one is a ref to an existing binding
       
        -  name: some-name
           spec:
              params:
                - name: commit_id # embedded binding
                  value: "$(body.head_commit_id)
                - name: message # embedded binding with static values
                  value: "Hello from an embedded binding"
```

# Additional Info

From: https://github.com/tektoncd/triggers/pull/548/files#r417024864
/kind feature
