### ISSUE TITLE
Feature: TriggerTemplate ObjectMeta templating

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#618]
/kind feature

# Idea 

Make it easy to apply common ObjectMeta attributes to all TriggerTemplate resources consistently without needing to modify the underlying Pipeline/Task resource(s).

## Proposal

Add `ObjectMeta` to `TriggerTemplateSpec`, e.g.

```go
type TriggerTemplateSpec struct {
  // +optional
  metav1.ObjectMeta `json:"metadata,omitempty"`
  ...
}
```

### Apply labels to pipelines

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  metadata:
    labels:
      repo: $(params.repo)
      pr: $(params.pr_num)
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run-
    spec:
      pipelineRef:
        name: simple-pipeline
```

Would label all resources with `repo` and `pr` labels. This is useful for providing filtering criteria for the dashboard.

/cc @k 

### Apply consistent generateName prefix to created resources

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  metadata:
    generateName: trigger-
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run-
    spec:
      pipelineRef:
        name: simple-pipeline
```

Would result in a the created resource `trigger-simple-pipeline-run-xxxx`.
