### ISSUE TITLE
0.5.0: CEL header expressions case-sensitivity inconsistency

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/triggers#621]
Using 0.5.0

I have this in a interceptor

```
    - name: my-build-v1-interceptor
      interceptors:
        - cel:
            filter: "header.match('x-my-pipeline-version', 'v1')"  
        - cel:
            overlays:
              - key: intercepted.cicdContext
                expression: "header['x-my-pipeline-version'][0]"
```

the filter works fine, but the expression on the header does not, errors with

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:145","msg":"failed to evaluate overlay expression 'header['x-my-pipeline-version'][0]': no such key: x-my-pipeline-version","knative.dev/controller":"eventlistener","/triggers-eventid":"wnsvr","/trigger":"my-build-v1-interceptor","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:145\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:93"}                
```

When I change the expression to `header['X-My-Pipeline-Version'][0]` then it works

The header handling should be case-insensitive, or if it is case-sensitive, it should match on same casing that is in the actual request headers
