### ISSUE TITLE
Limit EventListener trigger to master branch

### ISSUE THREAD

**Issue by TomaszKlosinski** [tektoncd/triggers#630]
Hello,

I have a EventListener like this one:
```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-eventlistener-listener
  namespace: tekton-pipelines
spec:
  triggers:
    - name: tekton-eventlistener-listener-trigger-1
      serviceAccountName: tekton-triggers-admin
      interceptors:
        - github:
            eventTypes: ["pull_request"]
      bindings:
        - name: tekton-eventlistener-pipelinebinding
      template:
        name: tekton-eventlistener-triggertemplate
```

How can I limit this to trigger a pipeline run only on master branch?

Thanks in advance!

**Comment by TomaszKlosinski** [comment]
OK, I figured it out:
```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-eventlistener-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: tekton-eventlistener-listener-trigger-1
      interceptors:
        - cel:
            filter: >-
              (header.match('X-GitHub-Event', 'push') && body.ref.startsWith('refs/heads/master'))
      bindings:
        - name: tekton-eventlistener-pipelinebinding
      template:
        name: tekton-eventlistener-triggertemplate
```
