### ISSUE TITLE
Using map in CEL panics the eventlistener

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/triggers#651]
# Expected Behavior

I can use `map` as defined in the language spec (see [here](https://github.com/google/cel-spec/blob/master/doc/langdef.md)).

# Actual Behavior

It panics (used in the interceptor of an eventlistener at least)

# Steps to Reproduce the Problem

The event json is a GitHub payload, `body.pull_request.labels` is a list with a `map` in, and that map contains `name`. The goal is to create a new "field" `extensions.safe_labels` that contains a list of label name (from `body.pull_request.labels`)

1. Use the following interceptor

```
        - cel:
            overlays:
            - key: extensions.safe_labels
              expression: body.pull_request.labels.map(s, s['name'])
```

2. See the eventlistener panic on events

# Additional Info

/kind bug
/assign @bigkevmcd
