### ISSUE TITLE
Escape incoming data

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/triggers#675]
# Expected Behavior
Incoming data parsed by trigger binding should be escaped so that it's not possible to execute injection attack.

In my example below, I expect to see
`Hello Pavol && echo I was here on $(date +%F) and I can do whatever I want!`

# Actual Behavior

```
$ tkn tr logs --last -f
[greet] Hello Pavol
[greet] I was here on 2020-07-10 and I can do whatever I want!
```

# Steps to Reproduce the Problem

1. deploy the following reproducer
```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello 
spec:
  params:
    - name: NAME
      default: World 
  steps:
    - name: greet
      image: fedora:32 
      script: |
        #!/bin/bash
        echo Hello $(params.NAME)!
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: hello 
spec:
  params:
  - name: NAME 
    value: $(body.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: hello
spec:
  params:
  - name: NAME
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: hello-tr-
    spec:
      taskRef:
        name: hello
      params:
      - name: NAME
        value: $(params.NAME)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: hello
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: hello
    template:
      name: hello
```
2. expose the event listerner, e.g. `oc expose svc el-hello`
3. make a request... `curl -X POST -i 'http://el-hello.mycluster.com/' --data '{"name":"Pavol && echo I was here on $(date +%F) and I can do whatever I want"}'

# Additional Info

There is basically the same problem when not using triggers at all but only plain taskrun/pipelinerun but IMHO in that case the risk of misuse/attack is quite limited.

**Comment by dibyom** [comment]
Thanks for the detailed report. Like you already mentioned, technically the issue is with Pipelines though using Triggers increases the risk. 

One idea would be to escape anything in `$()` from event bodies. Another would be for Pipelines to add some kind of escaping? On the other end of the spectrum, we could keep the behavior as is, and warn users about such potential misuse. Thoughts @gabemontero @vdemeester @wlynch ?

**Comment by gabemontero** [comment]
Minimally something to definitely highlight up top in the documentation, in both pipeline and trigger projects.  And yes, as @dibyom noted here and as myself and others have noted in WG calls or other issues, security around event injection into triggers could use bolstering.  We've done a few things in the space, but more is desirable.

Some thoughts from a Pod security perspective (when it is enabled) ... i.e. best practices to employ with triggers and pipelines:
- Restrictions on which user ID the container runs under will prevent "harmful" commands from succeeding 
- as would Restrictions on the pod privilege and escalate to privileged settings 
- as would Restrictions of volume mounting (i.e. access to the host file system), host network, host namespace, will also insulate what the command you can invoke can do

Some thoughts from an authentication perspective
- https://github.com/tektoncd/triggers/issues/610 would help serve as protection against this
- especially in the context of triggers, for as @dibyom noted, triggers widens the exposure

Some thoughts from a "granularity" perspective
- the existing trigger level SA I did a while back,
- as well as the multi tenant EL, triggers as CRDs, etc.
- will allow for isolation of places where we might want current behavior 

On that last point, presumably, there is/are scenario(s) where being able to take advantage of bash substitution exists.

I'll defer to those who have been on the tekton project(s) longer than I to confirm/deny.

But if so, any escaping at the pipeline or trigger level would need some sort of on/off control,  where administrators can then choose to employ isolation/security measures like the ones noted above as a way to mitigate these valid security concerns.

**Comment by dibyom** [comment]
> I'll defer to those who have been on the tekton project(s) longer than I to confirm/deny.

> But if so, any escaping at the pipeline or trigger level would need some sort of on/off control, where administrators can then choose to employ isolation/security measures like the ones noted above as a way to mitigate these valid security concerns.

Yeah while escaping might be the correct behavior from a security standpoint, I think we do have use cases we'd want this behavior. So, I'm not sure if want to escape always either. /cc @sbwsg @bobcatfish

**Comment by bigkevmcd** [comment]
I've implemented a couple of different approaches here https://github.com/tektoncd/pipeline/compare/master...bigkevmcd:escape-strings-in-script

One would escape everything in the `Script` element of the Task, the other would would require more explicit (using `#()`) escaping.

**Comment by bigkevmcd** [comment]
I'll summarise the options as I see them:

On the triggers side:

- Manual escaping (add a CEL function, perhaps `shellEscape()` on strings)
- Automated escaping of data in TemplateBindings?

On the pipeline side:

- Explicit manual escaping perhaps something like `#(params.name)` instead of `$(params.name)`
- Automatic escaping of all params in here https://github.com/tektoncd/pipeline/blob/master/pkg/substitution/substitution.go#L120
- Only automatic escaping of params inside Scripts, perhaps by calling something like `ApplyEscapedReplacements ` in https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1beta1/step_replacements.go#L23
- Automatic escaping of params inside Script, but with optional "don't escape this param" with `$()` but `#()` meaning "don't escape this parameter.

There are probably some other options I've not thought of.

**Comment by wlynch** [comment]
@bigkevmcd SGTM. 

My 2c is we should lean towards being more secure by default here and only allow unescaping if opted in if possible. My expectation is that most users (myself included) would use the `$()` behavior by default, and only be burned when the input changes to something unexpected. That said, we should weigh this against the difficulty of dealing with escaping (e.g. perhaps this is something we can just document).

Given a binding:
```yaml
- name: foo
  value: ";${}"
```

and a template:
```yaml
params:
- name: foo
  value: $(tt.params.foo)
```

If the resulting request is:
```yaml
params:
- name: foo
  value: ';${}'
```
This should be relatively similar behavior to triggers today, and should protect against any direct `script` injections. It would then be up to Pipelines to make sure that these params are handled properly.

Consequences I can think of:
1. You would no longer be able to do things like:
```yaml
params:
- $(tt.params.foo): bar
  value: baz
```
 I'm not sure if that's actually something we want to support anyway. (I remember talking about this in a triggers issue before, but I can't seem to find it - will update if/when I find it).
2. This could break existing template replacements that require a non-string value (not sure how common this is though).
