### ISSUE TITLE
TriggerTemplates Allow PipelineRun with taskRef to be Created

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/triggers#678]
# Expected Behavior

An error message stating that a PipelineRun has no field `taskRef`, preventing the creation of the invalid TriggerTemplate, such as what happens when an invalid PipelineRun is created:

```
Error from server (BadRequest): error when creating "pr.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "taskRef"
```

# Actual Behavior

TriggerTemplate is created with a PipelineRun that has a `taskRef` property. There doesn't appear to be validation of resourcetemplates for this case.

# Steps to Reproduce the Problem

1. Create the following TriggerTemplate:

```yaml
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-run-
      spec:
        taskRef:
          name: buildpacks-knative
        params:
        - name: BUILDER_IMAGE
          value: gcr.io/paketo-buildpacks/builder:base
        - name: SOURCE_SUBPATH
          value: spring-petclinic-jdbc
        resources:
        - name: source
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.gitrevision)
            - name: url
              value: $(tt.params.gitrepositoryurl)
        - name: image
          resourceRef:
            name: petclinic-image
        serviceAccountName: triggers-sa
```

# Additional Info

Triggers version: `0.6.0`

**Comment by dibyom** [comment]
Yeah, one issue here is that resourceTemplates are hard to validate since they are not fully formed resources i.e. the value of the task/pipelineRef can be $(params.whatever) which will fail the validation.

That being said, there is probably some partial validation we can do here. Perhaps fill in default values for params if supplied? and replace other params with random strings and call validate?

The other thing to work out here is if we want to call the Validate method in the controller itself or simply call the webhook (with dryrun set to true).  The former is easier but we'd have to be careful -- we can validate using one version of pipelines when a different version of pipelines is actually installed in the cluster.

**Comment by praveen4g0** [comment]
I see similar issue with `pipelineRef` too.

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:266","msg":"problem creating obj: &errors.errorString{s:\"couldn't create resource with group version kind \\\"tekton.dev/v1beta1, Resource=pipelineruns\\\": admission webhook \\\"webhook.pipeline.tekton.dev\\\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \\\"pipelineRef\\\"\"}"
```

Steps to Reproduce:

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
	generateName: s2i-go-run
      spec:
        params:
        - name: GIT_URL
          value: $(tt.params.gitrepositoryurl)
        - name: GIT_REVISION
          value: $(tt.params.gitrevision)
	pipelineRef:
	  name: s2i-go-pipeline
	workspaces:
	- name: source
	  persistentvolumeclaim:
	    claimName: shared-pvc
```

Triggers version: v0.8.1
