### ISSUE TITLE
Handle validation for replicas

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#716]
Now User can specify replicas information using eventlistener as part of [spec](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go#L58) 

Following are few observation:
1. No validation for the replicas and user can set any negative value (ex: -1)
2. No replicas specified as part of spec But still EL will have below data after the creation
```
spec:
  podTemplate: {}
  replicas: 0
  serviceAccountName: tekton-triggers-github-sa
``` 
and EventListener pod will be UP and Running and which may lead confusion to the user .

# Expected Behavior

1. User shouldn't be allowed to provide `replicas` as negative number if provided it should give below error
```
Error from server (BadRequest): error when creating "examples/github/github-eventlistener-interceptor.yaml": admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: invalid value: -1: spec.replicas
```
2. Created EL shouldn't show replicas field if user don't specify as part of Eventlistener yaml
i mean this one
```
spec:
  podTemplate: {}
  replicas: 0
  serviceAccountName: tekton-triggers-github-sa
``` 
So EL after creation should contain `replicas` only if it specified as part of eventlistener yaml
