### ISSUE TITLE
Validation for special characters for eventlistener cel filters

### ISSUE THREAD

**Issue by sravankumar777** [tektoncd/triggers#746]
# Expected Behavior
Event listener object should be validated with extra special characters.

# Actual Behavior
Event listener is created, even with extra special characters. Error message was provided only during the webhook event reaches to event listener. 

# Steps to Reproduce the Problem

1. Deploy latest release of tekton-pipelines & tekton-triggers on local environment(kind cluster)
2. Create a test namespace on the kind cluster.
3. Create eventlistener provided in the below yaml.
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-event-listener
  namespace: tekton-test
spec:
  serviceAccountName: default
  triggers:
    - name: test-bitbucket-pr-comment
      interceptors:
        - cel:
            filter: body.eventKey == 'pr:comment:added' && body.comment.text == 'ok-to-test')
      bindings:
        - ref: test-pipeline-binding
      template:
        name: test-pipeline-template
```

# Additional Info
Deployed tektoncd/pipelines v0.15.1 & tektoncd/triggers v0.7.0 on kind cluster, for this test. 

Slack Conversation: 
https://tektoncd.slack.com/archives/CKUSJ2A5D/p1599486079009700
