### ISSUE TITLE
I wish to customize the pipeline name

### ISSUE THREAD

**Issue by vvvsrx** [tektoncd/triggers#759]
# Expected Behavior
I hope to get a custom generateName, such as: `dss-$(tt.params.name)-$(uid)`

# Actual Behavior
But the `tt.params.name` I got has capital letters.

# Additional Info
``` yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-dotnet-standard-service
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitRef
    - name: triggerUser
    - name: event
    - name: gitlabProjectID
    - name: name
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: dss-$(tt.params.name)-$(uid)
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: pipeline-dotnet-standard-service
        serviceAccountName: robot-git-ssh-ls6s
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.gitrevision)
                - name: url
                  value: $(tt.params.gitrepositoryurl)
        params:
          - name: gitrevision
            value: $(tt.params.gitrevision)
          - name: gitrepositoryurl
            value: $(tt.params.gitrepositoryurl)
          - name: gitRef
            value: $(tt.params.gitRef)
          - name: triggerUser
            value: $(tt.params.triggerUser)
          - name: event
            value: $(tt.params.event)
          - name: gitlabProjectID
            value: $(tt.params.gitlabProjectID)
          - name: name
            value: $(tt.params.name)
```

What should I do? I checked the cel-go extensions, and there is no way to adapt?
