### ISSUE TITLE
Removing Triggers from Cluster with kubectl delete -f Does Not Remove EventListeners

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/triggers#775]
# Expected Behavior

Using `kubectl delete -f https://storage.googleapis.com/tekton-releases/triggers/previous/<TRIGGERS_VERSION>/release.yaml` should remove the triggers component from a Kubernetes cluster and all associated triggers resources.

# Actual Behavior

If an EventListener is installed on the cluster, the `kubectl delete` command will hang until timing out as shown below:

```
kubectl delete -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.8.1/release.yaml
podsecuritypolicy.policy "tekton-triggers" deleted
clusterrole.rbac.authorization.k8s.io "tekton-triggers-admin" deleted
serviceaccount "tekton-triggers-controller" deleted
clusterrolebinding.rbac.authorization.k8s.io "tekton-triggers-controller-admin" deleted
customresourcedefinition.apiextensions.k8s.io "clustertriggerbindings.triggers.tekton.dev" deleted
customresourcedefinition.apiextensions.k8s.io "eventlisteners.triggers.tekton.dev" deleted
customresourcedefinition.apiextensions.k8s.io "triggers.triggers.tekton.dev" deleted
customresourcedefinition.apiextensions.k8s.io "triggerbindings.triggers.tekton.dev" deleted
customresourcedefinition.apiextensions.k8s.io "triggertemplates.triggers.tekton.dev" deleted
secret "triggers-webhook-certs" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "validation.webhook.triggers.tekton.dev" deleted
mutatingwebhookconfiguration.admissionregistration.k8s.io "webhook.triggers.tekton.dev" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "config.webhook.triggers.tekton.dev" deleted
clusterrole.rbac.authorization.k8s.io "tekton-triggers-aggregate-edit" deleted
clusterrole.rbac.authorization.k8s.io "tekton-triggers-aggregate-view" deleted
configmap "config-logging-triggers" deleted
configmap "config-observability-triggers" deleted
service "tekton-triggers-controller" deleted
deployment.apps "tekton-triggers-controller" deleted
service "tekton-triggers-webhook" deleted
deployment.apps "tekton-triggers-webhook" deleted
```

The EventListener never appears to be deleted.

# Steps to Reproduce the Problem

1. Install triggers (Using v0.8.1)
2. Create an EventListener ( kubectl apply -f https://raw.githubusercontent.com/tektoncd/triggers/b6d0aac0992f7cb0fb28c129d6f41b2bbcbbd2c7/examples/github/github-eventlistener-interceptor.yaml)
3. Run `kubectl delete -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.8.1/release.yaml`

/kind bug

**Comment by dibyom** [comment]
Interesting....I think this might have something to do with the finalizer that we have for deleting the EL's logging config maps. The flow I think is:
1. When you delete a CRD, it will delete all instances of the CRD (EL in this case)

2. The EL objects have a `finalizer` specified, which means the `deletionTimestamp` field is set when we make a delete call.
 
3. The finalizer is supposed to notice the `deletionTimestamp` field is set, do whatever it needs to (i.e. delete the configmap), and then unset the `finalizer` field. Then, when `deletionTimestamp` is set and no `finalizers` are set on the resource, it is deleted.

 In our case, the finalizer is running in the controller deployment, and the controller pod is already deleted when we delete using  `kubectl delete -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.8.1/release.yaml`. So, the `finalizer` is never removed from the EL which blocks the EL delete which in turn blocks the EventListener CRD from being deleted, leading to `kubectl` hanging until timeout.


Workaround would be to delete the Listeners first `kubectl delete el --all` and then run the command.

**Comment by dibyom** [comment]
The other workaround would be to manually remove the finalizers.
` kubectl patch crd/eventlisteners.triggers.tekton.dev -p '{"metadata":{"finalizers":[]}}' --type=merge`

Wonder if knative has run into this at all? /cc @n3wscott

**Comment by savitaashture** [comment]
@dibyom when we apply above workaround `eventlistener` CRD deleted along with `kind: EventListener` CR 

But the `Deployment` which have `ownerReferences` as `EventListener`
```
ownerReferences:
    - apiVersion: triggers.tekton.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: EventListener
      name: github-listener-interceptor
      uid: a5bb2a5b-5135-48a7-a205-8de0ef3960e2
```
exist as it is which results `pod` also in running state

But as per GC rule if `ownerReferences` deletes then respective `resources` also should delete right

**Comment by dibyom** [comment]
Yeah, that's very strange. Let me try to replicate this on my setup.

**Comment by savitaashture** [comment]
* Created EL
* deleted Triggers using `kubectl delete -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.8.1/release.yaml`
* Ran `kubectl patch crd/eventlisteners.triggers.tekton.dev -p '{"metadata":{"finalizers":[]}}' --type=merge`

* EL CRD and CR got deleted but corresponding deployment exist

**Comment by savitaashture** [comment]
I tried to set `foregroundDeletion` in eventlistener `finalizer`
by referring this 
https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L315
and it works
means respective Deployment and pods are deleted

**Comment by dibyom** [comment]
At the WG today, we discussed adding the `foregrounddeletion` finalizer by default using a mutating admission webhook.

**Comment by dibyom** [comment]
Looks like foreground deletion support for kubectl got merged: https://github.com/kubernetes/kubernetes/pull/93384

But looks like we'll have to wait till 1.20 for it to be released which is supposed to be in December.

Once we have that, running the `kubectl delete --cascade=foreground ...` should fix our issues.

**Comment by dibyom** [comment]
/remove-lifecycle stale 
This should be possible now. Need to verify

**Comment by dibyom** [comment]
Was trying to verify this but failed to upgrade my minikube setup to k8s v.1.20

**Comment by jmcshane** [comment]
I just tested this with kind on a v1.20 cluster. Created a file:

```yaml
# eventlistener.yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-trigger-sa
  serviceType: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-trigger-sa
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tektoncd-triggers-github-binding
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: tekton-trigger-sa
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-trigger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-trigger-sa
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-aggregate-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-trigger-aggregate-view
subjects:
- kind: ServiceAccount
  name: tekton-trigger-sa
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-aggregate-view
```

Ran the following commands with kind 0.10 (kubernetes v1.20.2) to install triggers:
```bash
$ kind create cluster
$ kubectl create ns tekton-pipelines
$ kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.11.1/release.yaml
$ kubectl apply -f eventlistener.yaml
```

Validate the pods are up and running:

```bash
$ kubectl get pods -n tekton-pipelines
```

Then, ran the following command to delete triggers:

```bash
$ kubectl delete --cascade=foreground -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.11.1/release.yaml
```

The command completed successfully (after all pods were deleted) and the eventlistener was removed.
