### ISSUE TITLE
Can I set params dynamically use CEL interceptor?

### ISSUE THREAD

**Issue by win5do** [tektoncd/triggers#776]
Expected: 
```yaml
triggers:
  - name: foo
    interceptors:
      - cel:
          overlays:
            - key: custom.namespace
              expression: |
                // NOTE: This is not CEL grammar, it's Golang.
                if body.branch == "develop":
                  return "xxx"
                else if body.branch == "test":
                  return "yyy"
                else:
                  return "zzz"
```
Please note that I used **Golang** grammar because I didn’t find CEL's `if ... else if ... if ...` or `switch` example. 

It is difficult for me to derive grammar from [cel-spec](https://github.com/google/cel-spec/blob/master/doc/langdef.md).

If it can be achieved, please add some examples in the docs, thank you very much.

------

I know that another solution is to implement interceptors by writing an http server and expose it through k8s svc.
