### ISSUE TITLE
Support for triggering multiple pipelines from same EventListener

### ISSUE THREAD

**Issue by hprateek43** [tektoncd/triggers#801]
We are trying to migrate from Argo to TektonCD and are facing some implementation issues around Triggers. Argo allowed to deploy one Sensor and trigger multiple workflows through it based one event type. Can we do something similar with Tekton? I went thought the documentation and found a 1:1 relation between event listeners, triggertemplate and PipelineRuns.

**Comment by AlanGreene** [comment]
The `resourcetemplates` field of the TriggerTemplate accepts a list of resources to create. You can specify multiple PipelineRuns in that list if you wish, for example:

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: multi-pipeline-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline1-run-
    spec:
      pipelineRef:
        name: pipeline1
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline2-run-
    spec:
      pipelineRef:
        name: pipeline2
```
