### ISSUE TITLE
Invalid X-GitLab-Token

### ISSUE THREAD

**Issue by ddy4633** [tektoncd/triggers#813]
# Expected Behavior

Error : "msg": "Invalid X-GitLab-Token",

# Actual Behavior

- "trigger image": "gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.9.1

```json
This is TriggerEventlistener Error
{
	"level": "error",
	"logger": "eventlistener",
	"caller": "sink/sink.go:163",
	"msg": "Invalid X-GitLab-Token",
	"knative.dev/controller": "eventlistener",
	"/triggers-eventid": "895m6",
	"/trigger": "trigger",
	"stacktrace": "github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:163\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:95"
}
```
- my secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  secretToken: "1234567"
```

- my test:

```sh
curl -v -X POST \
  http://el-gitlab-listener-wenhook.default.svc.cluster.local:8080 \
  -H 'Content-Type: application/json' \
  -H 'X-GitLab-Token: 1234567' \
  -H 'X-Gitlab-Event: Push Hook' \
  -d '{
	"project":
	{
		"name": "test-demo"
	}
    "total_commits_count" : "2"
}'
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by bigkevmcd** [comment]
Based on reading https://github.com/tektoncd/triggers/blob/master/pkg/interceptors/interceptors.go#L79

Can you try...

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
data:
  secretToken: "1234567"
```
I suspect it's an error in the example.
