### ISSUE TITLE
Refer ResourceTemplates code by git url instead of writing code directly in the TriggerTemplates

### ISSUE THREAD

**Issue by LWZ55** [tektoncd/triggers#831]
### Feature request

For resourceTemplates in triggerTemplates, we don't want to write the resourceTemplate directly in the yaml. We can put that content in the github.Then we specify the git url to get different resourceTemplate.

### Use case
Details as follow:
The following is TriggerTemplate.However the resourceTemplate is written directly.

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-pipelinerun
spec:
  params:
  - name: revision-git
    default: master
# we want to replace it with git url: start
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: autogenerated-pipeline-run-
    spec:
      pipelineRef:
        name: pipeline-testcase
      resources:
      - name: git-resource
        resourceSpec:
          type: git
          params:
          - name: revision-git
            value: $(tt.params.revision-git)
# end
```

Then we want to replace the commented code with the git url which stores the corresponding code.
 
The scene is widespread,for example: we can write template in the github, which is convenient to maintain.
