### ISSUE TITLE
v0.10.0: github $(body.head_commit.modified): couldn't unmarshal json: invalid character

### ISSUE THREAD

**Issue by r0bj** [tektoncd/triggers#845]
# Expected Behavior

Event is handled without errors, it worked in v0.9.1.

# Actual Behavior

When trying to parse github webhooks, fields like `$(body.head_commit.modified)`, `$(body.head_commit. added)`, `$(body.head_commit.removed)` error message is generated.

JSON input looks like this:
```
  "head_commit": {
    "modified": [
      "test-image1/Dockerfile"
    ]
  }
```

Error log:
```
{"level":"info","logger":"eventlistener","caller":"sink/sink.go:237","msg":"ResolvedParams : [{Name:git-modified Value:[\"test-image1/Dockerfile\"]} {Name:git-added Value:[]} {Name:git-removed Value:[]}]","knative.dev/controller":"eventlistener","/triggers-eventid":"2f4fd","/trigger":"build-images"}
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:352","msg":"problem creating obj: &errors.errorString{s:\"couldn't unmarshal json: invalid character 't' after object key:value pair\"}","knative.dev/controller":"eventlistener","/triggers-eventid":"2f4fd","/trigger":"build-images","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.CreateResources\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:352\ngithub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:239\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:128"}
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:240","msg":"couldn't unmarshal json: invalid character 't' after object key:value pair","knative.dev/controller":"eventlistener","/triggers-eventid":"2f4fd","/trigger":"build-images","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:240\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:128"}
```

Adding annotation `triggers.tekton.dev/old-escape-quotes: "true"` helps in this case. However since you are going to deprecate and eventually delete this annotation, how we can handle binding those github webhook JSON object fields?

# Steps to Reproduce the Problem

1. Create a binding to a JSON Object $(body.head_commit.modified) from github webhook
2. Trigger the Eventlistener
3. Observe the Log

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.14.0
Pipeline version: v0.18.1
Triggers version: v0.10.0
```

**Comment by dibyom** [comment]
We added a new CEL function called `marshalJSON` that will be in the v0.11 release that should help with this (correct me if I'm wrong @bigkevmcd )

**Comment by bigkevmcd** [comment]
This is exactly what `marshalJSON` solves, it would quote the list correctly and insert it as a string, which can be decoded by a step in a task.

**Comment by r0bj** [comment]
So right now my `EventListener` uses github interceptor, and looks similar to this:
```
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-images
spec:
  params:
  - name: git-modified
    value: $(body.head_commit.modified)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-images-push
spec:
  triggers:
  - name: build-images
    interceptors:
    - github:
        secretRef:
          secretName: github-webhook-secret
          secretKey: github-secret
        eventTypes:
        - push
    bindings:
    - ref: build-images
    template:
      name: build-images
```

In order to keep using field `$(body.head_commit.modified)` (after annotation `triggers.tekton.dev/old-escape-quotes: "true"` is removed) do I need to replace github interceptor for CEL Interceptor?

**Comment by abhinavkhanna-sf** [comment]
> We added a new CEL function called `marshalJSON` that will be in the v0.11 release that should help with this (correct me if I'm wrong @bigkevmcd )
> 
> See #842
@dibyom 
I am seeing this issue in 0.11.2 as well. is it resolved?

**Comment by jmcshane** [comment]
@abhinavkhanna-sf you will need to update your trigger and binding in order to take advantage of the marshalJSON function. Try this:

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-images
spec:
  params:
  - name: git-modified
    value: $(extensions.git-modified)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-images-push
spec:
  triggers:
  - name: build-images
    interceptors:
    - github:
        secretRef:
          secretName: github-webhook-secret
          secretKey: github-secret
        eventTypes:
        - push
    - cel:
       overlays:
       - key: extensions.git-modified
          value: body.head_commit.modified.marshalJSON()
    bindings:
    - ref: build-images
    template:
      name: build-images
```
