### ISSUE TITLE
Add more generic HMAC validation

### ISSUE THREAD

**Issue by bigkevmcd** [tektoncd/triggers#856]
### Feature request

We support GitHub and GitLab's SHA-based signatures for incoming webhooks, but being able to trust Webhooks is important as they can come from anywhere.

I'd like to be able to do something like provide a header/algorithm (sha1/sha256 etc)/secret/key combination, and use that to validate received bodies.

```
      interceptors:
        - hmac:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            header: X-Signature
            algorithm: sha1 (defaults to sha1)?
```
