### ISSUE TITLE
Support for dynamic params to TriggerTemplates beyond just event values

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#87]
# Expected Behavior

It should (maybe!) be possible for users to provide values to `TriggerTemplate` from sources other than events

# Actual Behavior

A [TriggerTemplate](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md) takes parameters, and doesn't need to worry about where those come from e.g.:

```yaml
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
```

At the moment these values can be provided only by a [TriggerBinding](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md) which can extract them from json data (an event):

```yaml
spec:
  params: # side note - are these outputs? i think thats the intention...
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
    - name: namespace
      value: tekton-pipelines
```

There is no other way to provide values for the params of a `TriggerTemplate`.

# Steps to Reproduce the Problem

For dogfooding Tekton Pipelines, I wanted to make use of this the Pipeline we have been using for manual releases. However the Pipeline takes a parameter called `versionTag`:

https://github.com/tektoncd/pipeline/blob/3950521325d4744760a96c18e3d0c67d86495af3/tekton/publish.yaml#L14-L15

```yaml
    - name: versionTag
      description: The vX.Y.Z version that the artifacts should be tagged with (including `v`)
```

There are different types of values we want for this:

- When we are creating [official releases](https://docs.google.com/document/d/1BE9E2NkkvnZHdpX4F8ofBG-Uwd07bzx5cPoHSP67qmo/edit), we want to be able to extract the version from a combo of the name of the branch (e.g. `v0.4`) and number of commits so far (i.e. each subsequent commit bumps the patch value, e.g. `v0.4.1`)
- When we create nightly releases, we want to generate the version tag based on the date and the commit we are building from (e.g. ` vYYYYMMDD-commitsha`)

With the current implementation for Triggers (and Prow!), in order to accomplish the above, we need to modify the Pipeline itself to do this. And we'd need either 2 totally different Pipelines or a flag to distinguish between the official + nightly use cases.

My opinion is that it's reasonable to create a Pipeline like this that takes a version parameter without being concerned with how to create it, and I think it makes sense for the Triggering system to be able to make this data available.

# Additional info

Here is a proposal for how we could do this:

1. `TriggerBinding` would specifically be about extracting values from Events only, so it could be renamed (#62) to something like `EventParser` or `ParmsFromEvent` or something better but specifcally about "events" - `EventBinding`?
2. We could provide an interface (you guessed it, a container!) for users to provide additional parameters.

E.g. EventListener could look like this:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: default
  triggers:
    - bindings:
        - name: github-binding
        - name: nightly-version-binding 
      template:
        name: pipeline-template
```

`nightly-version-binding` would be an instance of at type called something like `ParamBinding` that is a container specification  - the interface would be something like the container has to write a json file to an expected location with the values it exports, e.g. something like:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: ParamBinding
metadata:
  name: nightly-version-binding
spec:
  outputs:
   - "versionTag"
  container:
  - name: generate-release-version
    image: alpine/git
    workingDir: "/workspace/go/src/github.com/bobcatfish/catservice/"
    command:
    - /bin/sh
    args:
    - -ce
    - |
      set -e
      set -x

      COMMIT=$(git rev-parse HEAD | cut -c 1-10)
      DATE=$(date +"%Y%m%d")
      VERSION_TAG="$DATE-$COMMIT"

      echo "{'versionTag': '$VERSION_TAG'}" > "/builder/home/outputs.json"
```

3. In the future, we could even extend this to support cases like filtering! For example @wlynch has been looking into use cases where we need additional info from github to make a decision, e.g. "is the user who opened the PR a member of the organziation". We could use something like this to provide inputs to the filtering logic.

4. And this could be extended to allow for caching info - to continue the use case from (3), say we wanted to know if the user who opened the PR is a member of the org - we could have a mechanism that is caching data like this from GitHub.

What I like about (3) and (4) is that it make it possible to separate the responsibilities of obtaining data from the responsibility of acting on that data.

**Comment by wlynch** [comment]
I like it!

Might be a noob questions, but would we need to explicitly list all fields in `outputs`? It seems like it would be great if we could treat the output of the step similar to the `event` in TriggerTemplates.

e.g. for the examples you gave above, being able to reference the ParamBinding in the TriggerBinding: 
```
spec:
  params: # side note - are these outputs? i think thats the intention...
    - name: version
      value: $(event.head_commit.id)
    - name: version
      value: $(nightly-version-binding.versionTag)
```

For filtering, this may not solve all problems since we might want to make some bindings conditional (e.g. don't call out to GitHub to check membership if we don't even care about the repo).
