### ISSUE TITLE
#761 would this behavior applies to CEL overlays too?

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/triggers#890]
**Kind:** Question

* #761 (apply triggertemplate param default value if body/header based triggerbinding param missing from body/header)

eg: 
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: example-with-multiple-overlays
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
      bindings:
      - name: sha
        value: $(extensions.truncated_sha)
      - name: branch
        value: $(extensions.branch_name)
      template:
        spec:
          params:
            - name: sha
            - name: branch
              default: master
          resourceTemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: TaskRun
              metadata:
                generateName: cel-trig-
              spec:
                taskSpec:
                  steps:
                  - image: ubuntu
                    script: |
                      #!/usr/bin/env bash
                      echo "SHA is : $(tt.params.sha). Branch is $(tt.params.branch)"
```  

what happens when user hit sink url, with a payload, where body doesn't contains field `ref` ?

### Actual:
* It ends up with below error
```
"level":"info","ts":"2021-01-07T12:06:26.168Z","logger":"eventlistener","caller":"sink/sink.go:215","msg":"interceptor stopped trigger processing: %!w(*status.Error=&{0xc000979620})","knative.dev/controller":"eventlistener","/triggers-eventid":"757sq","/trigger":"cel-trig"}
```
### Expected:

* Trigger template should get default value (master), or at least with some appropriate error log.

### Environment Details:
```
tkn version
Client version: 0.13.1
Pipeline version: v0.19.0
Triggers version: v0.10.2
```
