### ISSUE TITLE
Idea: consider 0 as valid value for EventListener replicas

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/triggers#892]
Hi,

I´m trying to replace the deployments created by EventListener with Knative Services to enable scale to zero. I´m aware of https://github.com/tektoncd/community/blob/master/teps/0008-support-knative-service-for-triggers-eventlistener-pod.md and think this is a great long term solution. Until this is fully implemented: what are your thoughts of considering 0 as a valid value for the field replicas of EventListener? With this I could create EventListeners with replicas=0 and therefore prevent the pod from running all the time and instead manually create an additional Knative Service to cover the functionality instead.

Thanks, Fabian

**Comment by dibyom** [comment]
> Until this is fully implemented: what are your thoughts of considering 0 as a valid value for the field replicas of EventListener? With this I could create EventListeners with replicas=0 and therefore prevent the pod from running all the time and instead manually create an additional Knative Service to cover the functionality instead.

Hmm interesting idea...Are you manually creating a Knative Service using the EventListener sink image? 

I'm guessing we only need the EventListener because we fetch the EventListener to get the list of triggers to process...I wonder if there is a way we could refactor that code so that you could just pass it a list of triggers.

also /cc @savitaashture for timeline on Knative EventListener implementation.

**Comment by Fabian-K** [comment]
Yes, exactly! I only did a quick test so far but the following service definition seems to work (almost a 1:1 copy of the deployment)

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${name}-ksvc
  namespace: ${namespace}
spec:
  template:
    spec:
      containers:
        - args:
            - --el-name=${name}
            - --el-namespace=${namespace}
            - --port=8080
            - --readtimeout=5
            - --writetimeout=40
            - --idletimeout=120
            - --timeouthandler=30
            - --is-multi-ns=false
            - --tls-cert=
            - --tls-key=
          env:
            - name: SYSTEM_NAMESPACE
              value: ${namespace}
          image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.10.2@sha256:1a91b57e5007ad6f524c2157cf83bdef97743bcc06a50c73ace8f48d9055fc7c
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
      serviceAccountName: tekton-triggers-listener
      volumes:
        - configMap:
            defaultMode: 420
            name: config-logging-triggers
          name: config-logging

```
