### ISSUE TITLE
Question: How to set default value for an array type parameter in TriggerTemplate

### ISSUE THREAD

**Issue by Thearas** [tektoncd/triggers#893]
Here is my `Pipeline`:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example
spec:
  params:
  - name: MESSAGES
    type: array
    default:
    - foo
    - bar
  tasks:
  ...
```
I want to extract the `MESSAGES` from HTTP body:
```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: example
spec:
  triggers:
  - name: example
    bindings:
    - name: MESSAGES
      value: $(body.MESSAGES)
    template:
      spec:
        params:
        - name: MESSAGES
          default:
          - foo1
          - bar1
        resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: example-
          spec:
            params:
            - name: MESSAGES
              value: $(tt.params.MESSAGES)
            pipelineRef:
            ...
```
Got an error when I applied it:
```
cannot decode incoming new object: json: cannot unmarshal array into Go struct field ParamSpec.spec.triggers.template.spec.params.default of type string
```
