### ISSUE TITLE
Unable to create EventListener with Gitlab Interceptor

### ISSUE THREAD

**Issue by weinix** [tektoncd/triggers#909]
# Expected Behavior
Create an EventListener with a Github interceptor.
# Actual Behavior
`Error from server (BadRequest): error when creating "./pipelinetriggers/eventlistener.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "name"
`
# Steps to Reproduce the Problem

Create EventListener with below yaml file:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-listener-interceptor
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-gitlab-triggers
  triggers:
  - name: gitlab-listener
    interceptors:
    - gitlab:
        secretRef:
          secretName: gitlab-trigger-secret
          secretKey: secretToken
        eventTypes:
          - Push Hook
    bindings:
    - ref: build-deploy-binding
    template:
      name: build-deploy-template
---

```

# Additional Info

- Kubernetes version: Kind

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
 ```
- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.14.0
Pipeline version: v0.20.0
Triggers version: v0.11.0
Dashboard version: v0.13.0
```
