### ISSUE TITLE
How to set the nodeselector and tolerances of the pipelinerun pod created by triggers

### ISSUE THREAD

**Issue by lqy1992** [tektoncd/triggers#924]
### How to set the node node selector and tolerances of the pipelinerun pod created by triggers
I refer to the official website examples to configure my CICD tasks.
https://github.com/tektoncd/triggers/tree/master/examples
But I found that I can't control the related configuration of nodeselector and tolerances of the generated cicd pod.
I only found the configuration of EventListener in the official website instance document。
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
   name: listener-tolerations
spec:
  serviceAccountName: tekton-triggers-example-sa
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            tolerations:
            - key: key
              value: value
              operator: Equal
              effect: NoSchedule
  triggers:
    - name: foo-trig
      bindings:
        - ref: pipeline-binding
        - ref: message-binding
      template:
        ref: pipeline-template
```
