### ISSUE TITLE
Proposal: Add cel logic to applying trigger bindings

### ISSUE THREAD

**Issue by jmcshane** [tektoncd/triggers#940]
### Feature request

Allow triggerbindings to be applied based off a cel selector

### Use case

Here's my use case, we are trying to do an "initiating" pipeline that operates based off all the different github events that can be fired on a repository. This can be "issue comment", "pr opened or updated", "pr closed", "pr comment", "release". We want to build a pipeline that runs with a flag based off the event type defined from that git context. As it is now, I have to build a whole trigger block for each event type:

```
  triggers:
    - name: pullrequest-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.action == "opened" ||
              body.action == "synchronize"
            ##conditions for pullrequest event
      bindings:
        - ref: pullrequest-triggerbinding
        - ref: pullrequest-event-triggerbinding
      template:
        name: initiating-triggertemplate
    - name: mainmerge-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.action == "closed" && 
              body.pull_request.merged == true
            ##conditions for mainmerge event
      bindings:
        - ref: pullrequest-triggerbinding
        - ref: mainmerge-event-triggerbinding
      template:
        name: initiating-triggertemplate
...etc
```

If I could do conditions on the bindings, then I could make this a single listener like this:

```
    - name: mainmerge-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - pull_request
      bindings:
        - ref: pullrequest-triggerbinding
        - cel:
            filter: >-
              body.action == "closed" && 
              body.pull_request.merged == true
            ##conditions for mainmerge event
          ref: mainmerge-event-triggerbinding
        - cel:
            filter: >-
              body.action == "opened" ||
              body.action == "synchronize"
            ##conditions for pullrequest event
          ref: pullrequest-event-triggerbinding
      template:
        name: initiating-triggertemplate
```

This would allow lots of different conditions to be built into a single trigger binding list for a more flexible template.
