### ISSUE TITLE
Feature: Allow triggerbinding and triggertemplate refs to be populated by tekton expressions

### ISSUE THREAD

**Issue by jmcshane** [tektoncd/triggers#948]
### Feature request

Currently, triggerbinding and triggertemplate references must be hardcoded strings. In this feature requests, these strings can be populated by an expression, possibly adding a new field in the `TriggerSpecBinding` and `TriggerSpecTemplate` spec besides `Ref` to account for this difference in how the values would be populated.

### Use case

This would allow Trigger objects to be more flexible to support a range of options based on the inputs. A couple small use cases:

- Github PR event has Repository owner in the body. This field could be used to select pipelines or binding metadata that are specific to that set of repositories. For example, a triggerbinding that associates the GH repository owner to information about that owner stored in a set of values on that binding.
- If trigger processing can determine whether or not a binding needs a workspace with a new volume claim, existing volume claim, or no workspace (via an extension), the Trigger processing could select the TriggerTemplate that has each one of these.

**Comment by jmcshane** [comment]
I've been looking at the code here and this looks like it could be done in the `template` package right before `template.ResolveTrigger` is invoked. The `template.ResolveParams` method already takes a set of parameters with the event body and extensions and resolves those to specific values. In this case, we would either:

1. Iterate through all the `Ref` fields and look for Tekton expressions with `findTektonExpressions`, then update the `Ref` field to the resolved value before invoking ResolveTrigger
2. Process an added field, potentially named `Expr`, processing them using similar logic in the `template.applyEventValuesToParams` function

**Comment by jmcshane** [comment]
Here's a simple example of why this could be useful. Let's say a Tekton system wants to track the resource owner for a set of pipelines that it triggers, but processes the triggers centrally. An event from Github would have the field `body.repository.owner.login`. This field could be used to reference a Triggerbinding per Github organization that could be added to the metadata of each PipelineRun or TaskRun. For example:

```
kind: Trigger
spec:
  bindings:
  - dynamicRef: owner-info-$(body.repository.owner.login)
     ref: default-owner-info
  - ref: another-triggerbinding
  template:
    ref: my-template
```

Then the dynamic ref could add metadata such as:

```
kind: TriggerBinding
metadata:
  name: owner-info-myteam
spec:
  params:
  - name: contact
     value: my-team@org.com
  - name: slack-room-name
     value: my-awesome-room
  ....
```

But, the default behavior could allow pipelines to still run without this meta information:

```
kind: TriggerBinding
metadata:
  name: default-owner-info
spec:
  params:
  - name: contact
     value: central-team@org.com
  - name: slack-room-name
     value: default-notifier-room
  ....
```

Then, the triggertemplate could use that data in labels/annotations/parameters as needed:

```
  spec:
    params:
    - name: contact
    - name: slack-room-name
    ....
    resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          tekton.dev/slack-room: $(tt.params.slack-room-name)
          tekton.dev/contact: $(tt.params.contact)
      spec:
        pipelineRef:
          name: my-pipeline
```

**Comment by jmcshane** [comment]
great question. one thing you see in this example is that dynamic bindings are often paired with dynamic templates. putting the default data in a resolved binding allows us to avoid repeating the values across all the templates that may consume that information

**Comment by joebertj** [comment]
I basically need to select a pvc based on two parameters:
```
      params:
      - name: app
        value: $(tt.params.application)
      - name: subapp
        value: $(tt.params.subapplication)
      workspaces:
      - name: shared-workspace
        persistentvolumeclaim:
          claimName: $(tt.params.application)-$(tt.params.subapplication)-pvc
```
