### ISSUE TITLE
nodeAffinity not respected

### ISSUE THREAD

**Issue by freefood89** [tektoncd/triggers#964]
Hello, I'm having problems scheduling builds on specific node pools in GKE. I think this might be a bug

# Expected Behavior

Pipeline tasks to be scheduled onto nodes with tags `blah/instance-family: n2` or `blah/instance-family: c2`

# Actual Behavior

Tasks are randomly scheduled onto nodes regardless of affinity

# Steps to Reproduce the Problem

1. Label node in cluster with `blah/instance-family: n2`
2. Add affinity section to podTemplate:

```yaml
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: publish-image-
      spec:
        podTemplate:
          tolerations:
            - key: "blah/cpu"
              operator: "Exists"
              effect: "NoSchedule"
          # nodeSelector:
          #   blah/instance-family: n2
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: blah/instance-family
                    operator: In
                    values:
                    - n2
                    - c2
```

3. Trigger pipeline from Github 

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: `v0.17.3`
- Tekton Triggers version: `v0.9.1`

- `nodeSelector` shown in the snippet above does what's expected when uncommented

- the scheduled task pods did have an affinity section, but only a podAffinity for the affinity assistant:
```yaml
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: affinity-assistant
          app.kubernetes.io/instance: affinity-assistant-1ef18496e5
      topologyKey: kubernetes.io/hostname
```
- affinity-assistant also only had a podAntiAffinity:
```yaml
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: affinity-assistant
        topologyKey: kubernetes.io/hostname
      weight: 100
```
- using the "soft" affinity did not work either:
```yaml
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: publish-image-
      spec:
        podTemplate:
          tolerations:
            - key: "nosidelines.io/cpu"
              operator: "Exists"
              effect: "NoSchedule"
          # nodeSelector:
          #   nosidelines.io/instance-family: n2
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                  - key: nosidelines.io/instance-family
                    operator: In
                    values:
                    - n2
                    - c2
```
