### ISSUE TITLE
EventListener fails to reconcile when using Knative Service with "validation.webhook.serving.knative.dev" denied the request

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/triggers#983]
Hi,

thanks for all the effort to implement Knative Service with EventListeners! Unfortunately I´m struggeling with the following issue:

# Expected Behavior
Reconciliation loop is successful when using Knative Service with EventListeners

# Actual Behavior
Reconciliation loop is stuck with
```
{"level":"info","ts":"2021-03-05T09:01:10.826Z","logger":"controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"EventListener\", Namespace:\"default\", Name:\"sample\", UID:\"edf55d3f-4278-4615-9016-6fde4c57aa2a\", APIVersion:\"triggers.tekton.dev/v1alpha1\", ResourceVersion:\"60353\", FieldPath:\"\"}): type: 'Normal' reason: 'FinalizerUpdate' Updated \"sample\" finalizers"}
{"level":"info","ts":"2021-03-05T09:01:10.969Z","logger":"controller","caller":"eventlistener/eventlistener.go:501","msg":"Created EventListener Deployment el-sample in Namespace default","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"d3cec124-3d93-455a-a07a-2f956164212c","knative.dev/key":"default/sample"}
{"level":"info","ts":"2021-03-05T09:01:11.035Z","logger":"controller","caller":"controller/controller.go:530","msg":"Reconcile succeeded","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"d3cec124-3d93-455a-a07a-2f956164212c","knative.dev/key":"default/sample","duration":0.219598241}
{"level":"error","ts":"2021-03-05T09:01:11.115Z","logger":"controller","caller":"eventlistener/eventlistener.go:476","msg":"error updating to eventListener custom object: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"440ce3e9-7ec0-44e0-adfc-0690b6c7cb7c","knative.dev/key":"default/sample","stacktrace":"github.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).reconcileCustomObject\n\tgithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:476\ngithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:118\ngithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go:237\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"error","ts":"2021-03-05T09:01:11.115Z","logger":"controller","caller":"eventlistener/reconciler.go:291","msg":"Returned an error","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"440ce3e9-7ec0-44e0-adfc-0690b6c7cb7c","knative.dev/key":"default/sample","targetMethod":"ReconcileKind","error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","stacktrace":"github.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go:291\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"error","ts":"2021-03-05T09:01:11.121Z","logger":"controller","caller":"controller/controller.go:540","msg":"Reconcile error","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","duration":0.085800861,"error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"info","ts":"2021-03-05T09:01:11.121Z","logger":"controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"EventListener\", Namespace:\"default\", Name:\"sample\", UID:\"edf55d3f-4278-4615-9016-6fde4c57aa2a\", APIVersion:\"triggers.tekton.dev/v1alpha1\", ResourceVersion:\"60368\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier"}
{"level":"error","ts":"2021-03-05T09:01:11.151Z","logger":"controller","caller":"eventlistener/eventlistener.go:476","msg":"error updating to eventListener custom object: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"1aeaa5bc-bd8a-4952-9fb1-c00694bcccbf","knative.dev/key":"default/sample","stacktrace":"github.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).reconcileCustomObject\n\tgithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:476\ngithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:118\ngithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go:237\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"error","ts":"2021-03-05T09:01:11.152Z","logger":"controller","caller":"eventlistener/reconciler.go:291","msg":"Returned an error","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"1aeaa5bc-bd8a-4952-9fb1-c00694bcccbf","knative.dev/key":"default/sample","targetMethod":"ReconcileKind","error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","stacktrace":"github.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go:291\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"error","ts":"2021-03-05T09:01:11.152Z","logger":"controller","caller":"controller/controller.go:540","msg":"Reconcile error","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","duration":0.030855079,"error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"info","ts":"2021-03-05T09:01:11.152Z","logger":"controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"EventListener\", Namespace:\"default\", Name:\"sample\", UID:\"edf55d3f-4278-4615-9016-6fde4c57aa2a\", APIVersion:\"triggers.tekton.dev/v1alpha1\", ResourceVersion:\"60368\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier"}
{"level":"error","ts":"2021-03-05T09:01:11.185Z","logger":"controller","caller":"eventlistener/eventlistener.go:476","msg":"error updating to eventListener custom object: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"3e4828f3-e9ae-47a7-a1d0-817a65b90775","knative.dev/key":"default/sample","stacktrace":"github.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).reconcileCustomObject\n\tgithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:476\ngithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/triggers/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go:118\ngithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go:237\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"error","ts":"2021-03-05T09:01:11.185Z","logger":"controller","caller":"eventlistener/reconciler.go:291","msg":"Returned an error","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","knative.dev/traceid":"3e4828f3-e9ae-47a7-a1d0-817a65b90775","knative.dev/key":"default/sample","targetMethod":"ReconcileKind","error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","stacktrace":"github.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/triggers/pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go:291\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"error","ts":"2021-03-05T09:01:11.185Z","logger":"controller","caller":"controller/controller.go:540","msg":"Reconcile error","knative.dev/controller":"github.com.tektoncd.triggers.pkg.reconciler.v1alpha1.eventlistener.Reconciler","knative.dev/kind":"triggers.tekton.dev.EventListener","duration":0.033045688,"error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
{"level":"info","ts":"2021-03-05T09:01:11.187Z","logger":"controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"EventListener\", Namespace:\"default\", Name:\"sample\", UID:\"edf55d3f-4278-4615-9016-6fde4c57aa2a\", APIVersion:\"triggers.tekton.dev/v1alpha1\", ResourceVersion:\"60368\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator\ninvalid value: : metadata.annotations.serving.knative.dev/lastModifier"}
```

EventListener Status:
```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: sample
  namespace: default
...
status:
  conditions:
  - lastTransitionTime: "2021-03-05T09:01:10Z"
    status: "False"
    type: Deployment
  - lastTransitionTime: "2021-03-05T09:01:10Z"
    status: "False"
    type: Service
  configuration:
    generatedName: el-sample
```

The generated Knative Service looks good:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: el-sample
  namespace: default
...
status:
  address:
    url: http://el-sample.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2021-03-05T09:01:33Z"
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: "2021-03-05T09:01:33Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-03-05T09:01:33Z"
    status: "True"
    type: RoutesReady
  latestCreatedRevisionName: el-sample-00001
  latestReadyRevisionName: el-sample-00001
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: el-sample-00001
  url: http://el-sample.default.example.com
```

# Steps to Reproduce the Problem
I´m using a KinD cluster v1.18.8 with Triggers 1.12.0 and tried Knative Serving versions between 0.18 and 0.21.

EventListener:
```yaml
apiVersion: "triggers.tekton.dev/v1alpha1"
kind: "EventListener"
metadata:
  name: "sample"
  namespace: "default"
spec:
  resources:
    customResource:
      apiVersion: "serving.knative.dev/v1"
      kind: "Service"
      metadata:
      spec:
        template:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "5m"
                    memory: "15Mi"
            serviceAccountName: "tekton-triggers-listener"
  serviceAccountName: "tekton-triggers-listener"
  triggers:
    - name: "sample-pr"
      template:
        spec:
          resourcetemplates:
            - apiVersion: "tekton.dev/v1beta1"
              kind: "PipelineRun"
              metadata:
                generateName: "cf-pr-"
                namespace: "default"
              spec:
                pipelineRef:
                  name: "pipeline"
```

# Additional Info

- Kubernetes version: `1.18.8`
- Tekton Pipeline version: `0.21.0`
- Tekton Triggers version: `0.12.0`
