### ISSUE TITLE
Github webhook doesn't work on page but works with curl

### ISSUE THREAD

**Issue by garyyang85** [tektoncd/triggers#985]
# Expected Behavior
Github webhook works
# Actual Behavior
202 response received on page, but there is error found in event listener log. This behavior is similar with #656.  My point is that I can use the HMAC tool to generate the Signature, and it works good in curl.  But when is trigger from github webhook page, it reports error in log, and no task triggered. 
# Steps to Reproduce the Problem

1.  create a event listener on kuberentes
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-github-sa
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - ref: github-pr-binding
      template:
        name: github-template
```
2.  config webhook in github
3.  change a file and push to git repo
4.  check the webhook post request, generate signature, post the same body in curl

# Additional Info

- Kubernetes version:

Kubernetes Version: v1.19.0+7070803

- Tekton Pipeline version:

 Client version: 0.13.1
Pipeline version: v0.16.3
Triggers version: v0.8.1

logs in event listener:
```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:177","msg":"failed to ApplyEventValuesToParams: failed to marshal event: failed to unmarshal request body: invalid character 'p' looking for beginning of value","knative.dev/controller":"eventlistener","/triggers-eventid":"rh59s","/trigger":"github-listener","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:177\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:94"}
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```
